# CARGA RESTAURANTES PARA CONOCER gmap_id

In [1]:
import pandas as pd
import os

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos CSV
file_dir = os.path.join(current_dir, 'Datos Limpios', 'metadata')

# Construir la ruta completa al archivo CSV
csv_file_path = os.path.join(file_dir, 'restaurantes.csv')

# Verificar si el archivo existe
if os.path.isfile(csv_file_path):
    # Cargar el archivo CSV en un DataFrame
    restaurantes = pd.read_csv(csv_file_path)
    print("Archivo cargado correctamente.")
else:
    print(f"El archivo {csv_file_path} no existe.")

Archivo cargado correctamente.

In [2]:
restaurantes = restaurantes["gmap_id"]

# PRUEBA CARGA REVIEWS

In [3]:
import time

# Inicia el temporizador
inicio = time.time()

01-ALABAMA

In [4]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-Alabama')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            alabama = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(alabama)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id                    name           time  rating  \
0        1.140438e+20           Kanisha Mixon  1597168272670       5
1        1.160090e+20          Brandie Hodges  1609899039594       5
2        1.062399e+20             Sharon King  1547235290843       4
3        1.049701e+20         Veronica Pierce  1517709403534       5
4        1.105875e+20  Whitney Waldon Collier  1535245718492       5
...               ...                     ...            ...     ...
1799995  1.049364e+20           Keith Serafin  1599158137870       1
1799996  1.133331e+20          Brenda McClure  1560738061123       5
1799997  1.048099e+20              Jan Peters  1582415271708       5
1799998  1.121136e+20          Brittany Banks  1530991256525       5
1799999  1.026253e+20          Kasey Robinson  1523049198962       5

                                                      text  pics  \
0        Very Personable staff! Beautiful and clean env...  None
1                                     Best clothing intown  None
2                                                     None  None
3                                                     None  None
4                                                     None  None
...                                                    ...   ...
1799995                                               None  None
1799996                                               None  None
1799997                                               None  None
1799998                                               None  None
1799999                                               None  None

                                                      resp  \
0                                                     None
1                                                     None
2                                                     None
3                                                     None
4                                                     None
...                                                    ...
1799995  {'time': 1599161854585, 'text': 'Hey Keith!  P...
1799996                                               None
1799997                                               None
1799998                                               None
1799999                                               None

                                       gmap_id
0        0x8862134e67ff5c87:0x38b5e2ae99cd1fcf
1        0x8862134e67ff5c87:0x38b5e2ae99cd1fcf
2        0x8862134e67ff5c87:0x38b5e2ae99cd1fcf
3        0x8862134e67ff5c87:0x38b5e2ae99cd1fcf
4        0x8862134e67ff5c87:0x38b5e2ae99cd1fcf
...                                        ...
1799995  0x8889f923aff52f69:0xf42d23231aafe68f
1799996  0x8889f923aff52f69:0xf42d23231aafe68f
1799997  0x8889f923aff52f69:0xf42d23231aafe68f
1799998  0x8889f923aff52f69:0xf42d23231aafe68f
1799999  0x8889f923aff52f69:0xf42d23231aafe68f

[1800000 rows x 8 columns]

In [5]:
alabama.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.140438e+20,Kanisha Mixon,1597168272670,5,Very Personable staff! Beautiful and clean env...,None,None,0x8862134e67ff5c87:0x38b5e2ae99cd1fcf
1,1.160090e+20,Brandie Hodges,1609899039594,5,Best clothing intown,None,None,0x8862134e67ff5c87:0x38b5e2ae99cd1fcf
2,1.062399e+20,Sharon King,1547235290843,4,None,None,None,0x8862134e67ff5c87:0x38b5e2ae99cd1fcf
3,1.049701e+20,Veronica Pierce,1517709403534,5,None,None,None,0x8862134e67ff5c87:0x38b5e2ae99cd1fcf
4,1.105875e+20,Whitney Waldon Collier,1535245718492,5,None,None,None,0x8862134e67ff5c87:0x38b5e2ae99cd1fcf

Filtro cruzado con los datos limpios de metadata (queremos solo comentarios sobre los locales que consideramos restaurantes y/o afines)

In [6]:
alabama_filtrado = alabama.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [7]:
alabama_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 183564 entries, 0 to 183563
Data columns (total 8 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   user_id  183564 non-null  float64
 1   name     183564 non-null  object
 2   time     183564 non-null  int64
 3   rating   183564 non-null  int64
 4   text     105727 non-null  object
 5   pics     4674 non-null    object
 6   resp     19545 non-null   object
 7   gmap_id  183564 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 11.2+ MB

Transformamos a fecha la columna time

In [8]:
# Convertir la columna 'time' a datetime
alabama_filtrado['time'] = pd.to_datetime(alabama_filtrado['time'], unit='ms')

In [9]:
alabama_filtrado = alabama_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [10]:
alabama_filtrado.head()

,user_id,name,time,rating,text,gmap_id
0,1.179759e+20,Anthony Roberts,2016-05-16 23:56:53.514,4,"On the higher end of price for pizza, but they...",0x8889221157fb3455:0x5c125c40c3eccc2a
1,1.143165e+20,Jonathan Robert,2015-11-15 21:45:39.865,3,"Food was ok, felt like the atmosphere as well ...",0x8889221157fb3455:0x5c125c40c3eccc2a
2,1.136326e+20,Brian Harvey,2016-07-23 17:05:49.247,4,"Good food, service so so",0x8889221157fb3455:0x5c125c40c3eccc2a
3,1.076840e+20,Ashley Maddox,2015-09-15 01:06:59.480,5,Love it,0x8889221157fb3455:0x5c125c40c3eccc2a
4,1.126036e+20,West Martin,2013-10-24 17:14:56.130,5,Yum,0x8889221157fb3455:0x5c125c40c3eccc2a

Evaluamos duplicados en tres conceptos claves, al mismo tiempo (se duplicó una entrada), el mismo texto y el mismo usuario. Estos tres conceptos no deberían repetirse, pudiendo un mismo usuario comentar al mismo tiempo dos cosas diferentes, o en diferentes tiempos lo mismo, pero no los tres conceptos iguales.

In [11]:
alabama_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    176928
True       6636
Name: count, dtype: int64

Una pequeña comprobación de muestra

In [12]:
duplicados = alabama_filtrado[alabama_filtrado.duplicated(subset=["time", "text", "user_id"], keep=False)]
duplicados[duplicados["name"] == "Anthony Roberts"]

,user_id,name,time,rating,text,gmap_id
0,1.179759e+20,Anthony Roberts,2016-05-16 23:56:53.514,4,"On the higher end of price for pizza, but they...",0x8889221157fb3455:0x5c125c40c3eccc2a
168,1.179759e+20,Anthony Roberts,2016-05-16 23:56:53.514,4,"On the higher end of price for pizza, but they...",0x8889221157fb3455:0x5c125c40c3eccc2a
58692,1.179759e+20,Anthony Roberts,2016-04-09 03:24:57.743,5,You can't beat 1/2 price drinks during happy h...,0x888923bccd6a2787:0x2a9a298802d0b047
58709,1.179759e+20,Anthony Roberts,2016-04-09 03:24:57.743,5,You can't beat 1/2 price drinks during happy h...,0x888923bccd6a2787:0x2a9a298802d0b047

Se manejan los duplicados para eliminarlos y tener listo el dataset del Estado para un análisis de sentimientos posterior (tanto del Estado como de la industria completa)

In [13]:
alabama_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [14]:
alabama_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    176928
Name: count, dtype: int64

Se guarda el archivo limpio

In [15]:
import os
import pandas as pd

# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "metadata" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "metadata"
alabama_filtrado.to_csv(os.path.join(ruta_reviews, "01-alabama.csv"),index= False)

02-Alaska

In [16]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-Alaska')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            alaska = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(alaska)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

             user_id               name           time  rating  \
0       1.091298e+20         Nicki Gore  1566331951619       5
1       1.132409e+20      Allen Ratliff  1504917982385       5
2       1.130448e+20  Jonathan Tringali  1474765901185       4
3       1.103292e+20             S Blad  1472858535682       4
4       1.089896e+20     Daniel Formoso  1529649811341       5
...              ...                ...            ...     ...
521510  1.063779e+20      Emily Stanker  1595464050942       3
521511  1.182198e+20          Jeri Hill  1573608171589       3
521512  1.170553e+20     Stas Moszynski  1520481904459       3
521513  1.130331e+20        Kalli Kline  1612036301339       4
521514  1.091719e+20   Ed ThePopPunkKid  1571068334950       5

                                                     text  pics  resp  \
0       We always stay here when in Valdez for silver ...  None  None
1       Great campground for the price. Nice hot unlim...  None  None
2       We tent camped here for 2 nights while explori...  None  None
3       This place is just a few miles outside Valdez,...  None  None
4       Probably the nicest and cleanest campground we...  None  None
...                                                   ...   ...   ...
521510                                               None  None  None
521511                                               None  None  None
521512                                               None  None  None
521513                                               None  None  None
521514                                               None  None  None

                                      gmap_id
0       0x56b646ed2220b77f:0xd8975e316de80952
1       0x56b646ed2220b77f:0xd8975e316de80952
2       0x56b646ed2220b77f:0xd8975e316de80952
3       0x56b646ed2220b77f:0xd8975e316de80952
4       0x56b646ed2220b77f:0xd8975e316de80952
...                                       ...
521510  0x540c25a454fb47cf:0xf0788e2fb7ba1907
521511  0x540c25a454fb47cf:0xf0788e2fb7ba1907
521512  0x540c25a454fb47cf:0xf0788e2fb7ba1907
521513  0x540c25a454fb47cf:0xf0788e2fb7ba1907
521514  0x540c25a454fb47cf:0xf0788e2fb7ba1907

[521515 rows x 8 columns]

In [17]:
alaska.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.091298e+20,Nicki Gore,1566331951619,5,We always stay here when in Valdez for silver ...,None,None,0x56b646ed2220b77f:0xd8975e316de80952
1,1.132409e+20,Allen Ratliff,1504917982385,5,Great campground for the price. Nice hot unlim...,None,None,0x56b646ed2220b77f:0xd8975e316de80952
2,1.130448e+20,Jonathan Tringali,1474765901185,4,We tent camped here for 2 nights while explori...,None,None,0x56b646ed2220b77f:0xd8975e316de80952
3,1.103292e+20,S Blad,1472858535682,4,"This place is just a few miles outside Valdez,...",None,None,0x56b646ed2220b77f:0xd8975e316de80952
4,1.089896e+20,Daniel Formoso,1529649811341,5,Probably the nicest and cleanest campground we...,None,None,0x56b646ed2220b77f:0xd8975e316de80952

In [18]:
alaska_filtrado = alaska.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [19]:
alaska_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18909 entries, 0 to 18908
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   user_id  18909 non-null  float64
 1   name     18909 non-null  object
 2   time     18909 non-null  int64
 3   rating   18909 non-null  int64
 4   text     12029 non-null  object
 5   pics     861 non-null    object
 6   resp     1242 non-null   object
 7   gmap_id  18909 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 1.2+ MB

In [20]:
# Convertir la columna 'time' a datetime
alaska_filtrado['time'] = pd.to_datetime(alaska_filtrado['time'], unit='ms')

In [21]:
alaska_filtrado = alaska_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [22]:
alaska_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [23]:
alaska_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    18630
Name: count, dtype: int64

In [24]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
alaska_filtrado.to_csv(os.path.join(ruta_reviews, "02-alaska.csv"),index= False)

03-Arizona

In [25]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-Arizona')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            arizona = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(arizona)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id              name           time  rating  \
0        1.183560e+20      Vicki Ullery  1628718071358       5
1        1.126523e+20        Doc Kovacs  1609796129431       5
2        1.089879e+20        Pedro Diaz  1594225668169       1
3        1.069277e+20       Brandon Ray  1622676189509       5
4        1.090535e+20        T. Bennett  1434829263041       5
...               ...               ...            ...     ...
2099995  1.107824e+20   Nina Kitsmiller  1516355557532       4
2099996  1.053941e+20        Green Leaf  1555811396904       3
2099997  1.006415e+20  Krystal Scoggins  1570621761138       5
2099998  1.172314e+20      John DiMarco  1547243677304       5
2099999  1.042303e+20      Jody burgess  1575518305688       1

                                                      text  pics  \
0        Gwen was so informative and made me feel comfo...  None
1        Dr. Huyhn is an ethical skilled dentist. Her s...  None
2        Not sure if one star is fair but my situation ...  None
3        Best dentist office I've ever had. Love everyt...  None
4        I've been coming to Oasis dentistry for a whil...  None
...                                                    ...   ...
2099995                    Cindy is great.... staff is ok.  None
2099996                                               None  None
2099997                                               None  None
2099998                                               None  None
2099999                                               None  None

                                                      resp  \
0                                                     None
1                                                     None
2                                                     None
3                                                     None
4                                                     None
...                                                    ...
2099995                                               None
2099996                                               None
2099997                                               None
2099998                                               None
2099999  {'time': 1575564140346, 'text': 'Good Morning....

                                       gmap_id
0        0x872b5dae3c5fcfa7:0xf0f8b286a2537821
1        0x872b5dae3c5fcfa7:0xf0f8b286a2537821
2        0x872b5dae3c5fcfa7:0xf0f8b286a2537821
3        0x872b5dae3c5fcfa7:0xf0f8b286a2537821
4        0x872b5dae3c5fcfa7:0xf0f8b286a2537821
...                                        ...
2099995  0x872a3e98eb27210f:0xa7a246259f678edf
2099996  0x872a3e98eb27210f:0xa7a246259f678edf
2099997  0x872a3e98eb27210f:0xa7a246259f678edf
2099998  0x872a3e98eb27210f:0xa7a246259f678edf
2099999  0x872a3e98eb27210f:0xa7a246259f678edf

[2100000 rows x 8 columns]

In [26]:
arizona.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.183560e+20,Vicki Ullery,1628718071358,5,Gwen was so informative and made me feel comfo...,None,None,0x872b5dae3c5fcfa7:0xf0f8b286a2537821
1,1.126523e+20,Doc Kovacs,1609796129431,5,Dr. Huyhn is an ethical skilled dentist. Her s...,None,None,0x872b5dae3c5fcfa7:0xf0f8b286a2537821
2,1.089879e+20,Pedro Diaz,1594225668169,1,Not sure if one star is fair but my situation ...,None,None,0x872b5dae3c5fcfa7:0xf0f8b286a2537821
3,1.069277e+20,Brandon Ray,1622676189509,5,Best dentist office I've ever had. Love everyt...,None,None,0x872b5dae3c5fcfa7:0xf0f8b286a2537821
4,1.090535e+20,T. Bennett,1434829263041,5,I've been coming to Oasis dentistry for a whil...,None,None,0x872b5dae3c5fcfa7:0xf0f8b286a2537821

In [27]:
arizona_filtrado = arizona.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [28]:
arizona_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 345465 entries, 0 to 345464
Data columns (total 8 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   user_id  345465 non-null  float64
 1   name     345465 non-null  object
 2   time     345465 non-null  int64
 3   rating   345465 non-null  int64
 4   text     212916 non-null  object
 5   pics     12148 non-null   object
 6   resp     46807 non-null   object
 7   gmap_id  345465 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 21.1+ MB

In [29]:
# Convertir la columna 'time' a datetime
arizona_filtrado['time'] = pd.to_datetime(arizona_filtrado['time'], unit='ms')

In [30]:
arizona_filtrado = arizona_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [31]:
arizona_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [32]:
arizona_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    328433
Name: count, dtype: int64

In [33]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
arizona_filtrado.to_csv(os.path.join(ruta_reviews, "03-arizona.csv"),index= False)

04-Arkansas

In [34]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-Arkansas')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            arkansas = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(arkansas)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id               name           time  rating  \
0        1.083175e+20       cayla layman  1630760310327       5
1        1.021233e+20    thomas mcdaniel  1631038071292       1
2        1.040671e+20        tony shelby  1627697592294       5
3        1.071093e+20   james williamson  1624394171528       3
4        1.146117e+20      Robert Hardin  1630615588505       5
...               ...                ...            ...     ...
2399995  1.064410e+20        David Lopez  1567199396659       5
2399996  1.064081e+20       Evelyn Perez  1534338443123       5
2399997  1.090229e+20  Joey Higginbotham  1563308063047       5
2399998  1.182165e+20            Byron M  1575651851197       3
2399999  1.107684e+20        Jesus Perez  1535931026049       2

                                                      text  \
0        Making West Memphis proud! Love this spot for ...
1        Small burrito period high price. U dont get yo...
2          I love the food and the staff are very friendly
3        It was a New Restaurant and I never had there ...
4                                   Great food and service
...                                                    ...
2399995                                               None
2399996                                               None
2399997                                               None
2399998                                               None
2399999                                               None

                                                      pics  \
0        [{'url': ['https://lh5.googleusercontent.com/p...
1                                                     None
2                                                     None
3                                                     None
4                                                     None
...                                                    ...
2399995                                               None
2399996                                               None
2399997                                               None
2399998                                               None
2399999                                               None

                                                      resp  \
0        {'time': 1631039710340, 'text': 'Thank you ver...
1        {'time': 1631039604586, 'text': 'Sorry for you...
2        {'time': 1627707384428, 'text': 'Thank you. Pl...
3        {'time': 1624395299305, 'text': 'Hi Mr. Willia...
4        {'time': 1630668653435, 'text': 'Thank you for...
...                                                    ...
2399995                                               None
2399996                                               None
2399997                                               None
2399998                                               None
2399999                                               None

                                       gmap_id
0        0x87d57755954b200d:0x157d3f3bad3d37a4
1        0x87d57755954b200d:0x157d3f3bad3d37a4
2        0x87d57755954b200d:0x157d3f3bad3d37a4
3        0x87d57755954b200d:0x157d3f3bad3d37a4
4        0x87d57755954b200d:0x157d3f3bad3d37a4
...                                        ...
2399995  0x87ca4cb163792ef9:0x3b3c2f90ac5931b0
2399996  0x87ca4cb163792ef9:0x3b3c2f90ac5931b0
2399997  0x87ca4cb163792ef9:0x3b3c2f90ac5931b0
2399998  0x87ca4cb163792ef9:0x3b3c2f90ac5931b0
2399999  0x87ca4cb163792ef9:0x3b3c2f90ac5931b0

[2400000 rows x 8 columns]

In [35]:
arkansas.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.083175e+20,cayla layman,1630760310327,5,Making West Memphis proud! Love this spot for ...,[{'url': ['https://lh5.googleusercontent.com/p...,"{'time': 1631039710340, 'text': 'Thank you ver...",0x87d57755954b200d:0x157d3f3bad3d37a4
1,1.021233e+20,thomas mcdaniel,1631038071292,1,Small burrito period high price. U dont get yo...,None,"{'time': 1631039604586, 'text': 'Sorry for you...",0x87d57755954b200d:0x157d3f3bad3d37a4
2,1.040671e+20,tony shelby,1627697592294,5,I love the food and the staff are very friendly,None,"{'time': 1627707384428, 'text': 'Thank you. Pl...",0x87d57755954b200d:0x157d3f3bad3d37a4
3,1.071093e+20,james williamson,1624394171528,3,It was a New Restaurant and I never had there ...,None,"{'time': 1624395299305, 'text': 'Hi Mr. Willia...",0x87d57755954b200d:0x157d3f3bad3d37a4
4,1.146117e+20,Robert Hardin,1630615588505,5,Great food and service,None,"{'time': 1630668653435, 'text': 'Thank you for...",0x87d57755954b200d:0x157d3f3bad3d37a4

In [36]:
arkansas_filtrado = arkansas.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [37]:
arkansas_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109948 entries, 0 to 109947
Data columns (total 8 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   user_id  109948 non-null  float64
 1   name     109948 non-null  object
 2   time     109948 non-null  int64
 3   rating   109948 non-null  int64
 4   text     63892 non-null   object
 5   pics     2572 non-null    object
 6   resp     12040 non-null   object
 7   gmap_id  109948 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 6.7+ MB

In [38]:
# Convertir la columna 'time' a datetime
arkansas_filtrado['time'] = pd.to_datetime(arkansas_filtrado['time'], unit='ms')

In [39]:
arkansas_filtrado = arkansas_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [40]:
arkansas_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [41]:
arkansas_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    106814
Name: count, dtype: int64

In [42]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
arkansas_filtrado.to_csv(os.path.join(ruta_reviews, "04-arkansas.csv"),index= False)

05-California

In [43]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-California')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            california = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(california)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id                 name           time  rating  \
0        1.089912e+20              Song Ro  1609909927056       5
1        1.112903e+20          Rafa Robles  1612849648663       5
2        1.126404e+20            David Han  1583643882296       4
3        1.174403e+20          Anthony Kim  1551938216355       5
4        1.005808e+20        Mario Marzouk  1494910901933       5
...               ...                  ...            ...     ...
2699995  1.113423e+20          Byunguk Kim  1573362674409       5
2699996  1.080818e+20  Ceveda Craytonhooks  1580608853411       5
2699997  1.175914e+20     Natacha Thompson  1528597806165       5
2699998  1.124266e+20       Eleanor Aikins  1551203379295       5
2699999  1.122199e+20            Thai Love  1553880485978       5

                                                      text  \
0                             Love there korean rice cake.
1                                           Good very good
2         They make Korean traditional food very properly.
3                           Short ribs are very delicious.
4             Great food and prices the portions are large
...                                                    ...
2699995                                               None
2699996  Beautiful salon. The staff and atmosphere were...
2699997  Flo is a great beautician.   She is very patie...
2699998  I Been going to have a variety of hair style a...
2699999  Teri is awesome she is a dread loc master. She...

                                                      pics  \
0                                                     None
1                                                     None
2                                                     None
3                                                     None
4                                                     None
...                                                    ...
2699995                                               None
2699996                                               None
2699997  [{'url': ['https://lh5.googleusercontent.com/p...
2699998                                               None
2699999                                               None

                                                      resp  \
0                                                     None
1                                                     None
2                                                     None
3                                                     None
4                                                     None
...                                                    ...
2699995                                               None
2699996                                               None
2699997  {'time': 1528598932831, 'text': 'Thank you!  I...
2699998                                               None
2699999                                               None

                                       gmap_id
0        0x80c2c778e3b73d33:0xbdc58662a4a97d49
1        0x80c2c778e3b73d33:0xbdc58662a4a97d49
2        0x80c2c778e3b73d33:0xbdc58662a4a97d49
3        0x80c2c778e3b73d33:0xbdc58662a4a97d49
4        0x80c2c778e3b73d33:0xbdc58662a4a97d49
...                                        ...
2699995  0x80c2bea30829f279:0x39aa953ee93734ed
2699996  0x8094675073616747:0x9f935a9b9046a9ba
2699997  0x8094675073616747:0x9f935a9b9046a9ba
2699998  0x8094675073616747:0x9f935a9b9046a9ba
2699999  0x8094675073616747:0x9f935a9b9046a9ba

[2700000 rows x 8 columns]

In [44]:
california.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.089912e+20,Song Ro,1609909927056,5,Love there korean rice cake.,None,None,0x80c2c778e3b73d33:0xbdc58662a4a97d49
1,1.112903e+20,Rafa Robles,1612849648663,5,Good very good,None,None,0x80c2c778e3b73d33:0xbdc58662a4a97d49
2,1.126404e+20,David Han,1583643882296,4,They make Korean traditional food very properly.,None,None,0x80c2c778e3b73d33:0xbdc58662a4a97d49
3,1.174403e+20,Anthony Kim,1551938216355,5,Short ribs are very delicious.,None,None,0x80c2c778e3b73d33:0xbdc58662a4a97d49
4,1.005808e+20,Mario Marzouk,1494910901933,5,Great food and prices the portions are large,None,None,0x80c2c778e3b73d33:0xbdc58662a4a97d49

In [45]:
california_filtrado = california.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [46]:
california_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 815755 entries, 0 to 815754
Data columns (total 8 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   user_id  815755 non-null  float64
 1   name     815755 non-null  object
 2   time     815755 non-null  int64
 3   rating   815755 non-null  int64
 4   text     469354 non-null  object
 5   pics     35052 non-null   object
 6   resp     54286 non-null   object
 7   gmap_id  815755 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 49.8+ MB

In [47]:
# Convertir la columna 'time' a datetime
california_filtrado['time'] = pd.to_datetime(california_filtrado['time'], unit='ms')

In [48]:
california_filtrado = california_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [49]:
california_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [50]:
california_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    783172
Name: count, dtype: int64

In [51]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
california_filtrado.to_csv(os.path.join(ruta_reviews, "05-california.csv"),index= False)

06-Colorado

In [52]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-Colorado')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            colorado = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(colorado)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id                            name           time  rating  \
0        1.089905e+20                     mgshouldice  1484353876202       3
1        1.074040e+20               Sabrina Holsinger  1484195642287       4
2        1.128198e+20                       Tad Amore  1459554530689       5
3        1.025918e+20  Victoria Elizabeth De La Torre  1483746469128       1
4        1.040089e+20               Luis Garcia-Lopez  1542782383361       5
...               ...                             ...            ...     ...
2399995  1.032026e+20                 Corinne Wardell  1560168139164       5
2399996  1.041474e+20                   Chris Bodeman  1550865056326       5
2399997  1.175542e+20                    David Finley  1529584611730       5
2399998  1.008053e+20              Rhiannon Nuttleman  1617631121593       5
2399999  1.110916e+20                  Heather Fierro  1550623284980       5

                                                      text  pics  resp  \
0        Don't mix this up with their high school. It w...  None  None
1        Teachers are great and you can tell the genual...  None  None
2        Great school can't wait for my son to start ne...  None  None
3                                                     None  None  None
4                                                     None  None  None
...                                                    ...   ...   ...
2399995                                               None  None  None
2399996                                               None  None  None
2399997                                               None  None  None
2399998  If you are seeking for the truth in the Bible,...  None  None
2399999  The only church I’ve been to where all my answ...  None  None

                                       gmap_id
0        0x876c75945568003d:0x2fae418af6d1e13a
1        0x876c75945568003d:0x2fae418af6d1e13a
2        0x876c75945568003d:0x2fae418af6d1e13a
3        0x876c75945568003d:0x2fae418af6d1e13a
4        0x876c75945568003d:0x2fae418af6d1e13a
...                                        ...
2399995   0x876c7be538675097:0xad445b850a4ba1f
2399996   0x876c7be538675097:0xad445b850a4ba1f
2399997   0x876c7be538675097:0xad445b850a4ba1f
2399998  0x876b87b4931a97e9:0xeb1b701effd598fb
2399999  0x876b87b4931a97e9:0xeb1b701effd598fb

[2400000 rows x 8 columns]

In [53]:
colorado.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.089905e+20,mgshouldice,1484353876202,3,Don't mix this up with their high school. It w...,None,None,0x876c75945568003d:0x2fae418af6d1e13a
1,1.074040e+20,Sabrina Holsinger,1484195642287,4,Teachers are great and you can tell the genual...,None,None,0x876c75945568003d:0x2fae418af6d1e13a
2,1.128198e+20,Tad Amore,1459554530689,5,Great school can't wait for my son to start ne...,None,None,0x876c75945568003d:0x2fae418af6d1e13a
3,1.025918e+20,Victoria Elizabeth De La Torre,1483746469128,1,None,None,None,0x876c75945568003d:0x2fae418af6d1e13a
4,1.040089e+20,Luis Garcia-Lopez,1542782383361,5,None,None,None,0x876c75945568003d:0x2fae418af6d1e13a

In [54]:
colorado_filtrado = colorado.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [55]:
colorado_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 309964 entries, 0 to 309963
Data columns (total 8 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   user_id  309964 non-null  float64
 1   name     309964 non-null  object
 2   time     309964 non-null  int64
 3   rating   309964 non-null  int64
 4   text     193155 non-null  object
 5   pics     9759 non-null    object
 6   resp     39280 non-null   object
 7   gmap_id  309964 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 18.9+ MB

In [56]:
# Convertir la columna 'time' a datetime
colorado_filtrado['time'] = pd.to_datetime(colorado_filtrado['time'], unit='ms')

In [57]:
colorado_filtrado = colorado_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [58]:
colorado_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [59]:
colorado_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    295440
Name: count, dtype: int64

In [60]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
colorado_filtrado.to_csv(os.path.join(ruta_reviews, "06-colorado.csv"),index= False)

07-Connecticut

In [61]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-Connecticut')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            connecticut = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(connecticut)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id             name           time  rating  \
0        1.140765e+20    Jeff Mccomish  1612059976820       5
1        1.015203e+20      Outlaw PiRu  1544752859553       5
2        1.118002e+20   Hector Acevedo  1564367962353       5
3        1.122618e+20    Leah Williams  1610758109050       5
4        1.089888e+20  Nick “Big Nick”  1570061475449       5
...               ...              ...            ...     ...
2680102  1.130097e+20    Chris Skiadas  1377991651194       5
2680103  1.178020e+20   Katerine Perez  1593357995320       5
2680104  1.147630e+20   Malcolm Carter  1491327429617       5
2680105  1.169131e+20   Rich Margiloff  1596746704325       5
2680106  1.151195e+20     thanigai vel  1530495734974       5

                                                      text  pics  resp  \
0                        Great friendly independent packie  None  None
1        Great Atmosphere and Great Service. Fantastic ...  None  None
2        Nice neighborhood store with great sandwiches ...  None  None
3                                              Just trying  None  None
4                                                 Love it!  None  None
...                                                    ...   ...   ...
2680102                                          Excellent  None  None
2680103  (Translated by Google) I love Greek food, I th...  None  None
2680104                                               None  None  None
2680105                                               None  None  None
2680106                                               None  None  None

                                       gmap_id
0        0x89e64b04d274c9d9:0x84d833dcc10ae21d
1        0x89e64b04d274c9d9:0x84d833dcc10ae21d
2        0x89e64b04d274c9d9:0x84d833dcc10ae21d
3        0x89e64b04d274c9d9:0x84d833dcc10ae21d
4        0x89e64b04d274c9d9:0x84d833dcc10ae21d
...                                        ...
2680102  0x89c2a167d2ccb261:0x457ddb2fa3b7d4aa
2680103  0x89c2a167d2ccb261:0x457ddb2fa3b7d4aa
2680104  0x89c2a167d2ccb261:0x457ddb2fa3b7d4aa
2680105  0x89c2a167d2ccb261:0x457ddb2fa3b7d4aa
2680106  0x89c2a167d2ccb261:0x457ddb2fa3b7d4aa

[2680107 rows x 8 columns]

In [62]:
connecticut.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.140765e+20,Jeff Mccomish,1612059976820,5,Great friendly independent packie,None,None,0x89e64b04d274c9d9:0x84d833dcc10ae21d
1,1.015203e+20,Outlaw PiRu,1544752859553,5,Great Atmosphere and Great Service. Fantastic ...,None,None,0x89e64b04d274c9d9:0x84d833dcc10ae21d
2,1.118002e+20,Hector Acevedo,1564367962353,5,Nice neighborhood store with great sandwiches ...,None,None,0x89e64b04d274c9d9:0x84d833dcc10ae21d
3,1.122618e+20,Leah Williams,1610758109050,5,Just trying,None,None,0x89e64b04d274c9d9:0x84d833dcc10ae21d
4,1.089888e+20,Nick “Big Nick”,1570061475449,5,Love it!,None,None,0x89e64b04d274c9d9:0x84d833dcc10ae21d

In [63]:
connecticut_filtrado = connecticut.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [64]:
connecticut_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 143854 entries, 0 to 143853
Data columns (total 8 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   user_id  143854 non-null  float64
 1   name     143854 non-null  object
 2   time     143854 non-null  int64
 3   rating   143854 non-null  int64
 4   text     85246 non-null   object
 5   pics     4652 non-null    object
 6   resp     14952 non-null   object
 7   gmap_id  143854 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 8.8+ MB

In [65]:
# Convertir la columna 'time' a datetime
connecticut_filtrado['time'] = pd.to_datetime(connecticut_filtrado['time'], unit='ms')

In [66]:
connecticut_filtrado = connecticut_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [67]:
connecticut_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [68]:
connecticut_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    140371
Name: count, dtype: int64

In [69]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
connecticut_filtrado.to_csv(os.path.join(ruta_reviews, "07-connecticut.csv"),index= False)

08-Delaware

In [70]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-Delaware')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            delaware = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(delaware)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

             user_id             name           time  rating  \
0       1.137980e+20   Heather Carper  1507258129698       5
1       1.089116e+20   STACY CLAVETTE  1544802238870       5
2       1.101471e+20        Zion Hood  1559123933643       5
3       1.147143e+20      Diane Clark  1600736020990       5
4       1.089864e+20          Eddie S  1554953350224       4
...              ...              ...            ...     ...
905532  1.170500e+20    Brian Pennock  1581951149665       5
905533  1.050767e+20           Debbie  1582344632568       3
905534  1.071567e+20        Dariel B.  1524334929834       5
905535  1.152439e+20    Rick Caldeira  1570987733155       4
905536  1.174334e+20  Marsha williams  1536658160179       5

                                                     text  \
0       Lived here for 3 years and enjoyed it. Locatio...
1       Nice complex and awesome staff.  Maintenance i...
2       Good places for people to live my friend lives...
3                                           great layout.
4       Positives: Elevator, dog park and maintenance....
...                                                   ...
905532                                               None
905533                                               None
905534                                               None
905535                                               None
905536                                               None

                                                     pics  resp  \
0       [{'url': ['https://lh5.googleusercontent.com/p...  None
1                                                    None  None
2                                                    None  None
3                                                    None  None
4                                                    None  None
...                                                   ...   ...
905532                                               None  None
905533                                               None  None
905534                                               None  None
905535                                               None  None
905536                                               None  None

                                      gmap_id
0        0x89b8b77c34771c5f:0xf768433b3a39763
1        0x89b8b77c34771c5f:0xf768433b3a39763
2        0x89b8b77c34771c5f:0xf768433b3a39763
3        0x89b8b77c34771c5f:0xf768433b3a39763
4        0x89b8b77c34771c5f:0xf768433b3a39763
...                                       ...
905532  0x89c7013d91d9a571:0xe0df870dacaad95d
905533  0x89c7013d91d9a571:0xe0df870dacaad95d
905534  0x89c7013d91d9a571:0xe0df870dacaad95d
905535  0x89c7013d91d9a571:0xe0df870dacaad95d
905536  0x89c7013d91d9a571:0xe0df870dacaad95d

[905537 rows x 8 columns]

In [71]:
delaware.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.137980e+20,Heather Carper,1507258129698,5,Lived here for 3 years and enjoyed it. Locatio...,[{'url': ['https://lh5.googleusercontent.com/p...,None,0x89b8b77c34771c5f:0xf768433b3a39763
1,1.089116e+20,STACY CLAVETTE,1544802238870,5,Nice complex and awesome staff. Maintenance i...,None,None,0x89b8b77c34771c5f:0xf768433b3a39763
2,1.101471e+20,Zion Hood,1559123933643,5,Good places for people to live my friend lives...,None,None,0x89b8b77c34771c5f:0xf768433b3a39763
3,1.147143e+20,Diane Clark,1600736020990,5,great layout.,None,None,0x89b8b77c34771c5f:0xf768433b3a39763
4,1.089864e+20,Eddie S,1554953350224,4,"Positives: Elevator, dog park and maintenance....",None,None,0x89b8b77c34771c5f:0xf768433b3a39763

In [72]:
delaware_filtrado = delaware.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [73]:
delaware_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40337 entries, 0 to 40336
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   user_id  40337 non-null  float64
 1   name     40337 non-null  object
 2   time     40337 non-null  int64
 3   rating   40337 non-null  int64
 4   text     24480 non-null  object
 5   pics     1071 non-null   object
 6   resp     5388 non-null   object
 7   gmap_id  40337 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 2.5+ MB

In [74]:
# Convertir la columna 'time' a datetime
delaware_filtrado['time'] = pd.to_datetime(delaware_filtrado['time'], unit='ms')

In [75]:
delaware_filtrado = delaware_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [76]:
delaware_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [77]:
delaware_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    38826
Name: count, dtype: int64

In [78]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
delaware_filtrado.to_csv(os.path.join(ruta_reviews, "08-delaware.csv"),index= False)

9-District of Columbia

In [79]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-District_of_Columbia')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            district_of_columbia = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(district_of_columbia)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

             user_id                  name           time  rating  \
0       1.042564e+20             Petre Ene  1551027526726       4
1       1.086426e+20        Keshava Mysore  1510920735052       4
2       1.118429e+20               Carol G  1543249586598       2
3       1.102994e+20                    翟泉  1496597796978       4
4       1.164480e+20             Kitae Yim  1540701399450       1
...              ...                   ...            ...     ...
564778  1.006178e+20      Eastwood Cameron  1562283008242       5
564779  1.183827e+20                     V  1519337600592       5
564780  1.058797e+20  Francisco de Zavalía  1568771759420       5
564781  1.157440e+20          Charleen Lim  1522153548594       5
564782  1.038073e+20         Rodrigo Ferro  1559302218699       5

                                                     text  \
0       the food is really good, I had a great experie...
1       High prices for not so big portions! But I thi...
2       The gelato looked "old" and ended up having co...
3       (Translated by Google) The fast food restauran...
4       (Translated by Google) The food is barely edib...
...                                                   ...
564778                                               None
564779                                               None
564780                                               None
564781                                               None
564782                                               None

                                                     pics  resp  \
0       [{'url': ['https://lh5.googleusercontent.com/p...  None
1                                                    None  None
2                                                    None  None
3       [{'url': ['https://lh5.googleusercontent.com/p...  None
4                                                    None  None
...                                                   ...   ...
564778                                               None  None
564779                                               None  None
564780                                               None  None
564781                                               None  None
564782                                               None  None

                                      gmap_id
0         0x89b7b7851b06ef6b:0x5f356b1eb1da27
1         0x89b7b7851b06ef6b:0x5f356b1eb1da27
2         0x89b7b7851b06ef6b:0x5f356b1eb1da27
3         0x89b7b7851b06ef6b:0x5f356b1eb1da27
4         0x89b7b7851b06ef6b:0x5f356b1eb1da27
...                                       ...
564778  0x89b7b7c0896f06db:0xb1616aab085a8353
564779  0x89b7b7c0896f06db:0xb1616aab085a8353
564780  0x89b7b7c0896f06db:0xb1616aab085a8353
564781  0x89b7b7c0896f06db:0xb1616aab085a8353
564782  0x89b7b7c0896f06db:0xb1616aab085a8353

[564783 rows x 8 columns]

In [80]:
district_of_columbia.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.042564e+20,Petre Ene,1551027526726,4,"the food is really good, I had a great experie...",[{'url': ['https://lh5.googleusercontent.com/p...,None,0x89b7b7851b06ef6b:0x5f356b1eb1da27
1,1.086426e+20,Keshava Mysore,1510920735052,4,High prices for not so big portions! But I thi...,None,None,0x89b7b7851b06ef6b:0x5f356b1eb1da27
2,1.118429e+20,Carol G,1543249586598,2,"The gelato looked ""old"" and ended up having co...",None,None,0x89b7b7851b06ef6b:0x5f356b1eb1da27
3,1.102994e+20,翟泉,1496597796978,4,(Translated by Google) The fast food restauran...,[{'url': ['https://lh5.googleusercontent.com/p...,None,0x89b7b7851b06ef6b:0x5f356b1eb1da27
4,1.164480e+20,Kitae Yim,1540701399450,1,(Translated by Google) The food is barely edib...,None,None,0x89b7b7851b06ef6b:0x5f356b1eb1da27

In [81]:
district_of_columbia_filtrado = district_of_columbia.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [82]:
district_of_columbia_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19012 entries, 0 to 19011
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   user_id  19012 non-null  float64
 1   name     19012 non-null  object
 2   time     19012 non-null  int64
 3   rating   19012 non-null  int64
 4   text     10673 non-null  object
 5   pics     905 non-null    object
 6   resp     1420 non-null   object
 7   gmap_id  19012 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 1.2+ MB

In [83]:
# Convertir la columna 'time' a datetime
district_of_columbia_filtrado['time'] = pd.to_datetime(district_of_columbia_filtrado['time'], unit='ms')

In [84]:
district_of_columbia_filtrado = district_of_columbia_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [85]:
district_of_columbia_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [86]:
district_of_columbia_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    18628
Name: count, dtype: int64

In [87]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
district_of_columbia_filtrado.to_csv(os.path.join(ruta_reviews, "09-district_of_columbia.csv"),index= False)

10-Florida

In [88]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-Florida')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            florida = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(florida)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id               name           time  rating  \
0        1.014719e+20    Julie A. Gerber  1628003250740       1
1        1.154772e+20   Martin Sheffield  1595031217005       5
2        1.018050e+20       Brian Truett  1522924253567       5
3        1.063444e+20           Tina Sun  1467907819586       1
4        1.008751e+20       James Haynes  1480683415081       5
...               ...                ...            ...     ...
2849995  1.002877e+20      James Rudolph  1617305583696       5
2849996  1.140989e+20  Vincent Alexander  1581817848416       3
2849997  1.123448e+20         Brett Owen  1551240010030       5
2849998  1.054465e+20       ashly kindle  1521152570004       5
2849999  1.087433e+20       Jomarra Auge  1536462690218       5

                                                      text  pics  \
0        Update: Their “reply” to my review amounted to...  None
1        He's a knowledgeable doctor but the way he run...  None
2        Best doctor I've ever had, I never wait to be ...  None
3        I was told he is a good doctor. I was trying t...  None
4        Takes the time to actually get to know his pat...  None
...                                                    ...   ...
2849995                                               None  None
2849996                                               None  None
2849997                                               None  None
2849998                                               None  None
2849999                                               None  None

                                                      resp  \
0        {'time': 1627042799532, 'text': 'Thank you for...
1        {'time': 1582464056733, 'text': 'Thank you for...
2                                                     None
3                                                     None
4                                                     None
...                                                    ...
2849995      {'time': 1617561671234, 'text': 'Thank you!'}
2849996                                               None
2849997                                               None
2849998  {'time': 1516914199348, 'text': 'Thank you, As...
2849999  {'time': 1536463333138, 'text': 'Thank you, Mr...

                                       gmap_id
0        0x8893863ea87bd5dd:0x9383ebf973e74abb
1        0x8893863ea87bd5dd:0x9383ebf973e74abb
2        0x8893863ea87bd5dd:0x9383ebf973e74abb
3        0x8893863ea87bd5dd:0x9383ebf973e74abb
4        0x8893863ea87bd5dd:0x9383ebf973e74abb
...                                        ...
2849995  0x8890966585e36d3f:0x131d47c2c60a8d31
2849996  0x8890966585e36d3f:0x131d47c2c60a8d31
2849997  0x8890966585e36d3f:0x131d47c2c60a8d31
2849998  0x8890966585e36d3f:0x131d47c2c60a8d31
2849999  0x8890966585e36d3f:0x131d47c2c60a8d31

[2850000 rows x 8 columns]

In [89]:
florida.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.014719e+20,Julie A. Gerber,1628003250740,1,Update: Their “reply” to my review amounted to...,None,"{'time': 1627042799532, 'text': 'Thank you for...",0x8893863ea87bd5dd:0x9383ebf973e74abb
1,1.154772e+20,Martin Sheffield,1595031217005,5,He's a knowledgeable doctor but the way he run...,None,"{'time': 1582464056733, 'text': 'Thank you for...",0x8893863ea87bd5dd:0x9383ebf973e74abb
2,1.018050e+20,Brian Truett,1522924253567,5,"Best doctor I've ever had, I never wait to be ...",None,None,0x8893863ea87bd5dd:0x9383ebf973e74abb
3,1.063444e+20,Tina Sun,1467907819586,1,I was told he is a good doctor. I was trying t...,None,None,0x8893863ea87bd5dd:0x9383ebf973e74abb
4,1.008751e+20,James Haynes,1480683415081,5,Takes the time to actually get to know his pat...,None,None,0x8893863ea87bd5dd:0x9383ebf973e74abb

In [90]:
florida_filtrado = florida.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [91]:
florida_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1075239 entries, 0 to 1075238
Data columns (total 8 columns):
 #   Column   Non-Null Count    Dtype
---  ------   --------------    -----
 0   user_id  1075239 non-null  float64
 1   name     1075239 non-null  object
 2   time     1075239 non-null  int64
 3   rating   1075239 non-null  int64
 4   text     662488 non-null   object
 5   pics     44645 non-null    object
 6   resp     142657 non-null   object
 7   gmap_id  1075239 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 65.6+ MB

In [92]:
# Convertir la columna 'time' a datetime
florida_filtrado['time'] = pd.to_datetime(florida_filtrado['time'], unit='ms')

In [93]:
florida_filtrado = florida_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [94]:
florida_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [95]:
florida_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    1010524
Name: count, dtype: int64

In [96]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
florida_filtrado.to_csv(os.path.join(ruta_reviews, "10-florida.csv"),index= False)

11-Georgia

In [97]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-Georgia')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            georgia = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(georgia)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id             name           time  rating  \
0        1.042277e+20     Brent Powell  1599604812269       5
1        1.055723e+20      Evan Thomas  1502078169146       5
2        1.039554e+20     Caleb Howell  1502571430852       5
3        1.069746e+20  ashlee crawford  1494161075405       5
4        1.048457e+20          T Paulk  1495139229501       5
...               ...              ...            ...     ...
1949995  1.022998e+20        Storm Jae  1610798794955       3
1949996  1.066675e+20    Ellou Padilla  1588262167321       5
1949997  1.095975e+20  Janetha Grovner  1562797644124       5
1949998  1.061530e+20          Ally Be  1571763949440       1
1949999  1.050105e+20         Ms. Love  1572104389480       5

                                                      text  pics  resp  \
0        Great hometown folk. Rob takes good care of al...  None  None
1        Very friendly hometown pharmarcy. Always helpf...  None  None
2                                                     None  None  None
3                                                     None  None  None
4                                                     None  None  None
...                                                    ...   ...   ...
1949995  I've been going here for a few years now I lik...  None  None
1949996  Mom, sister and cousins come here regularly an...  None  None
1949997  Lee does a good job on my nails all of the nai...  None  None
1949998  A friend went and got there nails done on last...  None  None
1949999       Always nice and nails last... Very friendly.  None  None

                                       gmap_id
0        0x88f16e41928ff687:0x883dad4fd048e8f8
1        0x88f16e41928ff687:0x883dad4fd048e8f8
2        0x88f16e41928ff687:0x883dad4fd048e8f8
3        0x88f16e41928ff687:0x883dad4fd048e8f8
4        0x88f16e41928ff687:0x883dad4fd048e8f8
...                                        ...
1949995  0x88f4fbf399058fad:0xb3876db2aa013c99
1949996  0x88f4fbf399058fad:0xb3876db2aa013c99
1949997  0x88f4fbf399058fad:0xb3876db2aa013c99
1949998  0x88f4fbf399058fad:0xb3876db2aa013c99
1949999  0x88f4fbf399058fad:0xb3876db2aa013c99

[1950000 rows x 8 columns]

In [98]:
georgia.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.042277e+20,Brent Powell,1599604812269,5,Great hometown folk. Rob takes good care of al...,None,None,0x88f16e41928ff687:0x883dad4fd048e8f8
1,1.055723e+20,Evan Thomas,1502078169146,5,Very friendly hometown pharmarcy. Always helpf...,None,None,0x88f16e41928ff687:0x883dad4fd048e8f8
2,1.039554e+20,Caleb Howell,1502571430852,5,None,None,None,0x88f16e41928ff687:0x883dad4fd048e8f8
3,1.069746e+20,ashlee crawford,1494161075405,5,None,None,None,0x88f16e41928ff687:0x883dad4fd048e8f8
4,1.048457e+20,T Paulk,1495139229501,5,None,None,None,0x88f16e41928ff687:0x883dad4fd048e8f8

In [99]:
georgia_filtrado = georgia.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [100]:
georgia_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 573325 entries, 0 to 573324
Data columns (total 8 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   user_id  573325 non-null  float64
 1   name     573325 non-null  object
 2   time     573325 non-null  int64
 3   rating   573325 non-null  int64
 4   text     344004 non-null  object
 5   pics     18646 non-null   object
 6   resp     69001 non-null   object
 7   gmap_id  573325 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 35.0+ MB

In [101]:
# Convertir la columna 'time' a datetime
georgia_filtrado['time'] = pd.to_datetime(georgia_filtrado['time'], unit='ms')

In [102]:
georgia_filtrado = georgia_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [103]:
georgia_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [104]:
georgia_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    547911
Name: count, dtype: int64

In [105]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
georgia_filtrado.to_csv(os.path.join(ruta_reviews, "11-georgia.csv"),index= False)

12-Hawaii

In [106]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-Hawaii')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            hawaii = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(hawaii)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id               name           time  rating  \
0        1.139654e+20    manuel grimaldo  1591839903487       5
1        1.166558e+20       Enrique Lara  1568059018979       5
2        1.008341e+20  Gregory Donaldson  1594885588335       5
3        1.032072e+20        Brian Baker  1575951131613       5
4        1.085262e+20              Kam J  1573076723916       3
...               ...                ...            ...     ...
1504342  1.033485e+20         Mark Oliva  1617751352744       3
1504343  1.053264e+20   Christian Wilson  1606805473370       5
1504344  1.165970e+20  Rachel Adams-Beja  1539035406569       4
1504345  1.042476e+20     Anthony Gentry  1583811257757       3
1504346  1.134281e+20           T Joseph  1538161887741       4

                                                      text  \
0                                        Great new upgrade
1                                                     None
2                                                     None
3                                                     None
4                                                     None
...                                                    ...
1504342  I was expecting more for the price. The maki r...
1504343  Their poke is even better than Kahuku Superett...
1504344  Service was a bit slow but the food was very g...
1504345  Great ambiance for a 3rd floor restaurant. Bea...
1504346  The location is great and the prices are fair....

                                                      pics  resp  \
0                                                     None  None
1                                                     None  None
2                                                     None  None
3                                                     None  None
4                                                     None  None
...                                                    ...   ...
1504342                                               None  None
1504343                                               None  None
1504344  [{'url': ['https://lh5.googleusercontent.com/p...  None
1504345                                               None  None
1504346  [{'url': ['https://lh5.googleusercontent.com/p...  None

                                       gmap_id
0        0x7c00159b5b1b1d25:0x8d2d85d4a758290e
1        0x7c00159b5b1b1d25:0x8d2d85d4a758290e
2        0x7c00159b5b1b1d25:0x8d2d85d4a758290e
3        0x7c00159b5b1b1d25:0x8d2d85d4a758290e
4        0x7c00159b5b1b1d25:0x8d2d85d4a758290e
...                                        ...
1504342  0x7c006d9399edc08d:0x98c0e4f56f78af2b
1504343  0x7c006d9399edc08d:0x98c0e4f56f78af2b
1504344  0x7c006d9399edc08d:0x98c0e4f56f78af2b
1504345  0x7c006d9399edc08d:0x98c0e4f56f78af2b
1504346  0x7c006d9399edc08d:0x98c0e4f56f78af2b

[1504347 rows x 8 columns]

In [107]:
hawaii.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.139654e+20,manuel grimaldo,1591839903487,5,Great new upgrade,None,None,0x7c00159b5b1b1d25:0x8d2d85d4a758290e
1,1.166558e+20,Enrique Lara,1568059018979,5,None,None,None,0x7c00159b5b1b1d25:0x8d2d85d4a758290e
2,1.008341e+20,Gregory Donaldson,1594885588335,5,None,None,None,0x7c00159b5b1b1d25:0x8d2d85d4a758290e
3,1.032072e+20,Brian Baker,1575951131613,5,None,None,None,0x7c00159b5b1b1d25:0x8d2d85d4a758290e
4,1.085262e+20,Kam J,1573076723916,3,None,None,None,0x7c00159b5b1b1d25:0x8d2d85d4a758290e

In [108]:
hawaii_filtrado = hawaii.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [109]:
hawaii_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57160 entries, 0 to 57159
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   user_id  57160 non-null  float64
 1   name     57160 non-null  object
 2   time     57160 non-null  int64
 3   rating   57160 non-null  int64
 4   text     34495 non-null  object
 5   pics     5158 non-null   object
 6   resp     3118 non-null   object
 7   gmap_id  57160 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 3.5+ MB

In [110]:
# Convertir la columna 'time' a datetime
hawaii_filtrado['time'] = pd.to_datetime(hawaii_filtrado['time'], unit='ms')

In [111]:
hawaii_filtrado = hawaii_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [112]:
hawaii_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [113]:
hawaii_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    55285
Name: count, dtype: int64

In [114]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
hawaii_filtrado.to_csv(os.path.join(ruta_reviews, "12-hawaii.csv"),index= False)

13-Idaho

In [115]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-Idaho')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            idaho = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(idaho)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id                                     name           time  \
0        1.078421e+20                            Jason Johnson  1499810222323
1        1.035121e+20                            Michael Harry  1478021694645
2        1.102976e+20                            Jolene Vaughn  1533847989090
3        1.150576e+20                                Ben Voris  1563297497573
4        1.049081e+20  Sunshine Window Cleaning Inc. Greg Reid  1543076221896
...               ...                                      ...            ...
2085482  1.139755e+20                          Jessica Acevedo  1568997679845
2085483  1.131434e+20                              Tanya Prall  1575805837000
2085484  1.140981e+20                        Benjamin Phillips  1581290167904
2085485  1.139393e+20                          Carol Albertson  1574014581140
2085486  1.109332e+20                           Terrance Cagle  1543988411569

         rating                                               text  \
0             3  Nice place, but not enough dog friendly areas ...
1             5  Pheasant, ducks, geese, white tailed deer.\nSm...
2             3  We took some horses up to ride, but there real...
3             3  Crowded during pheasant season. If you’re not ...
4             4  Beautiful spot for a hike or some hunting. Be ...
...         ...                                                ...
2085482       5                                               None
2085483       2                                               None
2085484       3                                               None
2085485       5                                               None
2085486       4                                               None

                                                      pics  resp  \
0        [{'url': ['https://lh5.googleusercontent.com/p...  None
1                                                     None  None
2                                                     None  None
3                                                     None  None
4        [{'url': ['https://lh5.googleusercontent.com/p...  None
...                                                    ...   ...
2085482                                               None  None
2085483                                               None  None
2085484                                               None  None
2085485                                               None  None
2085486                                               None  None

                                       gmap_id
0        0x54af0dfadab474e1:0x3ae5c949132941d8
1        0x54af0dfadab474e1:0x3ae5c949132941d8
2        0x54af0dfadab474e1:0x3ae5c949132941d8
3        0x54af0dfadab474e1:0x3ae5c949132941d8
4        0x54af0dfadab474e1:0x3ae5c949132941d8
...                                        ...
2085482  0x5354434e88c30241:0x3da91c68addecfd8
2085483  0x5354434e88c30241:0x3da91c68addecfd8
2085484  0x5354434e88c30241:0x3da91c68addecfd8
2085485  0x5354434e88c30241:0x3da91c68addecfd8
2085486  0x5354434e88c30241:0x3da91c68addecfd8

[2085487 rows x 8 columns]

In [116]:
idaho.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.078421e+20,Jason Johnson,1499810222323,3,"Nice place, but not enough dog friendly areas ...",[{'url': ['https://lh5.googleusercontent.com/p...,None,0x54af0dfadab474e1:0x3ae5c949132941d8
1,1.035121e+20,Michael Harry,1478021694645,5,"Pheasant, ducks, geese, white tailed deer.\nSm...",None,None,0x54af0dfadab474e1:0x3ae5c949132941d8
2,1.102976e+20,Jolene Vaughn,1533847989090,3,"We took some horses up to ride, but there real...",None,None,0x54af0dfadab474e1:0x3ae5c949132941d8
3,1.150576e+20,Ben Voris,1563297497573,3,Crowded during pheasant season. If you’re not ...,None,None,0x54af0dfadab474e1:0x3ae5c949132941d8
4,1.049081e+20,Sunshine Window Cleaning Inc. Greg Reid,1543076221896,4,Beautiful spot for a hike or some hunting. Be ...,[{'url': ['https://lh5.googleusercontent.com/p...,None,0x54af0dfadab474e1:0x3ae5c949132941d8

In [117]:
idaho_filtrado = idaho.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [118]:
idaho_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69458 entries, 0 to 69457
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   user_id  69458 non-null  float64
 1   name     69458 non-null  object
 2   time     69458 non-null  int64
 3   rating   69458 non-null  int64
 4   text     42386 non-null  object
 5   pics     1818 non-null   object
 6   resp     10415 non-null  object
 7   gmap_id  69458 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 4.2+ MB

In [119]:
# Convertir la columna 'time' a datetime
idaho_filtrado['time'] = pd.to_datetime(idaho_filtrado['time'], unit='ms')

In [120]:
idaho_filtrado = idaho_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [121]:
idaho_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [122]:
idaho_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    66690
Name: count, dtype: int64

In [123]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
idaho_filtrado.to_csv(os.path.join(ruta_reviews, "13-idaho.csv"),index= False)

14-Illinois

In [124]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-Illinois')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            illinois = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(illinois)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id             name           time  rating  \
0        1.094426e+20    Jim LeBurkien  1571842572977       5
1        1.009245e+20     Steve Muscat  1561679275695       5
2        1.008140e+20  Fletcher Oliver  1572719516502       5
3        1.101685e+20    Daniel Chavez  1572641473424       5
4        1.089906e+20  David Ferdinand  1561483351910       4
...               ...              ...            ...     ...
2099995  1.055523e+20      Cindy Neath  1546825827465       5
2099996  1.020356e+20      David Mauer  1541157502008       5
2099997  1.002122e+20   Bloodkisses333  1517804540149       5
2099998  1.094001e+20  Kevin Sircloumb  1553131495401       4
2099999  1.161752e+20    Phillip Feltz  1499839359853       5

                                                      text  pics  resp  \
0        Great selection of used and collectible toys. ...  None  None
1                                 Great visit as usual. 👍😊  None  None
2                                                     None  None  None
3                                                     None  None  None
4                                                     None  None  None
...                                                    ...   ...   ...
2099995                                          Like them  None  None
2099996                                          Loved It!  None  None
2099997                                 Local and awesome!  None  None
2099998                  Very convenient to get in and out  None  None
2099999               The only place we shop for our pets.  None  None

                                       gmap_id
0        0x880f0f1b32155555:0x8347e0c971acb955
1        0x880f0f1b32155555:0x8347e0c971acb955
2        0x880f0f1b32155555:0x8347e0c971acb955
3        0x880f0f1b32155555:0x8347e0c971acb955
4        0x880f0f1b32155555:0x8347e0c971acb955
...                                        ...
2099995  0x8808bbdd68f8761b:0x8c518beb56b4f3ca
2099996  0x8808bbdd68f8761b:0x8c518beb56b4f3ca
2099997  0x8808bbdd68f8761b:0x8c518beb56b4f3ca
2099998  0x8808bbdd68f8761b:0x8c518beb56b4f3ca
2099999  0x8808bbdd68f8761b:0x8c518beb56b4f3ca

[2100000 rows x 8 columns]

In [125]:
illinois.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.094426e+20,Jim LeBurkien,1571842572977,5,Great selection of used and collectible toys. ...,None,None,0x880f0f1b32155555:0x8347e0c971acb955
1,1.009245e+20,Steve Muscat,1561679275695,5,Great visit as usual. 👍😊,None,None,0x880f0f1b32155555:0x8347e0c971acb955
2,1.008140e+20,Fletcher Oliver,1572719516502,5,None,None,None,0x880f0f1b32155555:0x8347e0c971acb955
3,1.101685e+20,Daniel Chavez,1572641473424,5,None,None,None,0x880f0f1b32155555:0x8347e0c971acb955
4,1.089906e+20,David Ferdinand,1561483351910,4,None,None,None,0x880f0f1b32155555:0x8347e0c971acb955

In [126]:
illinois_filtrado = illinois.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [127]:
illinois_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545802 entries, 0 to 545801
Data columns (total 8 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   user_id  545802 non-null  float64
 1   name     545802 non-null  object
 2   time     545802 non-null  int64
 3   rating   545802 non-null  int64
 4   text     318018 non-null  object
 5   pics     18556 non-null   object
 6   resp     51415 non-null   object
 7   gmap_id  545802 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 33.3+ MB

In [128]:
# Convertir la columna 'time' a datetime
illinois_filtrado['time'] = pd.to_datetime(illinois_filtrado['time'], unit='ms')

In [129]:
illinois_filtrado = illinois_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [130]:
illinois_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [131]:
illinois_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    526971
Name: count, dtype: int64

In [132]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
illinois_filtrado.to_csv(os.path.join(ruta_reviews, "14-illinois.csv"),index= False)

15-Indiana

In [133]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-Indiana')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            indiana = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(indiana)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id               name           time  rating  \
0        1.114237e+20     Larry Sandefur  1615400502414       5
1        1.135966e+20         John Soard  1597280425295       5
2        1.008217e+20    Michael Johnson  1596678908723       5
3        1.060630e+20      Lauren Moretz  1606588867988       1
4        1.072273e+20      Tracy Workman  1606677082659       5
...               ...                ...            ...     ...
2249995  1.081862e+20  Emily Antoszewski  1533346060190       4
2249996  1.001759e+20       Amy Lawrence  1532489392113       5
2249997  1.137970e+20        Brian James  1517152510778       5
2249998  1.013957e+20      A Google User  1569530918179       5
2249999  1.134737e+20       Brenda Sizer  1513879940509       5

                                                      text  pics  \
0        Majestic security was the best job I ever had ...  None
1        I have used this company for a number of years...  None
2        I am an employee with Majestic Security, and h...  None
3        My husband has worked for this company for a f...  None
4        I'm 55 and have been here with Magestic over 6...  None
...                                                    ...   ...
2249995                                               None  None
2249996                                               None  None
2249997                                               None  None
2249998                                               None  None
2249999                                               None  None

                                                      resp  \
0        {'time': 1627580537714, 'text': 'Thanks for th...
1        {'time': 1606930574545, 'text': 'Thanks John, ...
2        {'time': 1606930806337, 'text': 'Thanks Mike f...
3        {'time': 1606930153562, 'text': 'in 33 years, ...
4        {'time': 1606930223376, 'text': 'Thank You Tra...
...                                                    ...
2249995                                               None
2249996                                               None
2249997                                               None
2249998                                               None
2249999                                               None

                                       gmap_id
0        0x8816c4b2fb8fb6a1:0x80451636e10ca83f
1        0x8816c4b2fb8fb6a1:0x80451636e10ca83f
2        0x8816c4b2fb8fb6a1:0x80451636e10ca83f
3        0x8816c4b2fb8fb6a1:0x80451636e10ca83f
4        0x8816c4b2fb8fb6a1:0x80451636e10ca83f
...                                        ...
2249995  0x881112883a1b1115:0x78ff1f0e8dfe0257
2249996  0x881112883a1b1115:0x78ff1f0e8dfe0257
2249997  0x881112883a1b1115:0x78ff1f0e8dfe0257
2249998  0x881112883a1b1115:0x78ff1f0e8dfe0257
2249999  0x881112883a1b1115:0x78ff1f0e8dfe0257

[2250000 rows x 8 columns]

In [134]:
indiana.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.114237e+20,Larry Sandefur,1615400502414,5,Majestic security was the best job I ever had ...,None,"{'time': 1627580537714, 'text': 'Thanks for th...",0x8816c4b2fb8fb6a1:0x80451636e10ca83f
1,1.135966e+20,John Soard,1597280425295,5,I have used this company for a number of years...,None,"{'time': 1606930574545, 'text': 'Thanks John, ...",0x8816c4b2fb8fb6a1:0x80451636e10ca83f
2,1.008217e+20,Michael Johnson,1596678908723,5,"I am an employee with Majestic Security, and h...",None,"{'time': 1606930806337, 'text': 'Thanks Mike f...",0x8816c4b2fb8fb6a1:0x80451636e10ca83f
3,1.060630e+20,Lauren Moretz,1606588867988,1,My husband has worked for this company for a f...,None,"{'time': 1606930153562, 'text': 'in 33 years, ...",0x8816c4b2fb8fb6a1:0x80451636e10ca83f
4,1.072273e+20,Tracy Workman,1606677082659,5,I'm 55 and have been here with Magestic over 6...,None,"{'time': 1606930223376, 'text': 'Thank You Tra...",0x8816c4b2fb8fb6a1:0x80451636e10ca83f

In [135]:
indiana_filtrado = indiana.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [136]:
indiana_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 332283 entries, 0 to 332282
Data columns (total 8 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   user_id  332283 non-null  float64
 1   name     332283 non-null  object
 2   time     332283 non-null  int64
 3   rating   332283 non-null  int64
 4   text     192132 non-null  object
 5   pics     7782 non-null    object
 6   resp     37991 non-null   object
 7   gmap_id  332283 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 20.3+ MB

In [137]:
# Convertir la columna 'time' a datetime
indiana_filtrado['time'] = pd.to_datetime(indiana_filtrado['time'], unit='ms')

In [138]:
indiana_filtrado = indiana_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [139]:
indiana_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [140]:
indiana_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    318726
Name: count, dtype: int64

In [141]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
indiana_filtrado.to_csv(os.path.join(ruta_reviews, "15-indiana.csv"),index= False)

16-Iowa

In [142]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-Iowa')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            iowa = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(iowa)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id                   name           time  rating  \
0        1.154997e+20        Nicole Williams  1528935574441       5
1        1.100727e+20              Dmitriy N  1575832576112       5
2        1.170215e+20            Sue Dickman  1465139905809       5
3        1.090032e+20          Ashley Nguyen  1565271263810       5
4        1.132786e+20           Candy Hester  1450564402784       5
...               ...                    ...            ...     ...
2677679  1.183260e+20         Jason Mrachina  1368211822370       5
2677680  1.069845e+20              Amy Meyer  1518834397012       4
2677681  1.181300e+20        Jackie Horsfall  1529615684500       5
2677682  1.061717e+20  Cheryl Laird-Humphrey  1511582300144       5
2677683  1.143576e+20  Just_Your_Local Guard  1555721001405       5

                                                      text  pics  \
0        I have found my new favorite nail shop. I love...  None
1        This place is awesome. Got my pedicure there a...  None
2        I love going to Polished Nails. Everyone is pr...  None
3                        Nice place to get a complete set.  None
4        Great manicure from someone who really cares f...  None
...                                                    ...   ...
2677679  Good food, simple but clean atmosphere.   Serv...  None
2677680               Fabulous food, slower than I prefer.  None
2677681                     Best greek food in Des Moines!  None
2677682    Yes! MeMe made it such a  memorable experience!  None
2677683                               Was really worth it.  None

                                                      resp  \
0                {'time': 1528950923185, 'text': 'Thanks'}
1        {'time': 1576094549338, 'text': 'Thanks , Dmit...
2                                                     None
3                {'time': 1565752414209, 'text': 'Thanks'}
4                                                     None
...                                                    ...
2677679                                               None
2677680                                               None
2677681                                               None
2677682                                               None
2677683                                               None

                                       gmap_id
0        0x87ec238afdd8837b:0x2f43f2b12142bff5
1        0x87ec238afdd8837b:0x2f43f2b12142bff5
2        0x87ec238afdd8837b:0x2f43f2b12142bff5
3        0x87ec238afdd8837b:0x2f43f2b12142bff5
4        0x87ec238afdd8837b:0x2f43f2b12142bff5
...                                        ...
2677679  0x87ee99b1c27f21df:0xdabedf4b380932ac
2677680  0x87ee99b1c27f21df:0xdabedf4b380932ac
2677681  0x87ee99b1c27f21df:0xdabedf4b380932ac
2677682  0x87ee99b1c27f21df:0xdabedf4b380932ac
2677683  0x87ee99b1c27f21df:0xdabedf4b380932ac

[2677684 rows x 8 columns]

In [143]:
iowa.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.154997e+20,Nicole Williams,1528935574441,5,I have found my new favorite nail shop. I love...,None,"{'time': 1528950923185, 'text': 'Thanks'}",0x87ec238afdd8837b:0x2f43f2b12142bff5
1,1.100727e+20,Dmitriy N,1575832576112,5,This place is awesome. Got my pedicure there a...,None,"{'time': 1576094549338, 'text': 'Thanks , Dmit...",0x87ec238afdd8837b:0x2f43f2b12142bff5
2,1.170215e+20,Sue Dickman,1465139905809,5,I love going to Polished Nails. Everyone is pr...,None,None,0x87ec238afdd8837b:0x2f43f2b12142bff5
3,1.090032e+20,Ashley Nguyen,1565271263810,5,Nice place to get a complete set.,None,"{'time': 1565752414209, 'text': 'Thanks'}",0x87ec238afdd8837b:0x2f43f2b12142bff5
4,1.132786e+20,Candy Hester,1450564402784,5,Great manicure from someone who really cares f...,None,None,0x87ec238afdd8837b:0x2f43f2b12142bff5

In [144]:
iowa_filtrado = iowa.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [145]:
iowa_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 141356 entries, 0 to 141355
Data columns (total 8 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   user_id  141356 non-null  float64
 1   name     141356 non-null  object
 2   time     141356 non-null  int64
 3   rating   141356 non-null  int64
 4   text     77582 non-null   object
 5   pics     2855 non-null    object
 6   resp     12359 non-null   object
 7   gmap_id  141356 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 8.6+ MB

In [146]:
# Convertir la columna 'time' a datetime
iowa_filtrado['time'] = pd.to_datetime(iowa_filtrado['time'], unit='ms')

In [147]:
iowa_filtrado = iowa_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [148]:
iowa_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [149]:
iowa_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    137567
Name: count, dtype: int64

In [150]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
iowa_filtrado.to_csv(os.path.join(ruta_reviews, "16-iowa.csv"),index= False)

17-Kansas

In [151]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-Kansas')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            kansas = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(kansas)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id                 name           time  rating  \
0        1.101749e+20      Hannah Johnston  1603469475914       4
1        1.094691e+20    Flint Blankenship  1628280826510       4
2        1.011328e+20        Sheryl Fields  1511648800146       2
3        1.145734e+20         Robert Gragg  1572660533736       4
4        1.172689e+20             Jan Swan  1603471293093       4
...               ...                  ...            ...     ...
1949995  1.021566e+20         katy leonard  1600794553545       5
1949996  1.171283e+20       Lane Trautwein  1557333898240       5
1949997  1.088911e+20  cristina magallanes  1577669812582       4
1949998  1.132996e+20       Patricia Lopez  1571321589979       4
1949999  1.140172e+20            Beth Koon  1554217033806       3

                                                      text  pics  \
0        Really cute store. All the staff are lovely. T...  None
1             Well......  The place is a 5-Star..... BUT..  None
2        Normally we really like stopping in and shoppi...  None
3        Nice selection of antiques collectables and ho...  None
4                                               Nice stuff  None
...                                                    ...   ...
1949995  Loved this place!\nAre they opening somewhere ...  None
1949996  Great for a cheap meal for a family, nothing w...  None
1949997  Pizza was great! A classic place to visit.  Ye...  None
1949998  Pizzas are freshly made.... I love that every ...  None
1949999  This is a super cheap pizza buffet. Kids eat f...  None

                                                      resp  \
0                                                     None
1                                                     None
2        {'time': 1511695775965, 'text': 'So sorry to d...
3        {'time': 1572693100906, 'text': 'Thank you for...
4                                                     None
...                                                    ...
1949995                                               None
1949996                                               None
1949997                                               None
1949998  {'time': 1571400129930, 'text': 'Happy to hear...
1949999                                               None

                                       gmap_id
0        0x87bf03987b89d0c3:0x9b3d137e7bfc045a
1        0x87bf03987b89d0c3:0x9b3d137e7bfc045a
2        0x87bf03987b89d0c3:0x9b3d137e7bfc045a
3        0x87bf03987b89d0c3:0x9b3d137e7bfc045a
4        0x87bf03987b89d0c3:0x9b3d137e7bfc045a
...                                        ...
1949995  0x87c0ecb5c604d395:0x21c383cffaf6e12a
1949996  0x87c0ecb5c604d395:0x21c383cffaf6e12a
1949997  0x87c0ecb5c604d395:0x21c383cffaf6e12a
1949998  0x87c0ecb5c604d395:0x21c383cffaf6e12a
1949999  0x87c0ecb5c604d395:0x21c383cffaf6e12a

[1950000 rows x 8 columns]

In [152]:
kansas.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.101749e+20,Hannah Johnston,1603469475914,4,Really cute store. All the staff are lovely. T...,None,None,0x87bf03987b89d0c3:0x9b3d137e7bfc045a
1,1.094691e+20,Flint Blankenship,1628280826510,4,Well...... The place is a 5-Star..... BUT..,None,None,0x87bf03987b89d0c3:0x9b3d137e7bfc045a
2,1.011328e+20,Sheryl Fields,1511648800146,2,Normally we really like stopping in and shoppi...,None,"{'time': 1511695775965, 'text': 'So sorry to d...",0x87bf03987b89d0c3:0x9b3d137e7bfc045a
3,1.145734e+20,Robert Gragg,1572660533736,4,Nice selection of antiques collectables and ho...,None,"{'time': 1572693100906, 'text': 'Thank you for...",0x87bf03987b89d0c3:0x9b3d137e7bfc045a
4,1.172689e+20,Jan Swan,1603471293093,4,Nice stuff,None,None,0x87bf03987b89d0c3:0x9b3d137e7bfc045a

In [153]:
kansas_filtrado = kansas.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [154]:
kansas_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119919 entries, 0 to 119918
Data columns (total 8 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   user_id  119919 non-null  float64
 1   name     119919 non-null  object
 2   time     119919 non-null  int64
 3   rating   119919 non-null  int64
 4   text     69575 non-null   object
 5   pics     3142 non-null    object
 6   resp     10346 non-null   object
 7   gmap_id  119919 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 7.3+ MB

In [155]:
# Convertir la columna 'time' a datetime
kansas_filtrado['time'] = pd.to_datetime(kansas_filtrado['time'], unit='ms')

In [156]:
kansas_filtrado = kansas_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [157]:
kansas_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [158]:
kansas_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    115476
Name: count, dtype: int64

In [159]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
kansas_filtrado.to_csv(os.path.join(ruta_reviews, "17-kansas.csv"),index= False)

18-Kentucky

In [160]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-Kentucky')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            kentucky = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(kentucky)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id             name           time  rating  \
0        1.176319e+20  Fatcat Paulanne  1612545195499       5
1        1.089865e+20     Scott Vatter  1531435973696       4
2        1.087629e+20       Cait Lewis  1505925988144       2
3        1.045360e+20    Kristen Casey  1558918298929       5
4        1.089805e+20     Cheryl Basil  1507352415093       5
...               ...              ...            ...     ...
1649995  1.041252e+20     Ashley Perry  1580785119082       3
1649996  1.180868e+20     Jill Pelfrey  1610440364047       4
1649997  1.085603e+20    Jacob Stamper  1536674838045       3
1649998  1.158957e+20        Eric Hall  1555589999236       4
1649999  1.127605e+20    Renee Bayless  1536762786333       5

                                                      text  pics  resp  \
0        Very professional.  Returned phone calls promp...  None  None
1                                             Very helpful  None  None
2                                                     None  None  None
3                                                     None  None  None
4                                                     None  None  None
...                                                    ...   ...   ...
1649995                                               None  None  None
1649996                                               None  None  None
1649997                                               None  None  None
1649998                                               None  None  None
1649999                                               None  None  None

                                       gmap_id
0        0x886851e247062e25:0xd455b2d55eda354a
1        0x886851e247062e25:0xd455b2d55eda354a
2        0x886851e247062e25:0xd455b2d55eda354a
3        0x886851e247062e25:0xd455b2d55eda354a
4        0x886851e247062e25:0xd455b2d55eda354a
...                                        ...
1649995  0x8846769f6fc49cf1:0xf177079a1176d7c3
1649996  0x8846769f6fc49cf1:0xf177079a1176d7c3
1649997  0x8846769f6fc49cf1:0xf177079a1176d7c3
1649998  0x8846769f6fc49cf1:0xf177079a1176d7c3
1649999  0x8846769f6fc49cf1:0xf177079a1176d7c3

[1650000 rows x 8 columns]

In [161]:
kentucky.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.176319e+20,Fatcat Paulanne,1612545195499,5,Very professional. Returned phone calls promp...,None,None,0x886851e247062e25:0xd455b2d55eda354a
1,1.089865e+20,Scott Vatter,1531435973696,4,Very helpful,None,None,0x886851e247062e25:0xd455b2d55eda354a
2,1.087629e+20,Cait Lewis,1505925988144,2,None,None,None,0x886851e247062e25:0xd455b2d55eda354a
3,1.045360e+20,Kristen Casey,1558918298929,5,None,None,None,0x886851e247062e25:0xd455b2d55eda354a
4,1.089805e+20,Cheryl Basil,1507352415093,5,None,None,None,0x886851e247062e25:0xd455b2d55eda354a

In [162]:
kentucky_filtrado = kentucky.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [163]:
kentucky_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 154370 entries, 0 to 154369
Data columns (total 8 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   user_id  154370 non-null  float64
 1   name     154370 non-null  object
 2   time     154370 non-null  int64
 3   rating   154370 non-null  int64
 4   text     89391 non-null   object
 5   pics     3571 non-null    object
 6   resp     18610 non-null   object
 7   gmap_id  154370 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 9.4+ MB

In [164]:
# Convertir la columna 'time' a datetime
kentucky_filtrado['time'] = pd.to_datetime(kentucky_filtrado['time'], unit='ms')

In [165]:
kentucky_filtrado = kentucky_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [166]:
kentucky_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [167]:
kentucky_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    149179
Name: count, dtype: int64

In [168]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
kentucky_filtrado.to_csv(os.path.join(ruta_reviews, "18-kentucky.csv"),index= False)

19-Louisiana

In [169]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-Louisiana')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            louisiana = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(louisiana)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id                  name           time  rating  \
0        1.101177e+20         Taria Jackson  1583803141563       5
1        1.044371e+20          Jodi Kociaba  1603610106892       5
2        1.089910e+20             Beejal S.  1527773942699       5
3        1.075095e+20           Lovely 2021  1578657721674       5
4        1.144982e+20   Technician Ash Mohd  1580787625014       5
...               ...                   ...            ...     ...
1499995  1.148989e+20            Jared Ware  1562025130824       5
1499996  1.002717e+20  Michelle Scarborough  1573820100467       5
1499997  1.003407e+20         Vasily Bender  1470802132373       3
1499998  1.032592e+20      Judith Angelette  1503067322006       1
1499999  1.082137e+20        Violet Flowers  1584369241149       5

                                                      text  pics  \
0        Reasonably priced, process was easy and fast! ...  None
1            Was quick, easy and fun to use the key kiosk.  None
2        Easy to use, fairly fast.  $3.49 for copy of b...  None
3                                                     None  None
4                                                     None  None
...                                                    ...   ...
1499995                              It's all soooooo good  None
1499996                                Our favorite buffet  None
1499997       Great food selection, customer service is OK  None
1499998  Is too expensive for the food that they offer ...  None
1499999                                I loved the food...  None

                                                      resp  \
0        {'time': 1583842250926, 'text': 'Taria , thank...
1        {'time': 1603631822084, 'text': 'Hello Steve, ...
2                                                     None
3        {'time': 1578949813503, 'text': 'Hi Lovely, th...
4        {'time': 1580821552374, 'text': 'Ashraf  , tha...
...                                                    ...
1499995                                               None
1499996                                               None
1499997                                               None
1499998                                               None
1499999                                               None

                                       gmap_id
0        0x86312d61f5ac28b5:0x5e6c55690b65096a
1        0x86312d61f5ac28b5:0x5e6c55690b65096a
2        0x86312d61f5ac28b5:0x5e6c55690b65096a
3        0x86312d61f5ac28b5:0x5e6c55690b65096a
4        0x86312d61f5ac28b5:0x5e6c55690b65096a
...                                        ...
1499995  0x86213de9159f74a3:0xfcb835497a40af5e
1499996  0x86213de9159f74a3:0xfcb835497a40af5e
1499997  0x86213de9159f74a3:0xfcb835497a40af5e
1499998  0x86213de9159f74a3:0xfcb835497a40af5e
1499999  0x86213de9159f74a3:0xfcb835497a40af5e

[1500000 rows x 8 columns]

In [170]:
louisiana.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.101177e+20,Taria Jackson,1583803141563,5,"Reasonably priced, process was easy and fast! ...",None,"{'time': 1583842250926, 'text': 'Taria , thank...",0x86312d61f5ac28b5:0x5e6c55690b65096a
1,1.044371e+20,Jodi Kociaba,1603610106892,5,"Was quick, easy and fun to use the key kiosk.",None,"{'time': 1603631822084, 'text': 'Hello Steve, ...",0x86312d61f5ac28b5:0x5e6c55690b65096a
2,1.089910e+20,Beejal S.,1527773942699,5,"Easy to use, fairly fast. $3.49 for copy of b...",None,None,0x86312d61f5ac28b5:0x5e6c55690b65096a
3,1.075095e+20,Lovely 2021,1578657721674,5,None,None,"{'time': 1578949813503, 'text': 'Hi Lovely, th...",0x86312d61f5ac28b5:0x5e6c55690b65096a
4,1.144982e+20,Technician Ash Mohd,1580787625014,5,None,None,"{'time': 1580821552374, 'text': 'Ashraf , tha...",0x86312d61f5ac28b5:0x5e6c55690b65096a

In [171]:
louisiana_filtrado = louisiana.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [172]:
louisiana_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 174429 entries, 0 to 174428
Data columns (total 8 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   user_id  174429 non-null  float64
 1   name     174429 non-null  object
 2   time     174429 non-null  int64
 3   rating   174429 non-null  int64
 4   text     98601 non-null   object
 5   pics     5954 non-null    object
 6   resp     19183 non-null   object
 7   gmap_id  174429 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 10.6+ MB

In [173]:
# Convertir la columna 'time' a datetime
louisiana_filtrado['time'] = pd.to_datetime(louisiana_filtrado['time'], unit='ms')

In [174]:
louisiana_filtrado = louisiana_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [175]:
louisiana_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [176]:
louisiana_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    169010
Name: count, dtype: int64

In [177]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
louisiana_filtrado.to_csv(os.path.join(ruta_reviews, "19-louisiana.csv"),index= False)

20-Maine

In [178]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-Maine')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            maine = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(maine)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id                     name           time  rating  \
0        1.134399e+20            Steve Holland  1528823744253       4
1        1.074215e+20             Matthew Hall  1500129522343       2
2        1.038352e+20             Laura Oliver  1534025979137       1
3        1.134932e+20                Phil Rose  1495584198169       2
4        1.089903e+20                 Sam I Am  1436912786006       4
...               ...                      ...            ...     ...
1123876  1.149096e+20             Jon McDaniel  1556273703057       5
1123877  1.111961e+20           charlie morrow  1611012905776       5
1123878  1.174246e+20       P.J. Ewen-Pospisil  1577910214339       5
1123879  1.032131e+20           David mehrtens  1535157600402       5
1123880  1.100103e+20  Rachel F. R. de Almeida  1562849835831       5

                                                      text  pics  resp  \
0        My friend and I played here today. played all ...  None  None
1        It literally pains me to give such a low revie...  None  None
2        DO NOT GO HERE!!! Seriously!! This was the mos...  None  None
3        Not sure what happened but it's not what it us...  None  None
4        Very nice course it's awesome that 27 holes al...  None  None
...                                                    ...   ...   ...
1123876                                               None  None  None
1123877                                               None  None  None
1123878                                               None  None  None
1123879                                               None  None  None
1123880                                               None  None  None

                                       gmap_id
0        0x4cb27993a61ab3e1:0xa6c6508fe8842ff0
1        0x4cb27993a61ab3e1:0xa6c6508fe8842ff0
2        0x4cb27993a61ab3e1:0xa6c6508fe8842ff0
3        0x4cb27993a61ab3e1:0xa6c6508fe8842ff0
4        0x4cb27993a61ab3e1:0xa6c6508fe8842ff0
...                                        ...
1123876  0x89e2b8d86ba1f799:0xee289941ea19d34e
1123877  0x89e2b8d86ba1f799:0xee289941ea19d34e
1123878  0x89e2b8d86ba1f799:0xee289941ea19d34e
1123879  0x89e2b8d86ba1f799:0xee289941ea19d34e
1123880  0x89e2b8d86ba1f799:0xee289941ea19d34e

[1123881 rows x 8 columns]

In [179]:
maine.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.134399e+20,Steve Holland,1528823744253,4,My friend and I played here today. played all ...,None,None,0x4cb27993a61ab3e1:0xa6c6508fe8842ff0
1,1.074215e+20,Matthew Hall,1500129522343,2,It literally pains me to give such a low revie...,None,None,0x4cb27993a61ab3e1:0xa6c6508fe8842ff0
2,1.038352e+20,Laura Oliver,1534025979137,1,DO NOT GO HERE!!! Seriously!! This was the mos...,None,None,0x4cb27993a61ab3e1:0xa6c6508fe8842ff0
3,1.134932e+20,Phil Rose,1495584198169,2,Not sure what happened but it's not what it us...,None,None,0x4cb27993a61ab3e1:0xa6c6508fe8842ff0
4,1.089903e+20,Sam I Am,1436912786006,4,Very nice course it's awesome that 27 holes al...,None,None,0x4cb27993a61ab3e1:0xa6c6508fe8842ff0

In [180]:
maine_filtrado = maine.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [181]:
maine_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51578 entries, 0 to 51577
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   user_id  51578 non-null  float64
 1   name     51578 non-null  object
 2   time     51578 non-null  int64
 3   rating   51578 non-null  int64
 4   text     31086 non-null  object
 5   pics     1423 non-null   object
 6   resp     5797 non-null   object
 7   gmap_id  51578 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 3.1+ MB

In [182]:
# Convertir la columna 'time' a datetime
maine_filtrado['time'] = pd.to_datetime(maine_filtrado['time'], unit='ms')

In [183]:
maine_filtrado = maine_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [184]:
maine_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [185]:
maine_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    49995
Name: count, dtype: int64

In [186]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
maine_filtrado.to_csv(os.path.join(ruta_reviews, "20-maine.csv"),index= False)

21-Maryland

In [187]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-Maryland')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            maryland = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(maryland)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id              name           time  rating  \
0        1.162101e+20           Brian A  1528719383671       5
1        1.089905e+20          Marsha J  1556106162554       5
2        1.179088e+20              Noel  1531995775977       5
3        1.174477e+20  Sheila Dickerson  1533222175613       1
4        1.145177e+20    Carlos Alvarez  1489337608868       5
...               ...               ...            ...     ...
2399995  1.139092e+20         Kelly Kil  1595163517690       5
2399996  1.031738e+20         anna chen  1589518192012       5
2399997  1.006875e+20     Kara Siegmund  1614520621252       4
2399998  1.029245e+20     kris sandholm  1603377725664       5
2399999  1.110699e+20     William Utasi  1579719487785       5

                                                      text  \
0        Every time I have been to this place I am in a...
1        Good pharmacy and fast service, majority of th...
2                                    Awesome service here!
3                        I never received my prescription.
4                                                very fast
...                                                    ...
2399995                                               None
2399996                                               None
2399997                                               None
2399998                                               None
2399999                                               None

                                                      pics  \
0                                                     None
1                                                     None
2                                                     None
3                                                     None
4                                                     None
...                                                    ...
2399995  [{'url': ['https://lh5.googleusercontent.com/p...
2399996  [{'url': ['https://lh5.googleusercontent.com/p...
2399997                                               None
2399998                                               None
2399999                                               None

                                                      resp  \
0                                                     None
1        {'time': 1556236566548, 'text': 'Hi Marsha, th...
2                                                     None
3        {'time': 1533224288512, 'text': 'Can you pleas...
4                                                     None
...                                                    ...
2399995                                               None
2399996                                               None
2399997                                               None
2399998                                               None
2399999                                               None

                                       gmap_id
0        0x89b7a76096bdad0b:0x66e4be0af3dc1720
1        0x89b7a76096bdad0b:0x66e4be0af3dc1720
2        0x89b7a76096bdad0b:0x66e4be0af3dc1720
3        0x89b7a76096bdad0b:0x66e4be0af3dc1720
4        0x89b7a76096bdad0b:0x66e4be0af3dc1720
...                                        ...
2399995   0x89c80335ceb1a2bf:0x52b5e5a15a58daf
2399996   0x89c80335ceb1a2bf:0x52b5e5a15a58daf
2399997   0x89c80335ceb1a2bf:0x52b5e5a15a58daf
2399998   0x89c80335ceb1a2bf:0x52b5e5a15a58daf
2399999   0x89c80335ceb1a2bf:0x52b5e5a15a58daf

[2400000 rows x 8 columns]

In [188]:
maryland.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.162101e+20,Brian A,1528719383671,5,Every time I have been to this place I am in a...,None,None,0x89b7a76096bdad0b:0x66e4be0af3dc1720
1,1.089905e+20,Marsha J,1556106162554,5,"Good pharmacy and fast service, majority of th...",None,"{'time': 1556236566548, 'text': 'Hi Marsha, th...",0x89b7a76096bdad0b:0x66e4be0af3dc1720
2,1.179088e+20,Noel,1531995775977,5,Awesome service here!,None,None,0x89b7a76096bdad0b:0x66e4be0af3dc1720
3,1.174477e+20,Sheila Dickerson,1533222175613,1,I never received my prescription.,None,"{'time': 1533224288512, 'text': 'Can you pleas...",0x89b7a76096bdad0b:0x66e4be0af3dc1720
4,1.145177e+20,Carlos Alvarez,1489337608868,5,very fast,None,None,0x89b7a76096bdad0b:0x66e4be0af3dc1720

In [189]:
maryland_filtrado = maryland.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [190]:
maryland_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 259333 entries, 0 to 259332
Data columns (total 8 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   user_id  259333 non-null  float64
 1   name     259333 non-null  object
 2   time     259333 non-null  int64
 3   rating   259333 non-null  int64
 4   text     153149 non-null  object
 5   pics     8286 non-null    object
 6   resp     33711 non-null   object
 7   gmap_id  259333 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 15.8+ MB

In [191]:
# Convertir la columna 'time' a datetime
maryland_filtrado['time'] = pd.to_datetime(maryland_filtrado['time'], unit='ms')

In [192]:
maryland_filtrado = maryland_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [193]:
maryland_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [194]:
maryland_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    249199
Name: count, dtype: int64

In [195]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
maryland_filtrado.to_csv(os.path.join(ruta_reviews, "21-maryland.csv"),index= False)

22-Massachusetts

In [196]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-Massachusetts')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            massachusetts = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(massachusetts)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id              name           time  rating  \
0        1.180340e+20     Donna Carlson  1619732714443       5
1        1.101673e+20   michael simmons  1615400031636       5
2        1.122136e+20       Paul Murray  1593992657241       5
3        1.081745e+20  Elba De Oliveira  1582074606394       5
4        1.089901e+20      Sherri Mayne  1572962045881       5
...               ...               ...            ...     ...
2399995  1.035917e+20    Pamela Mcgrath  1560468960579       4
2399996  1.119652e+20  William Clements  1557681734626       5
2399997  1.092981e+20  Ryon Fairbrother  1565018872627       5
2399998  1.092482e+20     Ken Wilkerson  1555927830059       5
2399999  1.095445e+20  David Lafontaine  1557919246629       4

                                                      text  pics  \
0              People run it make sure you are comfortable  None
1                            When you need a helping hand.  None
2        Very Helpful and understanding people definite...  None
3        Very good place nice things but on Saturday th...  None
4                                            Awesome place  None
...                                                    ...   ...
2399995             Great local breakfast.  Great service.  None
2399996  Great breakfast. Inexpensive. Staff is great a...  None
2399997       Alitttle expensive but absolutely worth it !  None
2399998                     Very good pleasant nice people  None
2399999                    Good lunch time spot good food.  None

                                                      resp  \
0                                                     None
1                                                     None
2                                                     None
3                                                     None
4                                                     None
...                                                    ...
2399995  {'time': 1560469647836, 'text': 'Thanks Pamela...
2399996  {'time': 1557684888741, 'text': 'Thank you for...
2399997  {'time': 1565020361985, 'text': 'Thanks for ta...
2399998  {'time': 1556819352796, 'text': 'Thank you Ken...
2399999  {'time': 1557919947234, 'text': 'Thanks David ...

                                       gmap_id
0        0x89e4a103dd188585:0xfadc47938337579f
1        0x89e4a103dd188585:0xfadc47938337579f
2        0x89e4a103dd188585:0xfadc47938337579f
3        0x89e4a103dd188585:0xfadc47938337579f
4        0x89e4a103dd188585:0xfadc47938337579f
...                                        ...
2399995  0x89e2e0ce66141d15:0x6bbb01d029c6127a
2399996  0x89e2e0ce66141d15:0x6bbb01d029c6127a
2399997  0x89e2e0ce66141d15:0x6bbb01d029c6127a
2399998  0x89e2e0ce66141d15:0x6bbb01d029c6127a
2399999  0x89e2e0ce66141d15:0x6bbb01d029c6127a

[2400000 rows x 8 columns]

In [197]:
massachusetts.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.180340e+20,Donna Carlson,1619732714443,5,People run it make sure you are comfortable,None,None,0x89e4a103dd188585:0xfadc47938337579f
1,1.101673e+20,michael simmons,1615400031636,5,When you need a helping hand.,None,None,0x89e4a103dd188585:0xfadc47938337579f
2,1.122136e+20,Paul Murray,1593992657241,5,Very Helpful and understanding people definite...,None,None,0x89e4a103dd188585:0xfadc47938337579f
3,1.081745e+20,Elba De Oliveira,1582074606394,5,Very good place nice things but on Saturday th...,None,None,0x89e4a103dd188585:0xfadc47938337579f
4,1.089901e+20,Sherri Mayne,1572962045881,5,Awesome place,None,None,0x89e4a103dd188585:0xfadc47938337579f

In [198]:
massachusetts_filtrado = massachusetts.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [199]:
massachusetts_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 238100 entries, 0 to 238099
Data columns (total 8 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   user_id  238100 non-null  float64
 1   name     238100 non-null  object
 2   time     238100 non-null  int64
 3   rating   238100 non-null  int64
 4   text     134595 non-null  object
 5   pics     8136 non-null    object
 6   resp     13685 non-null   object
 7   gmap_id  238100 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 14.5+ MB

In [200]:
# Convertir la columna 'time' a datetime
massachusetts_filtrado['time'] = pd.to_datetime(massachusetts_filtrado['time'], unit='ms')

In [201]:
massachusetts_filtrado = massachusetts_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [202]:
massachusetts_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [203]:
massachusetts_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    232232
Name: count, dtype: int64

In [204]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
massachusetts_filtrado.to_csv(os.path.join(ruta_reviews, "22-massachusetts.csv"),index= False)

23-Michigan

In [205]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-Michigan')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            michigan = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(michigan)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id                    name           time  rating  \
0        1.149975e+20                 Deb Mae  1611524448905       5
1        1.046177e+20            sherry stone  1574805324619       1
2        1.064380e+20           Shannon Kropp  1455651168542       5
3        1.053143e+20                 M A T T  1595369812147       5
4        1.075909e+20            Not the Mama  1593635254254       5
...               ...                     ...            ...     ...
2249995  1.121551e+20           Larry Stehlik  1499555836404       5
2249996  1.055174e+20            George Styka  1488512224300       4
2249997  1.021731e+20           Edward Seiler  1557579251594       5
2249998  1.146437e+20  Hector MrHEME Espinola  1554895749450       5
2249999  1.165122e+20         David Gruesbeck  1568258894157       5

                                                      text  pics  \
0        I have been with Sara as my Agent for many yea...  None
1        I went to this allstate because I needed a new...  None
2        Everyone at this office is great!  They make m...  None
3                                            Great service  None
4                                                 Friendly  None
...                                                    ...   ...
2249995  I only live 2 blocks away. Fellow parishioners...  None
2249996  This is a good Catholic Church first small tow...  None
2249997  The only reason I was there was because they w...  None
2249998          Excellent place for Spiritual Nourishment  None
2249999                                   Very. Ice Church  None

                                                      resp  \
0        {'time': 1611589883844, 'text': 'Deb,  Thank y...
1                                                     None
2                                                     None
3                                                     None
4                                                     None
...                                                    ...
2249995                                               None
2249996                                               None
2249997                                               None
2249998                                               None
2249999                                               None

                                       gmap_id
0        0x883b4dcfa112c3f7:0xa893bca9bab5ec71
1        0x883b4dcfa112c3f7:0xa893bca9bab5ec71
2        0x883b4dcfa112c3f7:0xa893bca9bab5ec71
3        0x883b4dcfa112c3f7:0xa893bca9bab5ec71
4        0x883b4dcfa112c3f7:0xa893bca9bab5ec71
...                                        ...
2249995  0x882241e5afaf1e11:0x5934c1dae78d564f
2249996  0x882241e5afaf1e11:0x5934c1dae78d564f
2249997  0x882241e5afaf1e11:0x5934c1dae78d564f
2249998  0x882241e5afaf1e11:0x5934c1dae78d564f
2249999  0x882241e5afaf1e11:0x5934c1dae78d564f

[2250000 rows x 8 columns]

In [206]:
michigan.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.149975e+20,Deb Mae,1611524448905,5,I have been with Sara as my Agent for many yea...,None,"{'time': 1611589883844, 'text': 'Deb, Thank y...",0x883b4dcfa112c3f7:0xa893bca9bab5ec71
1,1.046177e+20,sherry stone,1574805324619,1,I went to this allstate because I needed a new...,None,None,0x883b4dcfa112c3f7:0xa893bca9bab5ec71
2,1.064380e+20,Shannon Kropp,1455651168542,5,Everyone at this office is great! They make m...,None,None,0x883b4dcfa112c3f7:0xa893bca9bab5ec71
3,1.053143e+20,M A T T,1595369812147,5,Great service,None,None,0x883b4dcfa112c3f7:0xa893bca9bab5ec71
4,1.075909e+20,Not the Mama,1593635254254,5,Friendly,None,None,0x883b4dcfa112c3f7:0xa893bca9bab5ec71

In [207]:
michigan_filtrado = michigan.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [208]:
michigan_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 495567 entries, 0 to 495566
Data columns (total 8 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   user_id  495567 non-null  float64
 1   name     495567 non-null  object
 2   time     495567 non-null  int64
 3   rating   495567 non-null  int64
 4   text     295456 non-null  object
 5   pics     12596 non-null   object
 6   resp     59739 non-null   object
 7   gmap_id  495567 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 30.2+ MB

In [209]:
# Convertir la columna 'time' a datetime
michigan_filtrado['time'] = pd.to_datetime(michigan_filtrado['time'], unit='ms')

In [210]:
michigan_filtrado = michigan_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [211]:
michigan_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [212]:
michigan_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    474745
Name: count, dtype: int64

In [213]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
michigan_filtrado.to_csv(os.path.join(ruta_reviews, "23-michigan.csv"),index= False)

24-Minnesota

In [214]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-Minnesota')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            minnesota = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(minnesota)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id                            name           time  rating  \
0        1.129131e+20                       king 8488  1600976328270       5
1        1.162558e+20                  Steve Thornton  1544372192905       5
2        1.019050e+20                   Jessica Perry  1464405464526       5
3        1.042615e+20                   Frank Beissel  1537928043548       4
4        1.023054e+20                     Ryan Kwyzla  1538256770007       5
...               ...                             ...            ...     ...
1799995  1.180491e+20                    Ennis Sweats  1581190069920       5
1799996  1.011134e+20                    Kristan Roth  1596523381502       5
1799997  1.080643e+20                         Deke BL  1578290338482       2
1799998  1.161756e+20  Forest Log Furniture & Railing  1517761931105       5
1799999  1.127476e+20                    Mike Johnson  1581521852367       5

                                                      text  \
0        Super helpful local business they are there fo...
1        I was renting at a popular nation wide chain a...
2        Hands down the best place ever! Ran by super n...
3        Edit.  I was wrong. Wrong place.\n\nThey seem ...
4        Super friendly and helpful staff. Location is ...
...                                                    ...
1799995                            Great service and pool!
1799996                                               None
1799997                                               None
1799998  Great place with great people!   HayDays is a ...
1799999  If your looking for a fun weekend dont miss th...

                                                      pics  \
0                                                     None
1                                                     None
2                                                     None
3                                                     None
4                                                     None
...                                                    ...
1799995                                               None
1799996                                               None
1799997                                               None
1799998  [{'url': ['https://lh5.googleusercontent.com/p...
1799999                                               None

                                                      resp  \
0        {'time': 1605627047572, 'text': 'Thank you for...
1        {'time': 1544549857922, 'text': 'Thank you Ste...
2                                                     None
3        {'time': 1537509536392, 'text': 'I believe you...
4        {'time': 1544550134880, 'text': 'Thanks Ryan! ...
...                                                    ...
1799995  {'time': 1583896929433, 'text': 'Thank you for...
1799996                                               None
1799997  {'time': 1583896721239, 'text': 'We apologize ...
1799998                                               None
1799999                                               None

                                       gmap_id
0        0x87f630d649635d65:0x57b17f6d51a91c8b
1        0x87f630d649635d65:0x57b17f6d51a91c8b
2        0x87f630d649635d65:0x57b17f6d51a91c8b
3        0x87f630d649635d65:0x57b17f6d51a91c8b
4        0x87f630d649635d65:0x57b17f6d51a91c8b
...                                        ...
1799995  0x87f75f87ac16b06b:0xe247a38a547218f9
1799996  0x87f75f87ac16b06b:0xe247a38a547218f9
1799997  0x87f75f87ac16b06b:0xe247a38a547218f9
1799998  0x52b28b38d2e43407:0x69c9a7a4746a8033
1799999  0x52b28b38d2e43407:0x69c9a7a4746a8033

[1800000 rows x 8 columns]

In [215]:
minnesota.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.129131e+20,king 8488,1600976328270,5,Super helpful local business they are there fo...,None,"{'time': 1605627047572, 'text': 'Thank you for...",0x87f630d649635d65:0x57b17f6d51a91c8b
1,1.162558e+20,Steve Thornton,1544372192905,5,I was renting at a popular nation wide chain a...,None,"{'time': 1544549857922, 'text': 'Thank you Ste...",0x87f630d649635d65:0x57b17f6d51a91c8b
2,1.019050e+20,Jessica Perry,1464405464526,5,Hands down the best place ever! Ran by super n...,None,None,0x87f630d649635d65:0x57b17f6d51a91c8b
3,1.042615e+20,Frank Beissel,1537928043548,4,Edit. I was wrong. Wrong place.\n\nThey seem ...,None,"{'time': 1537509536392, 'text': 'I believe you...",0x87f630d649635d65:0x57b17f6d51a91c8b
4,1.023054e+20,Ryan Kwyzla,1538256770007,5,Super friendly and helpful staff. Location is ...,None,"{'time': 1544550134880, 'text': 'Thanks Ryan! ...",0x87f630d649635d65:0x57b17f6d51a91c8b

In [216]:
minnesota_filtrado = minnesota.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [217]:
minnesota_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 218459 entries, 0 to 218458
Data columns (total 8 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   user_id  218459 non-null  float64
 1   name     218459 non-null  object
 2   time     218459 non-null  int64
 3   rating   218459 non-null  int64
 4   text     129133 non-null  object
 5   pics     7005 non-null    object
 6   resp     21819 non-null   object
 7   gmap_id  218459 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 13.3+ MB

In [218]:
# Convertir la columna 'time' a datetime
minnesota_filtrado['time'] = pd.to_datetime(minnesota_filtrado['time'], unit='ms')

In [219]:
minnesota_filtrado = minnesota_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [220]:
minnesota_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [221]:
minnesota_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    210242
Name: count, dtype: int64

In [222]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
minnesota_filtrado.to_csv(os.path.join(ruta_reviews, "24-minnesota.csv"),index= False)

25-Mississippi

In [223]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-Mississippi')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            mississippi = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(mississippi)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id                   name           time  rating  \
0        1.098186e+20         Patti Strother  1598023328629       1
1        1.089888e+20         Hilda Forister  1492212551217       5
2        1.092447e+20                   J TH  1530800061632       5
3        1.147864e+20           Tim Ashcraft  1447764412977       3
4        1.083701e+20           DAVE MARABLE  1484427496391       5
...               ...                    ...            ...     ...
1971176  1.167125e+20     Stephanie Williams  1484672153622       5
1971177  1.023635e+20         Ayhana *******  1544146277916       1
1971178  1.129878e+20         Charles Wright  1479520973959       4
1971179  1.141740e+20  Sharon Schamber-Jones  1583017086381       5
1971180  1.000159e+20          Paula Mathews  1560784729072       5

                                                      text  pics  \
0        Don’t Use your DEBIT CARD at this location! Sk...  None
1        Every time I have gone it's either for gas or ...  None
2        There's a young black male who works here that...  None
3        No. This is not always the best gas price arou...  None
4        Staff and service are great!!! Chicken combo i...  None
...                                                    ...   ...
1971176  Best Po'boys. We eat here multiple times durin...  None
1971177  Food wasn't all that...I had the shrimp poboy ...  None
1971178       Real po-boys, red beans and rice, gumbo, bbq  None
1971179                                     Love this food  None
1971180                                    Love their food  None

                                                      resp  \
0                                                     None
1                                                     None
2                                                     None
3                                                     None
4        {'time': 1484964924867, 'text': 'Dave, thank y...
...                                                    ...
1971176                                               None
1971177                                               None
1971178                                               None
1971179                                               None
1971180                                               None

                                       gmap_id
0        0x887f93d5418166af:0xbbce72cb50342df1
1        0x887f93d5418166af:0xbbce72cb50342df1
2        0x887f93d5418166af:0xbbce72cb50342df1
3        0x887f93d5418166af:0xbbce72cb50342df1
4        0x887f93d5418166af:0xbbce72cb50342df1
...                                        ...
1971176  0x889cde9e7b61b3f5:0x5df0c480c8046690
1971177  0x889cde9e7b61b3f5:0x5df0c480c8046690
1971178  0x889cde9e7b61b3f5:0x5df0c480c8046690
1971179  0x889cde9e7b61b3f5:0x5df0c480c8046690
1971180  0x889cde9e7b61b3f5:0x5df0c480c8046690

[1971181 rows x 8 columns]

In [224]:
mississippi.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.098186e+20,Patti Strother,1598023328629,1,Don’t Use your DEBIT CARD at this location! Sk...,None,None,0x887f93d5418166af:0xbbce72cb50342df1
1,1.089888e+20,Hilda Forister,1492212551217,5,Every time I have gone it's either for gas or ...,None,None,0x887f93d5418166af:0xbbce72cb50342df1
2,1.092447e+20,J TH,1530800061632,5,There's a young black male who works here that...,None,None,0x887f93d5418166af:0xbbce72cb50342df1
3,1.147864e+20,Tim Ashcraft,1447764412977,3,No. This is not always the best gas price arou...,None,None,0x887f93d5418166af:0xbbce72cb50342df1
4,1.083701e+20,DAVE MARABLE,1484427496391,5,Staff and service are great!!! Chicken combo i...,None,"{'time': 1484964924867, 'text': 'Dave, thank y...",0x887f93d5418166af:0xbbce72cb50342df1

In [225]:
mississippi_filtrado = mississippi.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [226]:
mississippi_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90555 entries, 0 to 90554
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   user_id  90555 non-null  float64
 1   name     90555 non-null  object
 2   time     90555 non-null  int64
 3   rating   90555 non-null  int64
 4   text     51790 non-null  object
 5   pics     2301 non-null   object
 6   resp     7768 non-null   object
 7   gmap_id  90555 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 5.5+ MB

In [227]:
# Convertir la columna 'time' a datetime
mississippi_filtrado['time'] = pd.to_datetime(mississippi_filtrado['time'], unit='ms')

In [228]:
mississippi_filtrado = mississippi_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [229]:
mississippi_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [230]:
mississippi_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    87896
Name: count, dtype: int64

In [231]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
mississippi_filtrado.to_csv(os.path.join(ruta_reviews, "25-mississippi.csv"),index= False)

26-Missouri

In [232]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-Missouri')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            missouri = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(missouri)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id                name           time  rating  \
0        1.089882e+20        Tracy Reeder  1575932557871       1
1        1.004776e+20       Brett Stevens  1554489896899       5
2        1.181701e+20     steven williams  1498137347552       5
3        1.085274e+20                   b  1511496601769       5
4        1.034012e+20         Bekkah said  1505363292500       5
...               ...                 ...            ...     ...
1649995  1.036469e+20                Mark  1509297527199       4
1649996  1.056938e+20        Angela Brown  1577505155005       2
1649997  1.008615e+20      Sue Ann Taylor  1513169616567       4
1649998  1.114684e+20  Elizabeth Berthold  1617942030115       4
1649999  1.171190e+20          Brad Jones  1610971673131       3

                                                      text  pics  resp  \
0        This company seems like a great place to work ...  None  None
1                                                     None  None  None
2                                                     None  None  None
3                                                     None  None  None
4                                                     None  None  None
...                                                    ...   ...   ...
1649995                                               None  None  None
1649996                                               None  None  None
1649997                                               None  None  None
1649998                                               None  None  None
1649999                                               None  None  None

                                       gmap_id
0        0x87c87e473635feb5:0x6de42f63fb4ad19b
1        0x87c87e473635feb5:0x6de42f63fb4ad19b
2        0x87c87e473635feb5:0x6de42f63fb4ad19b
3        0x87c87e473635feb5:0x6de42f63fb4ad19b
4        0x87c87e473635feb5:0x6de42f63fb4ad19b
...                                        ...
1649995  0x88778bf7b76136e9:0x45b17ddec8e1f978
1649996  0x88778bf7b76136e9:0x45b17ddec8e1f978
1649997  0x88778bf7b76136e9:0x45b17ddec8e1f978
1649998  0x88778bf7b76136e9:0x45b17ddec8e1f978
1649999  0x88778bf7b76136e9:0x45b17ddec8e1f978

[1650000 rows x 8 columns]

In [233]:
missouri.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.089882e+20,Tracy Reeder,1575932557871,1,This company seems like a great place to work ...,None,None,0x87c87e473635feb5:0x6de42f63fb4ad19b
1,1.004776e+20,Brett Stevens,1554489896899,5,None,None,None,0x87c87e473635feb5:0x6de42f63fb4ad19b
2,1.181701e+20,steven williams,1498137347552,5,None,None,None,0x87c87e473635feb5:0x6de42f63fb4ad19b
3,1.085274e+20,b,1511496601769,5,None,None,None,0x87c87e473635feb5:0x6de42f63fb4ad19b
4,1.034012e+20,Bekkah said,1505363292500,5,None,None,None,0x87c87e473635feb5:0x6de42f63fb4ad19b

In [234]:
missouri_filtrado = missouri.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [235]:
missouri_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301264 entries, 0 to 301263
Data columns (total 8 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   user_id  301264 non-null  float64
 1   name     301264 non-null  object
 2   time     301264 non-null  int64
 3   rating   301264 non-null  int64
 4   text     179592 non-null  object
 5   pics     8171 non-null    object
 6   resp     35439 non-null   object
 7   gmap_id  301264 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 18.4+ MB

In [236]:
# Convertir la columna 'time' a datetime
missouri_filtrado['time'] = pd.to_datetime(missouri_filtrado['time'], unit='ms')

In [237]:
missouri_filtrado = missouri_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [238]:
missouri_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [239]:
missouri_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    288344
Name: count, dtype: int64

In [240]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
missouri_filtrado.to_csv(os.path.join(ruta_reviews, "26-missouri.csv"),index= False)

27-Montana

In [241]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-Montana')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            montana = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(montana)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

             user_id                name           time  rating  \
0       1.147715e+20  Shifts and giggles  1618975510300       5
1       1.005777e+20        Craig Thomas  1609450506236       5
2       1.052042e+20       Lance Broshar  1595447399474       5
3       1.105216e+20        Inicorn Refs  1569377416664       5
4       1.158574e+20                Chad  1607551230333       5
...              ...                 ...            ...     ...
950365  1.036458e+20  Kichōna loli queen  1571608396089       4
950366  1.035258e+20        Jaret Barnes  1554484273888       3
950367  1.104458e+20       Cassy Gabriel  1537795502246       3
950368  1.145894e+20      Jennifer Derby  1527548899649       4
950369  1.083638e+20    Amanda Carpenter  1525062920569       5

                                                     text  pics  resp  \
0       Good people that know thier stuff excellent cu...  None  None
1                  Fixed my saw bout 10min.\n\n1st class.  None  None
2       Excellent service and products. Fair and reaso...  None  None
3       One day they may start accepting credit cards!...  None  None
4                                 Great place good people  None  None
...                                                   ...   ...   ...
950365                                               None  None  None
950366                                               None  None  None
950367                                               None  None  None
950368                                               None  None  None
950369                                               None  None  None

                                      gmap_id
0       0x535e9ec3ce050deb:0x2169887374ce879f
1       0x535e9ec3ce050deb:0x2169887374ce879f
2       0x535e9ec3ce050deb:0x2169887374ce879f
3       0x535e9ec3ce050deb:0x2169887374ce879f
4       0x535e9ec3ce050deb:0x2169887374ce879f
...                                       ...
950365  0x53457c9d5d6a0d55:0xd237e6eeab6e28f9
950366  0x53457c9d5d6a0d55:0xd237e6eeab6e28f9
950367  0x53457c9d5d6a0d55:0xd237e6eeab6e28f9
950368  0x53457c9d5d6a0d55:0xd237e6eeab6e28f9
950369  0x53457c9d5d6a0d55:0xd237e6eeab6e28f9

[950370 rows x 8 columns]

In [242]:
montana.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.147715e+20,Shifts and giggles,1618975510300,5,Good people that know thier stuff excellent cu...,None,None,0x535e9ec3ce050deb:0x2169887374ce879f
1,1.005777e+20,Craig Thomas,1609450506236,5,Fixed my saw bout 10min.\n\n1st class.,None,None,0x535e9ec3ce050deb:0x2169887374ce879f
2,1.052042e+20,Lance Broshar,1595447399474,5,Excellent service and products. Fair and reaso...,None,None,0x535e9ec3ce050deb:0x2169887374ce879f
3,1.105216e+20,Inicorn Refs,1569377416664,5,One day they may start accepting credit cards!...,None,None,0x535e9ec3ce050deb:0x2169887374ce879f
4,1.158574e+20,Chad,1607551230333,5,Great place good people,None,None,0x535e9ec3ce050deb:0x2169887374ce879f

In [243]:
montana_filtrado = montana.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [244]:
montana_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37042 entries, 0 to 37041
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   user_id  37042 non-null  float64
 1   name     37042 non-null  object
 2   time     37042 non-null  int64
 3   rating   37042 non-null  int64
 4   text     22310 non-null  object
 5   pics     821 non-null    object
 6   resp     4498 non-null   object
 7   gmap_id  37042 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 2.3+ MB

In [245]:
# Convertir la columna 'time' a datetime
montana_filtrado['time'] = pd.to_datetime(montana_filtrado['time'], unit='ms')

In [246]:
montana_filtrado = montana_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [247]:
montana_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [248]:
montana_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    36020
Name: count, dtype: int64

In [249]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
montana_filtrado.to_csv(os.path.join(ruta_reviews, "27-montana.csv"),index= False)

28-Nebraska

In [250]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-Nebraska')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            nebraska = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(nebraska)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id             name           time  rating  \
0        1.088468e+20       Dan Grundy  1608331653332       5
1        1.161914e+20  dominick vacura  1627079809988       5
2        1.089856e+20      Cody Albers  1533832546055       4
3        1.169268e+20    Markus Farmer  1559062491880       5
4        1.147214e+20     james spevak  1526077661056       5
...               ...              ...            ...     ...
1817861  1.045794e+20     Dawn Jourdan  1556995548676       4
1817862  1.139890e+20              Jas  1479847523955       1
1817863  1.157996e+20           Ed Bok  1523709298777       5
1817864  1.108659e+20    Angelica Dunn  1542595813513       3
1817865  1.068396e+20   Crystal Prayer  1535903717796       1

                                                      text  pics  resp  \
0        For give me for not catching the managers name...  None  None
1                                         I've got shades!  None  None
2        Went here to see if I could get my glasses adj...  None  None
3        Very helpful with questions. More Versace plea...  None  None
4        Pretty good place to look for sunglasses. But ...  None  None
...                                                    ...   ...   ...
1817861               Lots of tpppings and hot fresh pizza  None  None
1817862  Honestly I wish I could rate this disgusting p...  None  None
1817863  Not much ambience, but good food, fair prices,...  None  None
1817864            It was a decent meal. (Or snack for me)  None  None
1817865  Big mix up with my order. Had to wait a half h...  None  None

                                       gmap_id
0         0x8793f2b4d692a433:0xc4d08ac32475203
1         0x8793f2b4d692a433:0xc4d08ac32475203
2         0x8793f2b4d692a433:0xc4d08ac32475203
3         0x8793f2b4d692a433:0xc4d08ac32475203
4         0x8793f2b4d692a433:0xc4d08ac32475203
...                                        ...
1817861  0x87938e5b4d378c8b:0xe8eff1ddd3a150d8
1817862  0x87938e5b4d378c8b:0xe8eff1ddd3a150d8
1817863  0x87938e5b4d378c8b:0xe8eff1ddd3a150d8
1817864  0x87938e5b4d378c8b:0xe8eff1ddd3a150d8
1817865  0x87938e5b4d378c8b:0xe8eff1ddd3a150d8

[1817866 rows x 8 columns]

In [251]:
nebraska.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.088468e+20,Dan Grundy,1608331653332,5,For give me for not catching the managers name...,None,None,0x8793f2b4d692a433:0xc4d08ac32475203
1,1.161914e+20,dominick vacura,1627079809988,5,I've got shades!,None,None,0x8793f2b4d692a433:0xc4d08ac32475203
2,1.089856e+20,Cody Albers,1533832546055,4,Went here to see if I could get my glasses adj...,None,None,0x8793f2b4d692a433:0xc4d08ac32475203
3,1.169268e+20,Markus Farmer,1559062491880,5,Very helpful with questions. More Versace plea...,None,None,0x8793f2b4d692a433:0xc4d08ac32475203
4,1.147214e+20,james spevak,1526077661056,5,Pretty good place to look for sunglasses. But ...,None,None,0x8793f2b4d692a433:0xc4d08ac32475203

In [252]:
nebraska_filtrado = nebraska.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [253]:
nebraska_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93894 entries, 0 to 93893
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   user_id  93894 non-null  float64
 1   name     93894 non-null  object
 2   time     93894 non-null  int64
 3   rating   93894 non-null  int64
 4   text     52682 non-null  object
 5   pics     2054 non-null   object
 6   resp     12116 non-null  object
 7   gmap_id  93894 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 5.7+ MB

In [254]:
# Convertir la columna 'time' a datetime
nebraska_filtrado['time'] = pd.to_datetime(nebraska_filtrado['time'], unit='ms')

In [255]:
nebraska_filtrado = nebraska_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [256]:
nebraska_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [257]:
nebraska_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    90440
Name: count, dtype: int64

In [258]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
nebraska_filtrado.to_csv(os.path.join(ruta_reviews, "28-nebraska.csv"),index= False)

29-Nevada

In [4]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-Nevada')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            nevada = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(nevada)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id               name           time  rating  \
0        1.028432e+20             CDL CO  1622740504476       5
1        1.149544e+20          So_ Blind  1573159413820       1
2        1.165234e+20        Greg Hansen  1515251163362       3
3        1.033041e+20       Brett Powell  1506206762095       3
4        1.141624e+20             M Aris  1468298771892       3
...               ...                ...            ...     ...
1799995  1.060821e+20  Lisa Frederickson  1509630851579       3
1799996  1.161710e+20     Wayne Davidson  1593727427643       5
1799997  1.079303e+20  Lauren Moore-Dowd  1594864074734       3
1799998  1.053944e+20    Jared Benavente  1506237834626       5
1799999  1.144681e+20                R L  1490195898234       4

                                                      text  \
0        No frills smaller coffee counter in the corner...
1        Save yourself the frustration and just ignore ...
2        I passed two Starbucks in order to get to this...
3        It does the job and is my preference over the ...
4                                                     None
...                                                    ...
1799995                                               None
1799996                                               None
1799997                                               None
1799998                                               None
1799999                                               None

                                                      pics  resp  \
0        [{'url': ['https://lh5.googleusercontent.com/p...  None
1                                                     None  None
2                                                     None  None
3                                                     None  None
4                                                     None  None
...                                                    ...   ...
1799995                                               None  None
1799996                                               None  None
1799997                                               None  None
1799998                                               None  None
1799999                                               None  None

                                       gmap_id
0        0x80c8c5cdced316b5:0xaf1ea0b1e42132a9
1        0x80c8c5cdced316b5:0xaf1ea0b1e42132a9
2        0x80c8c5cdced316b5:0xaf1ea0b1e42132a9
3        0x80c8c5cdced316b5:0xaf1ea0b1e42132a9
4        0x80c8c5cdced316b5:0xaf1ea0b1e42132a9
...                                        ...
1799995  0x80c8b8b2bdb3aea1:0xffd9ed0a9a5698b7
1799996  0x80c8b8b2bdb3aea1:0xffd9ed0a9a5698b7
1799997  0x80c8b8b2bdb3aea1:0xffd9ed0a9a5698b7
1799998  0x80c8b8b2bdb3aea1:0xffd9ed0a9a5698b7
1799999  0x80c8b8b2bdb3aea1:0xffd9ed0a9a5698b7

[1800000 rows x 8 columns]

In [5]:
nevada.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.028432e+20,CDL CO,1622740504476,5,No frills smaller coffee counter in the corner...,[{'url': ['https://lh5.googleusercontent.com/p...,None,0x80c8c5cdced316b5:0xaf1ea0b1e42132a9
1,1.149544e+20,So_ Blind,1573159413820,1,Save yourself the frustration and just ignore ...,None,None,0x80c8c5cdced316b5:0xaf1ea0b1e42132a9
2,1.165234e+20,Greg Hansen,1515251163362,3,I passed two Starbucks in order to get to this...,None,None,0x80c8c5cdced316b5:0xaf1ea0b1e42132a9
3,1.033041e+20,Brett Powell,1506206762095,3,It does the job and is my preference over the ...,None,None,0x80c8c5cdced316b5:0xaf1ea0b1e42132a9
4,1.141624e+20,M Aris,1468298771892,3,None,None,None,0x80c8c5cdced316b5:0xaf1ea0b1e42132a9

In [6]:
nevada_filtrado = nevada.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [7]:
nevada_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136922 entries, 0 to 136921
Data columns (total 8 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   user_id  136922 non-null  float64
 1   name     136922 non-null  object
 2   time     136922 non-null  int64
 3   rating   136922 non-null  int64
 4   text     85226 non-null   object
 5   pics     6904 non-null    object
 6   resp     12339 non-null   object
 7   gmap_id  136922 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 8.4+ MB

In [8]:
# Convertir la columna 'time' a datetime
nevada_filtrado['time'] = pd.to_datetime(nevada_filtrado['time'], unit='ms')

In [9]:
nevada_filtrado = nevada_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [10]:
nevada_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [11]:
nevada_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    130718
Name: count, dtype: int64

In [12]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
nevada_filtrado.to_csv(os.path.join(ruta_reviews, "29-nevada.csv"),index= False)

30-New Hampshire

In [13]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-New_Hampshire')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            new_hampshire = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(new_hampshire)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id               name           time  rating  \
0        1.073259e+20  Jeffrey J Howland  1621473866341       4
1        1.130123e+20    Nathaniel Houle  1604724170325       5
2        1.058399e+20     Shannon Thomas  1585573760111       5
3        1.066511e+20         Lora Haase  1593363624213       5
4        1.130374e+20       David Blouin  1593808080254       4
...               ...                ...            ...     ...
1296598  1.035316e+20      William Young  1596018061526       3
1296599  1.036999e+20        Kevin Grice  1602211998874       3
1296600  1.133995e+20   Jennifer Glidden  1559961342587       5
1296601  1.073657e+20   Samantha Currier  1589770147606       3
1296602  1.035775e+20    Michael Fortier  1535548398148       5

                                                      text  pics  resp  \
0        Like many campgrounds dust is a problem... but...  None  None
1        Nice clean and welcoming campground.  Love the...  None  None
2        ❤Super friendly people and very well maintaine...  None  None
3        Great time. Owners are awesome.  Had a great w...  None  None
4        Seems like a nice family owned campground the ...  None  None
...                                                    ...   ...   ...
1296598                                               None  None  None
1296599                                               None  None  None
1296600                                               None  None  None
1296601                                               None  None  None
1296602                                               None  None  None

                                       gmap_id
0        0x89e2936fffffffff:0x3fce71a3d83aa514
1        0x89e2936fffffffff:0x3fce71a3d83aa514
2        0x89e2936fffffffff:0x3fce71a3d83aa514
3        0x89e2936fffffffff:0x3fce71a3d83aa514
4        0x89e2936fffffffff:0x3fce71a3d83aa514
...                                        ...
1296598  0x89e26a8ce6b0e6d9:0xe1e5d554891834ee
1296599  0x89e26a8ce6b0e6d9:0xe1e5d554891834ee
1296600  0x89e26a8ce6b0e6d9:0xe1e5d554891834ee
1296601  0x89e26a8ce6b0e6d9:0xe1e5d554891834ee
1296602  0x89e26a8ce6b0e6d9:0xe1e5d554891834ee

[1296603 rows x 8 columns]

In [14]:
new_hampshire.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.073259e+20,Jeffrey J Howland,1621473866341,4,Like many campgrounds dust is a problem... but...,None,None,0x89e2936fffffffff:0x3fce71a3d83aa514
1,1.130123e+20,Nathaniel Houle,1604724170325,5,Nice clean and welcoming campground. Love the...,None,None,0x89e2936fffffffff:0x3fce71a3d83aa514
2,1.058399e+20,Shannon Thomas,1585573760111,5,❤Super friendly people and very well maintaine...,None,None,0x89e2936fffffffff:0x3fce71a3d83aa514
3,1.066511e+20,Lora Haase,1593363624213,5,Great time. Owners are awesome. Had a great w...,None,None,0x89e2936fffffffff:0x3fce71a3d83aa514
4,1.130374e+20,David Blouin,1593808080254,4,Seems like a nice family owned campground the ...,None,None,0x89e2936fffffffff:0x3fce71a3d83aa514

In [15]:
new_hampshire_filtrado = new_hampshire.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [16]:
new_hampshire_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46559 entries, 0 to 46558
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   user_id  46559 non-null  float64
 1   name     46559 non-null  object
 2   time     46559 non-null  int64
 3   rating   46559 non-null  int64
 4   text     28368 non-null  object
 5   pics     1304 non-null   object
 6   resp     4732 non-null   object
 7   gmap_id  46559 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 2.8+ MB

In [17]:
# Convertir la columna 'time' a datetime
new_hampshire_filtrado['time'] = pd.to_datetime(new_hampshire_filtrado['time'], unit='ms')

In [18]:
new_hampshire_filtrado = new_hampshire_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [19]:
new_hampshire_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [20]:
new_hampshire_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    45342
Name: count, dtype: int64

In [21]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
new_hampshire_filtrado.to_csv(os.path.join(ruta_reviews, "30-new_hampshire.csv"),index= False)

31-New Jersey

In [22]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-New_Jersey')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            new_jersey = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(new_jersey)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id                 name           time  rating  \
0        1.011903e+20         Monica Zobbi  1614634731992       5
1        1.172699e+20    Vitaliia Stefurak  1572974792541       5
2        1.152270e+20         Maria Guzman  1578525387607       5
3        1.161828e+20               Jo Rad  1602103279588       5
4        1.010712e+20       Kimberly Hults  1593034107348       5
...               ...                  ...            ...     ...
1949995  1.035862e+20  Karim Khaled Hashem  1609702826112       1
1949996  1.058550e+20          Sandra West  1613433636387       1
1949997  1.044227e+20          Cactus Jack  1609735699011       5
1949998  1.068292e+20         Larry Ramsey  1581622250541       5
1949999  1.175104e+20          Jake George  1611621301591       4

                                                      text  pics  \
0        Viktoriya is always very professional and atte...  None
1        If I could leave them 10 starts I would , unbe...  None
2        Laura took her time to know my hair and what s...  None
3        Wow, what an experience! Haircut by Victoria! ...  None
4        Love this salon! The great experience starts o...  None
...                                                    ...   ...
1949995  Ordered sushi that was literally wrapped in pa...  None
1949996  Salmon teriyaki with no teriyaki, sushi tasted...  None
1949997  I like this place fresh seafood and bite size ...  None
1949998  I visit this outstanding restaurant every coup...  None
1949999                    Great food and very nice staff.  None

                                                      resp  \
0                                                     None
1                                                     None
2                                                     None
3        {'time': 1576097102614, 'text': 'Thank you! Th...
4        {'time': 1575147680996, 'text': 'Thanks for th...
...                                                    ...
1949995  {'time': 1609791361113, 'text': 'Thank you for...
1949996                                               None
1949997                                               None
1949998                                               None
1949999                                               None

                                       gmap_id
0         0x89c2fb42465dd457:0x437fc2232abf899
1         0x89c2fb42465dd457:0x437fc2232abf899
2         0x89c2fb42465dd457:0x437fc2232abf899
3         0x89c2fb42465dd457:0x437fc2232abf899
4         0x89c2fb42465dd457:0x437fc2232abf899
...                                        ...
1949995  0x89c2f030ad7792d7:0x504091b4da3918a0
1949996  0x89c2f030ad7792d7:0x504091b4da3918a0
1949997  0x89c2f030ad7792d7:0x504091b4da3918a0
1949998  0x89c2f030ad7792d7:0x504091b4da3918a0
1949999  0x89c2f030ad7792d7:0x504091b4da3918a0

[1950000 rows x 8 columns]

In [23]:
new_jersey.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.011903e+20,Monica Zobbi,1614634731992,5,Viktoriya is always very professional and atte...,None,None,0x89c2fb42465dd457:0x437fc2232abf899
1,1.172699e+20,Vitaliia Stefurak,1572974792541,5,"If I could leave them 10 starts I would , unbe...",None,None,0x89c2fb42465dd457:0x437fc2232abf899
2,1.152270e+20,Maria Guzman,1578525387607,5,Laura took her time to know my hair and what s...,None,None,0x89c2fb42465dd457:0x437fc2232abf899
3,1.161828e+20,Jo Rad,1602103279588,5,"Wow, what an experience! Haircut by Victoria! ...",None,"{'time': 1576097102614, 'text': 'Thank you! Th...",0x89c2fb42465dd457:0x437fc2232abf899
4,1.010712e+20,Kimberly Hults,1593034107348,5,Love this salon! The great experience starts o...,None,"{'time': 1575147680996, 'text': 'Thanks for th...",0x89c2fb42465dd457:0x437fc2232abf899

In [24]:
new_jersey_filtrado = new_jersey.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [25]:
new_jersey_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 406337 entries, 0 to 406336
Data columns (total 8 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   user_id  406337 non-null  float64
 1   name     406337 non-null  object
 2   time     406337 non-null  int64
 3   rating   406337 non-null  int64
 4   text     235028 non-null  object
 5   pics     13767 non-null   object
 6   resp     30583 non-null   object
 7   gmap_id  406337 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 24.8+ MB

In [26]:
# Convertir la columna 'time' a datetime
new_jersey_filtrado['time'] = pd.to_datetime(new_jersey_filtrado['time'], unit='ms')

In [27]:
new_jersey_filtrado = new_jersey_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [28]:
new_jersey_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [29]:
new_jersey_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    394591
Name: count, dtype: int64

In [30]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
new_jersey_filtrado.to_csv(os.path.join(ruta_reviews, "31-new_jersey.csv"),index= False)

32-New Mexico

In [31]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-New_Mexico')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            new_mexico = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(new_mexico)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id               name           time  rating  \
0        1.090151e+20        Tania Solis  1607374166577       5
1        1.146420e+20      James Watters  1558380690011       5
2        1.181733e+20           Jesse G.  1542751368749       1
3        1.159089e+20               TR S  1486093061400       4
4        1.089812e+20       Mannie Myers  1625862764044       4
...               ...                ...            ...     ...
1799995  1.110333e+20  Angelo Santomenna  1619308339660       5
1799996  1.121382e+20    Kimberly Zamora  1557375153484       5
1799997  1.138603e+20      Johnell Davis  1513868243446       2
1799998  1.060168e+20  Catherine Johnson  1539283927856       4
1799999  1.107276e+20            Melanie  1613710196729       5

                                                      text  pics  \
0        I was helped by Rachel and let me tell you! Sh...  None
1        Colton was fantastic to work with and our shir...  None
2        I've been a returning customer for sometime an...  None
3                        Flighty service. Great selection.  None
4                                                     None  None
...                                                    ...   ...
1799995                                               None  None
1799996                                               None  None
1799997                                               None  None
1799998                                               None  None
1799999                                               None  None

                                                      resp  \
0        {'time': 1610492163288, 'text': 'Thank you Tan...
1        {'time': 1558533046333, 'text': 'Thank you Jam...
2        {'time': 1542752652008, 'text': 'Jesse,

When ...
3                                                     None
4                                                     None
...                                                    ...
1799995  {'time': 1619447517581, 'text': 'Hello, Thanks...
1799996                                               None
1799997  {'time': 1514413250232, 'text': 'Hi Johnell, I...
1799998                                               None
1799999  {'time': 1613765080538, 'text': 'Hello Melanie...

                                       gmap_id
0        0x86fc95104733adc1:0x94da050d754f90b3
1        0x86fc95104733adc1:0x94da050d754f90b3
2        0x86fc95104733adc1:0x94da050d754f90b3
3        0x86fc95104733adc1:0x94da050d754f90b3
4        0x86fc95104733adc1:0x94da050d754f90b3
...                                        ...
1799995  0x8718a0fab282c73f:0x656efaaf8b8cee48
1799996  0x8718a0fab282c73f:0x656efaaf8b8cee48
1799997  0x8718a0fab282c73f:0x656efaaf8b8cee48
1799998  0x8718a0fab282c73f:0x656efaaf8b8cee48
1799999  0x8718a0fab282c73f:0x656efaaf8b8cee48

[1800000 rows x 8 columns]

In [32]:
new_mexico.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.090151e+20,Tania Solis,1607374166577,5,I was helped by Rachel and let me tell you! Sh...,None,"{'time': 1610492163288, 'text': 'Thank you Tan...",0x86fc95104733adc1:0x94da050d754f90b3
1,1.146420e+20,James Watters,1558380690011,5,Colton was fantastic to work with and our shir...,None,"{'time': 1558533046333, 'text': 'Thank you Jam...",0x86fc95104733adc1:0x94da050d754f90b3
2,1.181733e+20,Jesse G.,1542751368749,1,I've been a returning customer for sometime an...,None,"{'time': 1542752652008, 'text': 'Jesse, When ...",0x86fc95104733adc1:0x94da050d754f90b3
3,1.159089e+20,TR S,1486093061400,4,Flighty service. Great selection.,None,None,0x86fc95104733adc1:0x94da050d754f90b3
4,1.089812e+20,Mannie Myers,1625862764044,4,None,None,None,0x86fc95104733adc1:0x94da050d754f90b3

In [33]:
new_mexico_filtrado = new_mexico.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [34]:
new_mexico_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91188 entries, 0 to 91187
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   user_id  91188 non-null  float64
 1   name     91188 non-null  object
 2   time     91188 non-null  int64
 3   rating   91188 non-null  int64
 4   text     54724 non-null  object
 5   pics     2282 non-null   object
 6   resp     10541 non-null  object
 7   gmap_id  91188 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 5.6+ MB

In [35]:
# Convertir la columna 'time' a datetime
new_mexico_filtrado['time'] = pd.to_datetime(new_mexico_filtrado['time'], unit='ms')

In [36]:
new_mexico_filtrado = new_mexico_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [37]:
new_mexico_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [38]:
new_mexico_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    87101
Name: count, dtype: int64

In [39]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
new_mexico_filtrado.to_csv(os.path.join(ruta_reviews, "32-new_mexico.csv"),index= False)

33-New York

In [40]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-New_York')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            new_york = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(new_york)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id              name           time  rating  \
0        1.137221e+20    Alvin Martinez  1603494795361       5
1        1.072934e+20   Johnnie Jackson  1620157037403       1
2        1.003786e+20      Manie Blazer  1597431662039       5
3        1.149982e+20    Fashion Fiinds  1543773862044       5
4        1.171782e+20    Andres Rieloff  1597279097718       1
...               ...               ...            ...     ...
2699995  1.150888e+20       Gourav Saha  1555437628373       4
2699996  1.117064e+20       jenn mosher  1462985945347       5
2699997  1.083698e+20      Michele Huck  1573877341097       5
2699998  1.007868e+20           Frank B  1603835563283       5
2699999  1.041909e+20  Vincent Viscanti  1561768469200       5

                                                      text  \
0        I'm late to posting this but this store especi...
1        Very dissatisfied I did not get my phone the p...
2        Excellent very well done with professional car...
3        Basing my review strictly on the service I rec...
4        Bad! Disorganized. I'm being totally honest. I...
...                                                    ...
2699995                                               None
2699996                                               None
2699997                                               None
2699998                                               None
2699999                                               None

                                                      pics  \
0        [{'url': ['https://lh5.googleusercontent.com/p...
1                                                     None
2                                                     None
3                                                     None
4                                                     None
...                                                    ...
2699995                                               None
2699996                                               None
2699997                                               None
2699998                                               None
2699999                                               None

                                                      resp  \
0                                                     None
1        {'time': 1620268360920, 'text': 'We pride ours...
2                                                     None
3        {'time': 1543855317372, 'text': 'Thanks for th...
4                                                     None
...                                                    ...
2699995                                               None
2699996                                               None
2699997                                               None
2699998                                               None
2699999                                               None

                                       gmap_id
0          0x89c25fc9494dce47:0x6d63c807b59a55
1          0x89c25fc9494dce47:0x6d63c807b59a55
2          0x89c25fc9494dce47:0x6d63c807b59a55
3          0x89c25fc9494dce47:0x6d63c807b59a55
4          0x89c25fc9494dce47:0x6d63c807b59a55
...                                        ...
2699995  0x89de0b8a0905153d:0x976fc4a006084f03
2699996  0x89de0b8a0905153d:0x976fc4a006084f03
2699997  0x89de0b8a0905153d:0x976fc4a006084f03
2699998  0x89de0b8a0905153d:0x976fc4a006084f03
2699999  0x89de0b8a0905153d:0x976fc4a006084f03

[2700000 rows x 8 columns]

In [41]:
new_york.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.137221e+20,Alvin Martinez,1603494795361,5,I'm late to posting this but this store especi...,[{'url': ['https://lh5.googleusercontent.com/p...,None,0x89c25fc9494dce47:0x6d63c807b59a55
1,1.072934e+20,Johnnie Jackson,1620157037403,1,Very dissatisfied I did not get my phone the p...,None,"{'time': 1620268360920, 'text': 'We pride ours...",0x89c25fc9494dce47:0x6d63c807b59a55
2,1.003786e+20,Manie Blazer,1597431662039,5,Excellent very well done with professional car...,None,None,0x89c25fc9494dce47:0x6d63c807b59a55
3,1.149982e+20,Fashion Fiinds,1543773862044,5,Basing my review strictly on the service I rec...,None,"{'time': 1543855317372, 'text': 'Thanks for th...",0x89c25fc9494dce47:0x6d63c807b59a55
4,1.171782e+20,Andres Rieloff,1597279097718,1,Bad! Disorganized. I'm being totally honest. I...,None,None,0x89c25fc9494dce47:0x6d63c807b59a55

In [42]:
new_york_filtrado = new_york.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [43]:
new_york_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 841654 entries, 0 to 841653
Data columns (total 8 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   user_id  841654 non-null  float64
 1   name     841654 non-null  object
 2   time     841654 non-null  int64
 3   rating   841654 non-null  int64
 4   text     491338 non-null  object
 5   pics     38187 non-null   object
 6   resp     67089 non-null   object
 7   gmap_id  841654 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 51.4+ MB

In [44]:
# Convertir la columna 'time' a datetime
new_york_filtrado['time'] = pd.to_datetime(new_york_filtrado['time'], unit='ms')

In [45]:
new_york_filtrado = new_york_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [46]:
new_york_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [47]:
new_york_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    818915
Name: count, dtype: int64

In [48]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
new_york_filtrado.to_csv(os.path.join(ruta_reviews, "33-new_york.csv"),index= False)

34-North Carolina

In [49]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-North_Carolina')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            north_carolina = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(north_carolina)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id                   name           time  rating  \
0        1.173413e+20          Vicki Pittman  1624283263383       5
1        1.157297e+20          Harley Reaves  1571655539426       5
2        1.115478e+20         JESSICA ALFORD  1590856630354       5
3        1.091106e+20       Tyler Piotrovsky  1577651422743       5
4        1.120391e+20         Frank Bissette  1590252300386       5
...               ...                    ...            ...     ...
2249995  1.148313e+20  Mountainmeshe fitlife  1550314297503       4
2249996  1.052687e+20        Richard MacCrea  1555516468758       5
2249997  1.054112e+20              Cpt Noobz  1566970989601       5
2249998  1.173723e+20            Brenda Manz  1564630572374       4
2249999  1.161267e+20        michelle cordin  1552339397441       5

                                                      text  \
0        Son gets hair cut. Kat is his stylist/barber. ...
1        Really great group of girls! If you have the e...
2        Kat is amazing! My son loves the way she gives...
3        Samantha gave me a perfect cut for me, though ...
4             As always Kat is the greatest stylist ever!!
...                                                    ...
2249995             Very helpful and friendly. Shop local.
2249996            Local business with knowledgable people
2249997                         Best compost in the world!
2249998  Variety of seeds and bulbs for planting and fr...
2249999                             Nice friendly helpers.

                                                      pics  resp  \
0                                                     None  None
1                                                     None  None
2                                                     None  None
3                                                     None  None
4        [{'url': ['https://lh5.googleusercontent.com/p...  None
...                                                    ...   ...
2249995                                               None  None
2249996                                               None  None
2249997                                               None  None
2249998                                               None  None
2249999                                               None  None

                                       gmap_id
0        0x89a911d03136ef51:0xb1c06825101afe51
1        0x89a911d03136ef51:0xb1c06825101afe51
2        0x89a911d03136ef51:0xb1c06825101afe51
3        0x89a911d03136ef51:0xb1c06825101afe51
4        0x89a911d03136ef51:0xb1c06825101afe51
...                                        ...
2249995  0x885ee22896b0566d:0x58d2f0878ba023db
2249996  0x885ee22896b0566d:0x58d2f0878ba023db
2249997  0x885ee22896b0566d:0x58d2f0878ba023db
2249998  0x885ee22896b0566d:0x58d2f0878ba023db
2249999  0x885ee22896b0566d:0x58d2f0878ba023db

[2250000 rows x 8 columns]

In [50]:
north_carolina.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.173413e+20,Vicki Pittman,1624283263383,5,Son gets hair cut. Kat is his stylist/barber. ...,None,None,0x89a911d03136ef51:0xb1c06825101afe51
1,1.157297e+20,Harley Reaves,1571655539426,5,Really great group of girls! If you have the e...,None,None,0x89a911d03136ef51:0xb1c06825101afe51
2,1.115478e+20,JESSICA ALFORD,1590856630354,5,Kat is amazing! My son loves the way she gives...,None,None,0x89a911d03136ef51:0xb1c06825101afe51
3,1.091106e+20,Tyler Piotrovsky,1577651422743,5,"Samantha gave me a perfect cut for me, though ...",None,None,0x89a911d03136ef51:0xb1c06825101afe51
4,1.120391e+20,Frank Bissette,1590252300386,5,As always Kat is the greatest stylist ever!!,[{'url': ['https://lh5.googleusercontent.com/p...,None,0x89a911d03136ef51:0xb1c06825101afe51

In [51]:
north_carolina_filtrado = north_carolina.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [52]:
north_carolina_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 467452 entries, 0 to 467451
Data columns (total 8 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   user_id  467452 non-null  float64
 1   name     467452 non-null  object
 2   time     467452 non-null  int64
 3   rating   467452 non-null  int64
 4   text     279450 non-null  object
 5   pics     14399 non-null   object
 6   resp     58458 non-null   object
 7   gmap_id  467452 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 28.5+ MB

In [53]:
# Convertir la columna 'time' a datetime
north_carolina_filtrado['time'] = pd.to_datetime(north_carolina_filtrado['time'], unit='ms')

In [54]:
north_carolina_filtrado = north_carolina_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [55]:
north_carolina_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [56]:
north_carolina_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    448205
Name: count, dtype: int64

In [57]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
north_carolina_filtrado.to_csv(os.path.join(ruta_reviews, "34-north_carolina.csv"),index= False)

35-North Dakota

In [58]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-North_Dakota')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            north_dakota = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(north_dakota)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

             user_id               name           time  rating  \
0       1.024707e+20       Bryan Miller  1626317971375       5
1       1.022127e+20        Kurt Franke  1612038279541       5
2       1.125204e+20       Amber Moller  1623440198128       5
3       1.133982e+20          Ian Smith  1619722402903       5
4       1.160142e+20  Lilslayerplaez .W  1594748268627       5
...              ...                ...            ...     ...
563688  1.069012e+20         Jon Hanson  1534977144197       5
563689  1.128202e+20     Corey Pederson  1481311648525       4
563690  1.084444e+20       Steven Bayer  1532736972461       5
563691  1.046730e+20       Mykel Sanner  1521256533699       4
563692  1.023970e+20   Natalie Martinez  1530195069314       3

                                                     text  pics  resp  \
0       Fast quick service. I go here almost all the t...  None  None
1       Mike and crew do a great job.  Dropped off veh...  None  None
2                                Amazing love this place!  None  None
3                                 Fair prices speedy work  None  None
4       Always in & out.  Super professional and conve...  None  None
...                                                   ...   ...   ...
563688                                               None  None  None
563689                                               None  None  None
563690                                               None  None  None
563691                                               None  None  None
563692                                               None  None  None

                                      gmap_id
0       0x52d0147640d529bd:0xec9407dc9201780b
1       0x52d0147640d529bd:0xec9407dc9201780b
2       0x52d0147640d529bd:0xec9407dc9201780b
3       0x52d0147640d529bd:0xec9407dc9201780b
4       0x52d0147640d529bd:0xec9407dc9201780b
...                                       ...
563688  0x532126717c175637:0x67f2ed90c51729ed
563689  0x532126717c175637:0x67f2ed90c51729ed
563690  0x532126717c175637:0x67f2ed90c51729ed
563691  0x532126717c175637:0x67f2ed90c51729ed
563692  0x532126717c175637:0x67f2ed90c51729ed

[563693 rows x 8 columns]

In [59]:
north_dakota.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.024707e+20,Bryan Miller,1626317971375,5,Fast quick service. I go here almost all the t...,None,None,0x52d0147640d529bd:0xec9407dc9201780b
1,1.022127e+20,Kurt Franke,1612038279541,5,Mike and crew do a great job. Dropped off veh...,None,None,0x52d0147640d529bd:0xec9407dc9201780b
2,1.125204e+20,Amber Moller,1623440198128,5,Amazing love this place!,None,None,0x52d0147640d529bd:0xec9407dc9201780b
3,1.133982e+20,Ian Smith,1619722402903,5,Fair prices speedy work,None,None,0x52d0147640d529bd:0xec9407dc9201780b
4,1.160142e+20,Lilslayerplaez .W,1594748268627,5,Always in & out. Super professional and conve...,None,None,0x52d0147640d529bd:0xec9407dc9201780b

In [60]:
north_dakota_filtrado = north_dakota.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [61]:
north_dakota_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21788 entries, 0 to 21787
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   user_id  21788 non-null  float64
 1   name     21788 non-null  object
 2   time     21788 non-null  int64
 3   rating   21788 non-null  int64
 4   text     12114 non-null  object
 5   pics     438 non-null    object
 6   resp     2855 non-null   object
 7   gmap_id  21788 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 1.3+ MB

In [62]:
# Convertir la columna 'time' a datetime
north_dakota_filtrado['time'] = pd.to_datetime(north_dakota_filtrado['time'], unit='ms')

In [63]:
north_dakota_filtrado = north_dakota_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [64]:
north_dakota_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [65]:
north_dakota_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    21337
Name: count, dtype: int64

In [66]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
north_dakota_filtrado.to_csv(os.path.join(ruta_reviews, "35-north_dakota.csv"),index= False)

36-Ohio

In [67]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-Ohio')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            ohio = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(ohio)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id                    name           time  rating  \
0        1.147335e+20         Justin Calabris  1584232912307       1
1        1.155461e+20           Benjamin Cope  1487429476527       5
2        1.091146e+20           Jason Hammond  1629077164606       5
3        1.159693e+20                  a Null  1485737926073       2
4        1.138889e+20                Justin F  1499085386882       4
...               ...                     ...            ...     ...
1949995  1.140310e+20            Kelsea Martz  1592011178383       4
1949996  1.003351e+20           Michele Haste  1516480698615       5
1949997  1.094576e+20             Angela Cole  1499181744406       2
1949998  1.046345e+20  Pamela Anderson-Walker  1568165375997       2
1949999  1.028175e+20         Donyetta Bailey  1573701890388       2

                                                      text  pics  \
0                                   I would not recommend.  None
1                    Quality communication and workmanship  None
2                                                     None  None
3                                                     None  None
4                                                     None  None
...                                                    ...   ...
1949995                                Nice park and clean  None
1949996  This Park Was Amazing We Had Our 2017 Family R...  None
1949997  Parking is awful! If they opened the gate on t...  None
1949998                      Dirty. Needs cleaned up. Sad.  None
1949999    It's a baseball field with a mediocre swing set  None

                                                      resp  \
0        {'time': 1606161555458, 'text': 'Justin, I am ...
1                                                     None
2                                                     None
3                                                     None
4                                                     None
...                                                    ...
1949995                                               None
1949996                                               None
1949997                                               None
1949998                                               None
1949999                                               None

                                       gmap_id
0        0x8830cf8574b74559:0x64520f17d5e337dc
1        0x8830cf8574b74559:0x64520f17d5e337dc
2        0x8830cf8574b74559:0x64520f17d5e337dc
3        0x8830cf8574b74559:0x64520f17d5e337dc
4        0x8830cf8574b74559:0x64520f17d5e337dc
...                                        ...
1949995  0x8841ca0e5da6ccab:0x4fbc5e636d94ecc7
1949996  0x8841ca0e5da6ccab:0x4fbc5e636d94ecc7
1949997  0x8841ca0e5da6ccab:0x4fbc5e636d94ecc7
1949998  0x8841ca0e5da6ccab:0x4fbc5e636d94ecc7
1949999  0x8841ca0e5da6ccab:0x4fbc5e636d94ecc7

[1950000 rows x 8 columns]

In [68]:
ohio.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.147335e+20,Justin Calabris,1584232912307,1,I would not recommend.,None,"{'time': 1606161555458, 'text': 'Justin, I am ...",0x8830cf8574b74559:0x64520f17d5e337dc
1,1.155461e+20,Benjamin Cope,1487429476527,5,Quality communication and workmanship,None,None,0x8830cf8574b74559:0x64520f17d5e337dc
2,1.091146e+20,Jason Hammond,1629077164606,5,None,None,None,0x8830cf8574b74559:0x64520f17d5e337dc
3,1.159693e+20,a Null,1485737926073,2,None,None,None,0x8830cf8574b74559:0x64520f17d5e337dc
4,1.138889e+20,Justin F,1499085386882,4,None,None,None,0x8830cf8574b74559:0x64520f17d5e337dc

In [69]:
ohio_filtrado = ohio.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [70]:
ohio_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 479917 entries, 0 to 479916
Data columns (total 8 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   user_id  479917 non-null  float64
 1   name     479917 non-null  object
 2   time     479917 non-null  int64
 3   rating   479917 non-null  int64
 4   text     276363 non-null  object
 5   pics     11531 non-null   object
 6   resp     64478 non-null   object
 7   gmap_id  479917 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 29.3+ MB

In [71]:
# Convertir la columna 'time' a datetime
ohio_filtrado['time'] = pd.to_datetime(ohio_filtrado['time'], unit='ms')

In [72]:
ohio_filtrado = ohio_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [73]:
ohio_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [74]:
ohio_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    463256
Name: count, dtype: int64

In [75]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
ohio_filtrado.to_csv(os.path.join(ruta_reviews, "36-ohio.csv"),index= False)

37-Oklahoma

In [76]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-Oklahoma')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            oklahoma = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(oklahoma)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id                     name           time  rating  \
0        1.089901e+20           Dana Schreiber  1630078007996       5
1        1.138113e+20              Julie Combs  1612485567960       3
2        1.024559e+20                 Regi Glo  1598387347506       5
3        1.037625e+20             Jaimee Steed  1593476994427       5
4        1.164308e+20            Kaylee Miller  1575156563539       1
...               ...                      ...            ...     ...
1649995  1.100951e+20       Terri Lease-Crager  1563804023801       5
1649996  1.047275e+20               kim dollar  1559968571905       5
1649997  1.049320e+20                Kela Tosh  1564177461989       5
1649998  1.045977e+20  David Gutiérrez Álvarez  1538758480240       5
1649999  1.012758e+20             Mery Fuentes  1551399046080       5

                                                      text  pics  \
0        Very knowledgeable, you have a question they k...  None
1        Well they had what I needed but the only  Budt...  None
2        Great place to shop... very helpful and they a...  None
3        Sara is fabulous and super sweet! Lots of choi...  None
4        This place always advertises good deals to get...  None
...                                                    ...   ...
1649995                                               None  None
1649996                                               None  None
1649997                                               None  None
1649998                                               None  None
1649999                                               None  None

                                                      resp  \
0                                                     None
1                                                     None
2        {'time': 1598541936411, 'text': 'Thank you for...
3        {'time': 1593623171971, 'text': 'Thank you so ...
4        {'time': 1579024194534, 'text': 'I completely ...
...                                                    ...
1649995                                               None
1649996                                               None
1649997                                               None
1649998                                               None
1649999                                               None

                                       gmap_id
0        0x87b2695af1ba5c73:0x13084fad93bafbe6
1        0x87b2695af1ba5c73:0x13084fad93bafbe6
2        0x87b2695af1ba5c73:0x13084fad93bafbe6
3        0x87b2695af1ba5c73:0x13084fad93bafbe6
4        0x87b2695af1ba5c73:0x13084fad93bafbe6
...                                        ...
1649995  0x87b6eb9a4c7f0449:0x614aa95b17c43371
1649996  0x87b6eb9a4c7f0449:0x614aa95b17c43371
1649997  0x87b6eb9a4c7f0449:0x614aa95b17c43371
1649998  0x87b6eb9a4c7f0449:0x614aa95b17c43371
1649999  0x87b6eb9a4c7f0449:0x614aa95b17c43371

[1650000 rows x 8 columns]

In [77]:
oklahoma.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.089901e+20,Dana Schreiber,1630078007996,5,"Very knowledgeable, you have a question they k...",None,None,0x87b2695af1ba5c73:0x13084fad93bafbe6
1,1.138113e+20,Julie Combs,1612485567960,3,Well they had what I needed but the only Budt...,None,None,0x87b2695af1ba5c73:0x13084fad93bafbe6
2,1.024559e+20,Regi Glo,1598387347506,5,Great place to shop... very helpful and they a...,None,"{'time': 1598541936411, 'text': 'Thank you for...",0x87b2695af1ba5c73:0x13084fad93bafbe6
3,1.037625e+20,Jaimee Steed,1593476994427,5,Sara is fabulous and super sweet! Lots of choi...,None,"{'time': 1593623171971, 'text': 'Thank you so ...",0x87b2695af1ba5c73:0x13084fad93bafbe6
4,1.164308e+20,Kaylee Miller,1575156563539,1,This place always advertises good deals to get...,None,"{'time': 1579024194534, 'text': 'I completely ...",0x87b2695af1ba5c73:0x13084fad93bafbe6

In [78]:
oklahoma_filtrado = oklahoma.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [79]:
oklahoma_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169510 entries, 0 to 169509
Data columns (total 8 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   user_id  169510 non-null  float64
 1   name     169510 non-null  object
 2   time     169510 non-null  int64
 3   rating   169510 non-null  int64
 4   text     100803 non-null  object
 5   pics     4529 non-null    object
 6   resp     15388 non-null   object
 7   gmap_id  169510 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 10.3+ MB

In [80]:
# Convertir la columna 'time' a datetime
oklahoma_filtrado['time'] = pd.to_datetime(oklahoma_filtrado['time'], unit='ms')

In [81]:
oklahoma_filtrado = oklahoma_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [82]:
oklahoma_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [83]:
oklahoma_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    163373
Name: count, dtype: int64

In [84]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
oklahoma_filtrado.to_csv(os.path.join(ruta_reviews, "37-oklahoma.csv"),index= False)

38-Oregon

In [85]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-Oregon')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            oregon = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(oregon)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id               name           time  rating  \
0        1.162386e+20          Mike Alan  1607013385211       5
1        1.169888e+20   Jennifer Zumwalt  1607571121183       5
2        1.180039e+20  Courtney Saunders  1582762237754       5
3        1.180039e+20  Courtney Saunders  1582762237754       5
4        1.030973e+20       Becky proulx  1584064731306       5
...               ...                ...            ...     ...
2249995  1.045023e+20        Darla Price  1504072290277       5
2249996  1.120197e+20        Sasha Rippy  1490599536783       5
2249997  1.179433e+20     Thomas Leseman  1526065458310       5
2249998  1.125457e+20      Lucas heineck  1513227280077       5
2249999  1.153863e+20         Jody Cupps  1484311985020       5

                                                      text  pics  \
0        Every staff member in this office is absolutel...  None
1        They are amazing. Always so kinda and helpful....  None
2        With three kids and myself, our family has bee...  None
3        With three kids and myself, our family has bee...  None
4        Three of our children have received their brac...  None
...                                                    ...   ...
2249995  Awesome, quick in and out access, nice selecti...  None
2249996          The best beer selection I have ever seen!  None
2249997  Largest beer and wine selection in Salem! And ...  None
2249998                  Just a quick stop.. all went well  None
2249999          Very nice and clean. clean very organized  None

                                                      resp  \
0                                                     None
1                                                     None
2        {'time': 1599964077016, 'text': 'It has been g...
3        {'time': 1599964077016, 'text': 'It has been g...
4        {'time': 1599961987996, 'text': 'I am glad you...
...                                                    ...
2249995                                               None
2249996                                               None
2249997                                               None
2249998                                               None
2249999                                               None

                                       gmap_id
0        0x54bfff5952aad583:0xad7afdc825730614
1        0x54bfff5952aad583:0xad7afdc825730614
2        0x54bfff5952aad583:0xad7afdc825730614
3        0x54bfff5952aad583:0xad7afdc825730614
4        0x54bfff5952aad583:0xad7afdc825730614
...                                        ...
2249995  0x54bfff1677c2433f:0x9b218e18e39e82c2
2249996  0x54bfff1677c2433f:0x9b218e18e39e82c2
2249997  0x54bfff1677c2433f:0x9b218e18e39e82c2
2249998  0x54bfff1677c2433f:0x9b218e18e39e82c2
2249999  0x54bfff1677c2433f:0x9b218e18e39e82c2

[2250000 rows x 8 columns]

In [86]:
oregon.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.162386e+20,Mike Alan,1607013385211,5,Every staff member in this office is absolutel...,None,None,0x54bfff5952aad583:0xad7afdc825730614
1,1.169888e+20,Jennifer Zumwalt,1607571121183,5,They are amazing. Always so kinda and helpful....,None,None,0x54bfff5952aad583:0xad7afdc825730614
2,1.180039e+20,Courtney Saunders,1582762237754,5,"With three kids and myself, our family has bee...",None,"{'time': 1599964077016, 'text': 'It has been g...",0x54bfff5952aad583:0xad7afdc825730614
3,1.180039e+20,Courtney Saunders,1582762237754,5,"With three kids and myself, our family has bee...",None,"{'time': 1599964077016, 'text': 'It has been g...",0x54bfff5952aad583:0xad7afdc825730614
4,1.030973e+20,Becky proulx,1584064731306,5,Three of our children have received their brac...,None,"{'time': 1599961987996, 'text': 'I am glad you...",0x54bfff5952aad583:0xad7afdc825730614

In [87]:
oregon_filtrado = oregon.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [88]:
oregon_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 216500 entries, 0 to 216499
Data columns (total 8 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   user_id  216500 non-null  float64
 1   name     216500 non-null  object
 2   time     216500 non-null  int64
 3   rating   216500 non-null  int64
 4   text     134454 non-null  object
 5   pics     8176 non-null    object
 6   resp     18570 non-null   object
 7   gmap_id  216500 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 13.2+ MB

In [89]:
# Convertir la columna 'time' a datetime
oregon_filtrado['time'] = pd.to_datetime(oregon_filtrado['time'], unit='ms')

In [90]:
oregon_filtrado = oregon_filtrado[["user_id","name","time","rating","text","resp","gmap_id"]]

In [91]:
oregon_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [92]:
oregon_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    207890
Name: count, dtype: int64

In [93]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
oregon_filtrado.to_csv(os.path.join(ruta_reviews, "38-oregon.csv"),index= False)

39-Pennsylvania

In [94]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-Pennsylvania')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            pennsylvania = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(pennsylvania)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id               name           time  rating  \
0        1.049447e+20    Jaron Whitfield  1517731762839       5
1        1.176097e+20  Jonathan McCarthy  1476276291163       5
2        1.105632e+20          Rocky Kev  1338826945578       5
3        1.128960e+20        Josep Valls  1363286110554       5
4        1.106197e+20     Timaree Schmit  1548798329760       5
...               ...                ...            ...     ...
2399995  1.091214e+20        Aileen Blas  1617621797453       5
2399996  1.078737e+20        Joshua Juda  1604013876755       4
2399997  1.072232e+20      Anthony Casto  1614576293981       5
2399998  1.058429e+20      Mark McKillop  1611092631663       5
2399999  1.013187e+20        Shawn Smith  1582499834928       5

                                                      text  \
0        Joe is quite unique of his line of work, he as...
1        For such a small place their impact on my life...
2        I usually give them a call before I stop by to...
3        My bike had been sitting outdoors for a good w...
4        Always an easy experience. Service is knowledg...
...                                                    ...
2399995  Great cookies, wonderful staff.  Very enjoyabl...
2399996  Good fresh baked cookies. Prices are a little ...
2399997                                  Best cookies ever
2399998  Great place for a snack. Open really late and ...
2399999  Who doesn't love a walk in cookie store that h...

                                                      pics  resp  \
0                                                     None  None
1                                                     None  None
2                                                     None  None
3                                                     None  None
4                                                     None  None
...                                                    ...   ...
2399995                                               None  None
2399996                                               None  None
2399997  [{'url': ['https://lh5.googleusercontent.com/p...  None
2399998                                               None  None
2399999                                               None  None

                                       gmap_id
0        0x89c6c63c8cd87141:0x54d0d283872eecbb
1        0x89c6c63c8cd87141:0x54d0d283872eecbb
2        0x89c6c63c8cd87141:0x54d0d283872eecbb
3        0x89c6c63c8cd87141:0x54d0d283872eecbb
4        0x89c6c63c8cd87141:0x54d0d283872eecbb
...                                        ...
2399995  0x89cb5b2714dfeecf:0xe4f25ae9daa774ff
2399996  0x89cb5b2714dfeecf:0xe4f25ae9daa774ff
2399997  0x89cb5b2714dfeecf:0xe4f25ae9daa774ff
2399998  0x89cb5b2714dfeecf:0xe4f25ae9daa774ff
2399999  0x89cb5b2714dfeecf:0xe4f25ae9daa774ff

[2400000 rows x 8 columns]

In [95]:
pennsylvania.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.049447e+20,Jaron Whitfield,1517731762839,5,"Joe is quite unique of his line of work, he as...",None,None,0x89c6c63c8cd87141:0x54d0d283872eecbb
1,1.176097e+20,Jonathan McCarthy,1476276291163,5,For such a small place their impact on my life...,None,None,0x89c6c63c8cd87141:0x54d0d283872eecbb
2,1.105632e+20,Rocky Kev,1338826945578,5,I usually give them a call before I stop by to...,None,None,0x89c6c63c8cd87141:0x54d0d283872eecbb
3,1.128960e+20,Josep Valls,1363286110554,5,My bike had been sitting outdoors for a good w...,None,None,0x89c6c63c8cd87141:0x54d0d283872eecbb
4,1.106197e+20,Timaree Schmit,1548798329760,5,Always an easy experience. Service is knowledg...,None,None,0x89c6c63c8cd87141:0x54d0d283872eecbb

In [96]:
pennsylvania_filtrado = pennsylvania.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [97]:
pennsylvania_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 468934 entries, 0 to 468933
Data columns (total 8 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   user_id  468934 non-null  float64
 1   name     468934 non-null  object
 2   time     468934 non-null  int64
 3   rating   468934 non-null  int64
 4   text     277386 non-null  object
 5   pics     12927 non-null   object
 6   resp     48163 non-null   object
 7   gmap_id  468934 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 28.6+ MB

In [98]:
# Convertir la columna 'time' a datetime
pennsylvania_filtrado['time'] = pd.to_datetime(pennsylvania_filtrado['time'], unit='ms')

In [99]:
pennsylvania_filtrado = pennsylvania_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [100]:
pennsylvania_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [101]:
pennsylvania_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    456357
Name: count, dtype: int64

In [102]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
pennsylvania_filtrado.to_csv(os.path.join(ruta_reviews, "39-pennsylvania.csv"),index= False)

40-Rhode Island

In [103]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-Rhode_Island')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            rhode_island = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(rhode_island)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

             user_id                  name           time  rating  \
0       1.079069e+20           Rubia Bella  1601590520320       5
1       1.167350e+20       angel olivencia  1602983693555       4
2       1.057469e+20       Daniel Reggiani  1603064156784       5
3       1.167282e+20  Joseph “Joe” Solomon  1600710962505       5
4       1.113063e+20        Julio Robinson  1601408236165       5
...              ...                   ...            ...     ...
890001  1.105587e+20           Brian Logan  1599414863011       5
890002  1.141279e+20      Victor Dossantos  1591578809036       5
890003  1.090841e+20         Jeffrey Moten  1533210480907       5
890004  1.172675e+20             Geoff Zub  1557665127379       5
890005  1.175959e+20        Manuel Atencio  1560732773655       5

                                       text  pics  \
0       Very good! Will eat here again! ☺️😍  None
1                Not bad place... good food  None
2                          Really good food  None
3                     Great people and food  None
4                                      None  None
...                                     ...   ...
890001                                 None  None
890002                                 None  None
890003                                 None  None
890004                                 None  None
890005                                 None  None

                                                     resp  \
0       {'time': 1602371857761, 'text': 'Hope to see y...
1                                                    None
2                                                    None
3       {'time': 1602371881382, 'text': 'Thanks for th...
4                   {'time': 1602371865572, 'text': '🙏🏼'}
...                                                   ...
890001                                               None
890002                                               None
890003                                               None
890004                                               None
890005                                               None

                                      gmap_id
0       0x89e44fe1c2a2a2c3:0x5fc9f6751fb29737
1       0x89e44fe1c2a2a2c3:0x5fc9f6751fb29737
2       0x89e44fe1c2a2a2c3:0x5fc9f6751fb29737
3       0x89e44fe1c2a2a2c3:0x5fc9f6751fb29737
4       0x89e44fe1c2a2a2c3:0x5fc9f6751fb29737
...                                       ...
890001  0x89e445186950d54f:0xef05d379019eaed4
890002  0x89e445186950d54f:0xef05d379019eaed4
890003  0x89e445186950d54f:0xef05d379019eaed4
890004  0x89e445186950d54f:0xef05d379019eaed4
890005  0x89e445186950d54f:0xef05d379019eaed4

[890006 rows x 8 columns]

In [104]:
rhode_island.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.079069e+20,Rubia Bella,1601590520320,5,Very good! Will eat here again! ☺️😍,None,"{'time': 1602371857761, 'text': 'Hope to see y...",0x89e44fe1c2a2a2c3:0x5fc9f6751fb29737
1,1.167350e+20,angel olivencia,1602983693555,4,Not bad place... good food,None,None,0x89e44fe1c2a2a2c3:0x5fc9f6751fb29737
2,1.057469e+20,Daniel Reggiani,1603064156784,5,Really good food,None,None,0x89e44fe1c2a2a2c3:0x5fc9f6751fb29737
3,1.167282e+20,Joseph “Joe” Solomon,1600710962505,5,Great people and food,None,"{'time': 1602371881382, 'text': 'Thanks for th...",0x89e44fe1c2a2a2c3:0x5fc9f6751fb29737
4,1.113063e+20,Julio Robinson,1601408236165,5,None,None,"{'time': 1602371865572, 'text': '🙏🏼'}",0x89e44fe1c2a2a2c3:0x5fc9f6751fb29737

In [105]:
rhode_island_filtrado = rhode_island.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [106]:
rhode_island_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49583 entries, 0 to 49582
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   user_id  49583 non-null  float64
 1   name     49583 non-null  object
 2   time     49583 non-null  int64
 3   rating   49583 non-null  int64
 4   text     28454 non-null  object
 5   pics     1383 non-null   object
 6   resp     3636 non-null   object
 7   gmap_id  49583 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 3.0+ MB

In [107]:
# Convertir la columna 'time' a datetime
rhode_island_filtrado['time'] = pd.to_datetime(rhode_island_filtrado['time'], unit='ms')

In [108]:
rhode_island_filtrado = rhode_island_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [109]:
rhode_island_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [110]:
rhode_island_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    48037
Name: count, dtype: int64

In [111]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
rhode_island_filtrado.to_csv(os.path.join(ruta_reviews, "40-rhode_island.csv"),index= False)

41- South Carolina

In [112]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-South_Carolina')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            south_carolina = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(south_carolina)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id               name           time  rating  \
0        1.089900e+20       Pamela Poole  1611327187871       4
1        1.157870e+20    Cleveland Grant  1520462369713       5
2        1.009543e+20         Sean Smith  1492902201253       5
3        1.177168e+20    ThunderStroke91  1509505441582       5
4        1.030620e+20      Joshua Tongue  1578438229754       5
...               ...                ...            ...     ...
2099995  1.075432e+20  Mitchell Thrasher  1580302707587       5
2099996  1.012773e+20       Sara Hopkins  1557445312077       5
2099997  1.177628e+20      Moira Bullard  1554832871503       5
2099998  1.075647e+20       Chris Belshe  1564784807900       3
2099999  1.062370e+20       Perry Bolick  1549498165182       5

                                                      text  \
0        They were very informative  about  the product...
1        Great Gun Shop!!! Best local shop you will fin...
2        Met Jr and Cathy today at the gun show in Gree...
3        Big variety, they've got what you need. They a...
4                                                     None
...                                                    ...
2099995                                               None
2099996                                               None
2099997                                               None
2099998                                               None
2099999                                               None

                                                      pics  resp  \
0                                                     None  None
1        [{'url': ['https://lh5.googleusercontent.com/p...  None
2                                                     None  None
3                                                     None  None
4                                                     None  None
...                                                    ...   ...
2099995                                               None  None
2099996                                               None  None
2099997                                               None  None
2099998                                               None  None
2099999                                               None  None

                                       gmap_id
0        0x8856e3dd768d3649:0xb38593eb55374673
1        0x8856e3dd768d3649:0xb38593eb55374673
2        0x8856e3dd768d3649:0xb38593eb55374673
3        0x8856e3dd768d3649:0xb38593eb55374673
4        0x8856e3dd768d3649:0xb38593eb55374673
...                                        ...
2099995  0x8858294f459c3f31:0x964f8890cdb80343
2099996  0x8858294f459c3f31:0x964f8890cdb80343
2099997  0x8858294f459c3f31:0x964f8890cdb80343
2099998  0x8858294f459c3f31:0x964f8890cdb80343
2099999  0x8858294f459c3f31:0x964f8890cdb80343

[2100000 rows x 8 columns]

In [113]:
south_carolina.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.089900e+20,Pamela Poole,1611327187871,4,They were very informative about the product...,None,None,0x8856e3dd768d3649:0xb38593eb55374673
1,1.157870e+20,Cleveland Grant,1520462369713,5,Great Gun Shop!!! Best local shop you will fin...,[{'url': ['https://lh5.googleusercontent.com/p...,None,0x8856e3dd768d3649:0xb38593eb55374673
2,1.009543e+20,Sean Smith,1492902201253,5,Met Jr and Cathy today at the gun show in Gree...,None,None,0x8856e3dd768d3649:0xb38593eb55374673
3,1.177168e+20,ThunderStroke91,1509505441582,5,"Big variety, they've got what you need. They a...",None,None,0x8856e3dd768d3649:0xb38593eb55374673
4,1.030620e+20,Joshua Tongue,1578438229754,5,None,None,None,0x8856e3dd768d3649:0xb38593eb55374673

In [114]:
south_carolina_filtrado = south_carolina.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [115]:
south_carolina_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 255226 entries, 0 to 255225
Data columns (total 8 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   user_id  255226 non-null  float64
 1   name     255226 non-null  object
 2   time     255226 non-null  int64
 3   rating   255226 non-null  int64
 4   text     153821 non-null  object
 5   pics     7696 non-null    object
 6   resp     28582 non-null   object
 7   gmap_id  255226 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 15.6+ MB

In [116]:
# Convertir la columna 'time' a datetime
south_carolina_filtrado['time'] = pd.to_datetime(south_carolina_filtrado['time'], unit='ms')

In [117]:
south_carolina_filtrado = south_carolina_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [118]:
south_carolina_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [119]:
south_carolina_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    243113
Name: count, dtype: int64

In [120]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
south_carolina_filtrado.to_csv(os.path.join(ruta_reviews, "41-south_carolina.csv"),index= False)

42- South Dakota

In [121]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-South_Dakota')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            south_dakota = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(south_dakota)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

             user_id               name           time  rating  \
0       1.035634e+20          Peri Gray  1516122675780       5
1       1.018250e+20        Suzy Berndt  1532922350314       5
2       1.087116e+20  Rosemary Red Legs  1530969093932       5
3       1.018523e+20         Brown Wolf  1537085635922       2
4       1.089874e+20      C J Blue Coat  1474922375491       5
...              ...                ...            ...     ...
673043  1.063497e+20            Peggy M  1541553943539       5
673044  1.111324e+20  Gabrielle Strouse  1465971016069       2
673045  1.125993e+20   Where's The 10mm  1439839859315       5
673046  1.042896e+20         A J Rausch  1534031130311       5
673047  1.112594e+20                D B  1542421998790       5

                                         text  pics  resp  \
0       Great place to care for our children.  None  None
1                         Th sw y are so nice  None  None
2                       Went with my daughter  None  None
3                                        None  None  None
4                                        None  None  None
...                                       ...   ...   ...
673043                                   None  None  None
673044                                   None  None  None
673045                                   None  None  None
673046                                   None  None  None
673047                                   None  None  None

                                      gmap_id
0       0x532af45db8f30779:0xd9be9359f1e56178
1       0x532af45db8f30779:0xd9be9359f1e56178
2       0x532af45db8f30779:0xd9be9359f1e56178
3       0x532af45db8f30779:0xd9be9359f1e56178
4       0x532af45db8f30779:0xd9be9359f1e56178
...                                       ...
673043  0x877d4b3beecb809d:0xc8750c627d73a316
673044  0x877d4b3beecb809d:0xc8750c627d73a316
673045  0x877d4b3beecb809d:0xc8750c627d73a316
673046  0x877d4b3beecb809d:0xc8750c627d73a316
673047  0x877d4b3beecb809d:0xc8750c627d73a316

[673048 rows x 8 columns]

In [122]:
south_dakota.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.035634e+20,Peri Gray,1516122675780,5,Great place to care for our children.,None,None,0x532af45db8f30779:0xd9be9359f1e56178
1,1.018250e+20,Suzy Berndt,1532922350314,5,Th sw y are so nice,None,None,0x532af45db8f30779:0xd9be9359f1e56178
2,1.087116e+20,Rosemary Red Legs,1530969093932,5,Went with my daughter,None,None,0x532af45db8f30779:0xd9be9359f1e56178
3,1.018523e+20,Brown Wolf,1537085635922,2,None,None,None,0x532af45db8f30779:0xd9be9359f1e56178
4,1.089874e+20,C J Blue Coat,1474922375491,5,None,None,None,0x532af45db8f30779:0xd9be9359f1e56178

In [123]:
south_dakota_filtrado = south_dakota.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [124]:
south_dakota_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27252 entries, 0 to 27251
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   user_id  27252 non-null  float64
 1   name     27252 non-null  object
 2   time     27252 non-null  int64
 3   rating   27252 non-null  int64
 4   text     14973 non-null  object
 5   pics     592 non-null    object
 6   resp     2787 non-null   object
 7   gmap_id  27252 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 1.7+ MB

In [125]:
# Convertir la columna 'time' a datetime
south_dakota_filtrado['time'] = pd.to_datetime(south_dakota_filtrado['time'], unit='ms')

In [126]:
south_dakota_filtrado = south_dakota_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [127]:
south_dakota_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [128]:
south_dakota_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    26465
Name: count, dtype: int64

In [129]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
south_dakota_filtrado.to_csv(os.path.join(ruta_reviews, "42-south_dakota.csv"),index= False)

43- Tennessee

In [130]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-Tennessee')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            tennessee = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(tennessee)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id            name           time  rating  \
0        1.182884e+20     Ally Medina  1567349037857       1
1        1.130847e+20    Nikki Thomas  1476897445568       5
2        1.006869e+20   Michael Wahba  1574100089433       5
3        1.005480e+20     DaiJa Ricks  1535731263264       5
4        1.059574e+20  Lydia Thompson  1554665980076       5
...               ...             ...            ...     ...
1799995  1.009729e+20    T Tamburello  1590778554189       5
1799996  1.043551e+20      Arleen Lee  1508459784726       5
1799997  1.092016e+20    Carma Cartel  1570847532945       5
1799998  1.038258e+20    Dale Rickman  1564141792272       5
1799999  1.179981e+20       Kyle Just  1564033263730       1

                                                      text  \
0        I have been taking my daughter here since 2015...
1        We switched from Dr.Henschel at Tennessee Pedi...
2        The doctors and nurses and all staff are reall...
3        My children have been patients at this office ...
4        Dr. Haselton is great, my boys have seen her f...
...                                                    ...
1799995                                               None
1799996                                               None
1799997                                               None
1799998                                               None
1799999  Worst place to live without a doubt. They can ...

                                                      pics  \
0                                                     None
1                                                     None
2                                                     None
3                                                     None
4                                                     None
...                                                    ...
1799995                                               None
1799996                                               None
1799997                                               None
1799998                                               None
1799999  [{'url': ['https://lh5.googleusercontent.com/p...

                                                      resp  \
0        {'time': 1567368090513, 'text': 'All of the pr...
1                                                     None
2                                                     None
3                                                     None
4                                                     None
...                                                    ...
1799995                                               None
1799996                                               None
1799997                                               None
1799998                                               None
1799999  {'time': 1545927982923, 'text': 'Kyle, Thank y...

                                       gmap_id
0        0x88640cea7d985e0b:0xf214c6bf1d01be6c
1        0x88640cea7d985e0b:0xf214c6bf1d01be6c
2        0x88640cea7d985e0b:0xf214c6bf1d01be6c
3        0x88640cea7d985e0b:0xf214c6bf1d01be6c
4        0x88640cea7d985e0b:0xf214c6bf1d01be6c
...                                        ...
1799995  0x88605bc0a437a5f7:0x64832df1a0324614
1799996  0x88605bc0a437a5f7:0x64832df1a0324614
1799997  0x88605bc0a437a5f7:0x64832df1a0324614
1799998  0x88605bc0a437a5f7:0x64832df1a0324614
1799999  0x88606332b0a09855:0x11719050227835b2

[1800000 rows x 8 columns]

In [131]:
tennessee.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.182884e+20,Ally Medina,1567349037857,1,I have been taking my daughter here since 2015...,None,"{'time': 1567368090513, 'text': 'All of the pr...",0x88640cea7d985e0b:0xf214c6bf1d01be6c
1,1.130847e+20,Nikki Thomas,1476897445568,5,We switched from Dr.Henschel at Tennessee Pedi...,None,None,0x88640cea7d985e0b:0xf214c6bf1d01be6c
2,1.006869e+20,Michael Wahba,1574100089433,5,The doctors and nurses and all staff are reall...,None,None,0x88640cea7d985e0b:0xf214c6bf1d01be6c
3,1.005480e+20,DaiJa Ricks,1535731263264,5,My children have been patients at this office ...,None,None,0x88640cea7d985e0b:0xf214c6bf1d01be6c
4,1.059574e+20,Lydia Thompson,1554665980076,5,"Dr. Haselton is great, my boys have seen her f...",None,None,0x88640cea7d985e0b:0xf214c6bf1d01be6c

In [133]:
tennessee_filtrado = tennessee.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [134]:
tennessee_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307297 entries, 0 to 307296
Data columns (total 8 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   user_id  307297 non-null  float64
 1   name     307297 non-null  object
 2   time     307297 non-null  int64
 3   rating   307297 non-null  int64
 4   text     184386 non-null  object
 5   pics     9400 non-null    object
 6   resp     38807 non-null   object
 7   gmap_id  307297 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 18.8+ MB

In [135]:
# Convertir la columna 'time' a datetime
tennessee_filtrado['time'] = pd.to_datetime(tennessee_filtrado['time'], unit='ms')

In [136]:
tennessee_filtrado = tennessee_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [137]:
tennessee_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [138]:
tennessee_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    293712
Name: count, dtype: int64

In [139]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
tennessee_filtrado.to_csv(os.path.join(ruta_reviews, "43-tennessee.csv"),index= False)

44-Texas

In [140]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-Texas')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            texas = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(texas)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id              name           time  rating  \
0        1.105453e+20    Kimberly Feger  1625431734826       5
1        1.036198e+20     Briana Streit  1568336283913       2
2        1.019167e+20   Sylvia Caudillo  1519873586872       1
3        1.178709e+20     Ginger Kinyon  1571638384637       1
4        1.103973e+20  Angeles Arellano  1546568877087       1
...               ...               ...            ...     ...
2296819  1.021681e+20        t williams  1562883151018       5
2296820  1.054173e+20        Erika Lira  1532009672494       5
2296821  1.107857e+20         Jon Brent  1567968578697       5
2296822  1.091676e+20       lunna cabal  1506476840285       4
2296823  1.012701e+20   Michelle Torres  1555551049893       5

                                                      text  pics  resp  \
0        The pharmacist, Erin, is phenomenal. She was s...  None  None
1        I gave them 2 stars because they offer prescri...  None  None
2        If I could put minus stars I would. This has t...  None  None
3                           Please fix your restroom doors  None  None
4        This pharmacy Walmart dose not work not come a...  None  None
...                                                    ...   ...   ...
2296819                                               None  None  None
2296820                                               None  None  None
2296821                                               None  None  None
2296822                                               None  None  None
2296823                                               None  None  None

                                       gmap_id
0        0x864c3998b8d8dc83:0x57ffabe1e2322320
1        0x864c3998b8d8dc83:0x57ffabe1e2322320
2        0x864c3998b8d8dc83:0x57ffabe1e2322320
3        0x864c3998b8d8dc83:0x57ffabe1e2322320
4        0x864c3998b8d8dc83:0x57ffabe1e2322320
...                                        ...
2296819  0x8640d215ff1e43e5:0xaeeb5211a25191f4
2296820  0x8640d215ff1e43e5:0xaeeb5211a25191f4
2296821  0x8640d215ff1e43e5:0xaeeb5211a25191f4
2296822  0x8640d215ff1e43e5:0xaeeb5211a25191f4
2296823  0x8640d215ff1e43e5:0xaeeb5211a25191f4

[2296824 rows x 8 columns]

In [141]:
texas.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.105453e+20,Kimberly Feger,1625431734826,5,"The pharmacist, Erin, is phenomenal. She was s...",None,None,0x864c3998b8d8dc83:0x57ffabe1e2322320
1,1.036198e+20,Briana Streit,1568336283913,2,I gave them 2 stars because they offer prescri...,None,None,0x864c3998b8d8dc83:0x57ffabe1e2322320
2,1.019167e+20,Sylvia Caudillo,1519873586872,1,If I could put minus stars I would. This has t...,None,None,0x864c3998b8d8dc83:0x57ffabe1e2322320
3,1.178709e+20,Ginger Kinyon,1571638384637,1,Please fix your restroom doors,None,None,0x864c3998b8d8dc83:0x57ffabe1e2322320
4,1.103973e+20,Angeles Arellano,1546568877087,1,This pharmacy Walmart dose not work not come a...,None,None,0x864c3998b8d8dc83:0x57ffabe1e2322320

In [142]:
texas_filtrado = texas.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [143]:
texas_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 605013 entries, 0 to 605012
Data columns (total 8 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   user_id  605013 non-null  float64
 1   name     605013 non-null  object
 2   time     605013 non-null  int64
 3   rating   605013 non-null  int64
 4   text     360170 non-null  object
 5   pics     23359 non-null   object
 6   resp     77490 non-null   object
 7   gmap_id  605013 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 36.9+ MB

In [144]:
# Convertir la columna 'time' a datetime
texas_filtrado['time'] = pd.to_datetime(texas_filtrado['time'], unit='ms')

In [145]:
texas_filtrado = texas_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [146]:
texas_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [147]:
texas_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    577645
Name: count, dtype: int64

In [148]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
texas_filtrado.to_csv(os.path.join(ruta_reviews, "44-texas.csv"),index= False)

45-Utah

In [149]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-Utah')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            utah = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(utah)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id              name           time  rating  \
0        1.111826e+20        Liz W Poch  1627085008811       5
1        1.176892e+20  Mario D'Ambrosio  1626437133578       1
2        1.158347e+20   Kathleen Hambly  1585165423975       5
3        1.126796e+20     Crystal Olsen  1591629458998       1
4        1.085994e+20      Sarah Jensen  1510264647735       5
...               ...               ...            ...     ...
1499995  1.074057e+20     justin kargis  1560026378916       5
1499996  1.090164e+20             Ash E  1544633928924       5
1499997  1.066894e+20     Marisa Cannon  1549267391378       4
1499998  1.144290e+20      Ali Houghton  1564862963159       5
1499999  1.040441e+20     Codie Bennett  1559361628322       4

                                                      text  pics  \
0        Paige is the best! Everyone at this branch is ...  None
1        I have updated my systems on two titles for ca...  None
2        Simone is the best. She helped me to defer my ...  None
3        Ive called several times and there customer se...  None
4        My fiance and I had an awesome stress-free exp...  None
...                                                    ...   ...
1499995  Friendly service and efficient. They did a gre...  None
1499996  The food is a little expensive, but you do get...  None
1499997  I love nekter! They use a lot of gluten free a...  None
1499998             I LOVE NECTER. Best acai bowls around.  None
1499999  Yummy! You can never go wrong with an açaí bow...  None

                                                      resp  \
0                                                     None
1                                                     None
2                                                     None
3                                                     None
4        {'time': 1514404059776, 'text': 'Thank you for...
...                                                    ...
1499995  {'time': 1619483568326, 'text': 'We are now op...
1499996                                               None
1499997  {'time': 1619485140225, 'text': 'hi Marisa!
Pl...
1499998  {'time': 1619483174113, 'text': 'Thank you Ali...
1499999  {'time': 1619484924709, 'text': 'Hi Codie!
Ple...

                                       gmap_id
0        0x87528767d0ec0e4d:0x7a2f1637a6fb6925
1        0x87528767d0ec0e4d:0x7a2f1637a6fb6925
2        0x87528767d0ec0e4d:0x7a2f1637a6fb6925
3        0x87528767d0ec0e4d:0x7a2f1637a6fb6925
4        0x87528767d0ec0e4d:0x7a2f1637a6fb6925
...                                        ...
1499995  0x8752802156c9c84b:0xd80b37abfef5c319
1499996  0x8752802156c9c84b:0xd80b37abfef5c319
1499997  0x8752802156c9c84b:0xd80b37abfef5c319
1499998  0x8752802156c9c84b:0xd80b37abfef5c319
1499999  0x8752802156c9c84b:0xd80b37abfef5c319

[1500000 rows x 8 columns]

In [150]:
utah.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.111826e+20,Liz W Poch,1627085008811,5,Paige is the best! Everyone at this branch is ...,None,None,0x87528767d0ec0e4d:0x7a2f1637a6fb6925
1,1.176892e+20,Mario D'Ambrosio,1626437133578,1,I have updated my systems on two titles for ca...,None,None,0x87528767d0ec0e4d:0x7a2f1637a6fb6925
2,1.158347e+20,Kathleen Hambly,1585165423975,5,Simone is the best. She helped me to defer my ...,None,None,0x87528767d0ec0e4d:0x7a2f1637a6fb6925
3,1.126796e+20,Crystal Olsen,1591629458998,1,Ive called several times and there customer se...,None,None,0x87528767d0ec0e4d:0x7a2f1637a6fb6925
4,1.085994e+20,Sarah Jensen,1510264647735,5,My fiance and I had an awesome stress-free exp...,None,"{'time': 1514404059776, 'text': 'Thank you for...",0x87528767d0ec0e4d:0x7a2f1637a6fb6925

In [151]:
utah_filtrado = utah.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [152]:
utah_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200817 entries, 0 to 200816
Data columns (total 8 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   user_id  200817 non-null  float64
 1   name     200817 non-null  object
 2   time     200817 non-null  int64
 3   rating   200817 non-null  int64
 4   text     127201 non-null  object
 5   pics     6698 non-null    object
 6   resp     29846 non-null   object
 7   gmap_id  200817 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 12.3+ MB

In [153]:
# Convertir la columna 'time' a datetime
utah_filtrado['time'] = pd.to_datetime(utah_filtrado['time'], unit='ms')

In [154]:
utah_filtrado = utah_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [155]:
utah_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [156]:
utah_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    190020
Name: count, dtype: int64

In [157]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
utah_filtrado.to_csv(os.path.join(ruta_reviews, "45-utah.csv"),index= False)

46-Vermont

In [158]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-Vermont')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            vermont = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(vermont)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

             user_id             name           time  rating  \
0       1.180269e+20    rebecca kerns  1620085852324       5
1       1.015327e+20    Peter DeForge  1580309946474       5
2       1.154041e+20    Chad Goulette  1605195974445       5
3       1.047893e+20  Mark LaFountain  1593005848256       5
4       1.089807e+20           Jeff R  1582059996120       5
...              ...              ...            ...     ...
324720  1.026044e+20   Nicole Couture  1534560336677       5
324721  1.136674e+20      Holly Chase  1601130739739       5
324722  1.010313e+20  Jennie Drummind  1503368927511       5
324723  1.135118e+20     John Hawkins  1566750149101       5
324724  1.076973e+20            Mindy  1521208726615       5

                                                     text  pics  \
0           Always done right from wood stove to screens!  None
1       A great company to work with.  Their sales and...  None
2       Great place to do business with staff was grea...  None
3       Awesome Customer service, quick response, and ...  None
4       If you need a top quality job, by a group of p...  None
...                                                   ...   ...
324720                                               None  None
324721                                               None  None
324722                                               None  None
324723                                               None  None
324724                                               None  None

                                                     resp  \
0       {'time': 1620087641504, 'text': 'Good Evening,...
1       {'time': 1580320228721, 'text': 'Good Afternoo...
2       {'time': 1605195166792, 'text': 'Hi Chad!

Tha...
3       {'time': 1593376422014, 'text': 'Mark, thank y...
4       {'time': 1582063833737, 'text': 'Good Afternoo...
...                                                   ...
324720  {'time': 1535421423802, 'text': 'Thank you for...
324721  {'time': 1601394881137, 'text': 'Holly, Thank ...
324722  {'time': 1503963258239, 'text': 'Jennie! Thank...
324723  {'time': 1566954272879, 'text': 'John, Thank y...
324724  {'time': 1521426846390, 'text': 'Thank you for...

                                      gmap_id
0       0x89e02445cb9db457:0x37f42bff4edf7a43
1       0x89e02445cb9db457:0x37f42bff4edf7a43
2       0x89e02445cb9db457:0x37f42bff4edf7a43
3       0x89e02445cb9db457:0x37f42bff4edf7a43
4       0x89e02445cb9db457:0x37f42bff4edf7a43
...                                       ...
324720  0x89e1c79c60aef325:0xbed8bfc41018f020
324721  0x89e1c79c60aef325:0xbed8bfc41018f020
324722  0x89e1c79c60aef325:0xbed8bfc41018f020
324723  0x89e1c79c60aef325:0xbed8bfc41018f020
324724  0x89e1c79c60aef325:0xbed8bfc41018f020

[324725 rows x 8 columns]

In [159]:
vermont.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.180269e+20,rebecca kerns,1620085852324,5,Always done right from wood stove to screens!,None,"{'time': 1620087641504, 'text': 'Good Evening,...",0x89e02445cb9db457:0x37f42bff4edf7a43
1,1.015327e+20,Peter DeForge,1580309946474,5,A great company to work with. Their sales and...,None,"{'time': 1580320228721, 'text': 'Good Afternoo...",0x89e02445cb9db457:0x37f42bff4edf7a43
2,1.154041e+20,Chad Goulette,1605195974445,5,Great place to do business with staff was grea...,None,"{'time': 1605195166792, 'text': 'Hi Chad! Tha...",0x89e02445cb9db457:0x37f42bff4edf7a43
3,1.047893e+20,Mark LaFountain,1593005848256,5,"Awesome Customer service, quick response, and ...",None,"{'time': 1593376422014, 'text': 'Mark, thank y...",0x89e02445cb9db457:0x37f42bff4edf7a43
4,1.089807e+20,Jeff R,1582059996120,5,"If you need a top quality job, by a group of p...",None,"{'time': 1582063833737, 'text': 'Good Afternoo...",0x89e02445cb9db457:0x37f42bff4edf7a43

In [160]:
vermont_filtrado = vermont.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [161]:
vermont_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17682 entries, 0 to 17681
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   user_id  17682 non-null  float64
 1   name     17682 non-null  object
 2   time     17682 non-null  int64
 3   rating   17682 non-null  int64
 4   text     10420 non-null  object
 5   pics     482 non-null    object
 6   resp     1307 non-null   object
 7   gmap_id  17682 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 1.1+ MB

In [162]:
# Convertir la columna 'time' a datetime
vermont_filtrado['time'] = pd.to_datetime(vermont_filtrado['time'], unit='ms')

In [163]:
vermont_filtrado = vermont_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [164]:
vermont_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [165]:
vermont_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    17365
Name: count, dtype: int64

In [166]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
vermont_filtrado.to_csv(os.path.join(ruta_reviews, "46-vermont.csv"),index= False)

47-Virginia

In [167]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-Virginia')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            virginia = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(virginia)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id            name           time  rating  \
0        1.116036e+20      Jessie Lee  1581455645898       5
1        1.062787e+20  Brittany Janis  1612044004790       2
2        1.075629e+20    Brandy Monge  1580144842073       5
3        1.000741e+20     Lisa Adkins  1612916442287       4
4        1.015055e+20     Bill Bercaw  1549752949680       2
...               ...             ...            ...     ...
1662054  1.016686e+20    dani morales  1524247477651       5
1662055  1.105558e+20   Ismael castro  1602522428859       5
1662056  1.176229e+20   jeremy states  1521326968661       3
1662057  1.160829e+20       Jon Henry  1525807809705       5
1662058  1.020335e+20  Joshua Lindsay  1515948880926       5

                                                      text  pics  \
0                           I loved Rita!! She was awesome  None
1                               Expensive to do taxes here  None
2          She was very helpful and made sure I understood  None
3                                            Tracey Spadey  None
4        I waited 1.5 hours for my Appointment because ...  None
...                                                    ...   ...
1662054                                               None  None
1662055                                               None  None
1662056                                               None  None
1662057                                               None  None
1662058                                               None  None

                                                      resp  \
0                                                     None
1        {'time': 1614371539737, 'text': 'Thank you for...
2                                                     None
3                                                     None
4                                                     None
...                                                    ...
1662054                                               None
1662055                                               None
1662056                                               None
1662057                                               None
1662058                                               None

                                       gmap_id
0        0x89b1af6550d33595:0x8fb8874b8aa57e3f
1        0x89b1af6550d33595:0x8fb8874b8aa57e3f
2        0x89b1af6550d33595:0x8fb8874b8aa57e3f
3        0x89b1af6550d33595:0x8fb8874b8aa57e3f
4        0x89b1af6550d33595:0x8fb8874b8aa57e3f
...                                        ...
1662054  0x89b492c92ee68717:0x7342bbf246de880b
1662055  0x89b492c92ee68717:0x7342bbf246de880b
1662056  0x89b492c92ee68717:0x7342bbf246de880b
1662057  0x89b492c92ee68717:0x7342bbf246de880b
1662058  0x89b492c92ee68717:0x7342bbf246de880b

[1662059 rows x 8 columns]

In [168]:
virginia.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.116036e+20,Jessie Lee,1581455645898,5,I loved Rita!! She was awesome,None,None,0x89b1af6550d33595:0x8fb8874b8aa57e3f
1,1.062787e+20,Brittany Janis,1612044004790,2,Expensive to do taxes here,None,"{'time': 1614371539737, 'text': 'Thank you for...",0x89b1af6550d33595:0x8fb8874b8aa57e3f
2,1.075629e+20,Brandy Monge,1580144842073,5,She was very helpful and made sure I understood,None,None,0x89b1af6550d33595:0x8fb8874b8aa57e3f
3,1.000741e+20,Lisa Adkins,1612916442287,4,Tracey Spadey,None,None,0x89b1af6550d33595:0x8fb8874b8aa57e3f
4,1.015055e+20,Bill Bercaw,1549752949680,2,I waited 1.5 hours for my Appointment because ...,None,None,0x89b1af6550d33595:0x8fb8874b8aa57e3f

In [169]:
virginia_filtrado = virginia.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [170]:
virginia_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 386729 entries, 0 to 386728
Data columns (total 8 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   user_id  386729 non-null  float64
 1   name     386729 non-null  object
 2   time     386729 non-null  int64
 3   rating   386729 non-null  int64
 4   text     228658 non-null  object
 5   pics     12489 non-null   object
 6   resp     37705 non-null   object
 7   gmap_id  386729 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 23.6+ MB

In [171]:
# Convertir la columna 'time' a datetime
virginia_filtrado['time'] = pd.to_datetime(virginia_filtrado['time'], unit='ms')

In [172]:
virginia_filtrado = virginia_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [173]:
virginia_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [174]:
virginia_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    373117
Name: count, dtype: int64

In [175]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
virginia_filtrado.to_csv(os.path.join(ruta_reviews, "47-virginia.csv"),index= False)

48-Washington

In [176]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-Washington')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            washington = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(washington)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id               name           time  rating  \
0        1.030930e+20      Casper Steele  1626907411534       2
1        1.110141e+20          Judy Maes  1613028426989       5
2        1.117244e+20   Daniel Hernandez  1536710665852       5
3        1.153311e+20          Lumi Nosa  1484359806540       5
4        1.069064e+20     James Conright  1500643741079       1
...               ...                ...            ...     ...
1942015  1.099295e+20           Prasad G  1566848691950       5
1942016  1.165459e+20  Preet Kamal Singh  1570550393071       5
1942017  1.032106e+20          jatt putt  1550381850870       5
1942018  1.036544e+20        Frank Evans  1567160556396       5
1942019  1.094439e+20     Sandra Russell  1553211279840       5

                                                      text  pics  \
0        Drivers say security has bathroom key. Securit...  None
1        It's a CTRAN transit center with schedules to ...  None
2        Neat little Transit Center with lots of schedu...  None
3                                    Very helpful.  Thanks  None
4                                   They don't sell tacos.  None
...                                                    ...   ...
1942015                             Nice  place  to visit.  None
1942016                                 Best pizza in town  None
1942017                               Best pizza I love it  None
1942018                                                Bam  None
1942019                      Amazing Pizza Amazing Service  None

                                                      resp  \
0                                                     None
1                                                     None
2                                                     None
3                                                     None
4                                                     None
...                                                    ...
1942015  {'time': 1566871454101, 'text': 'Thank you for...
1942016  {'time': 1570562467274, 'text': 'Thank you so ...
1942017  {'time': 1550769513812, 'text': 'Thank you so ...
1942018  {'time': 1567215089043, 'text': 'Thank you, Fr...
1942019  {'time': 1553620562270, 'text': 'Thank you for...

                                       gmap_id
0        0x5495ae7d3bf7d097:0xbcbc06152a3ccebc
1        0x5495ae7d3bf7d097:0xbcbc06152a3ccebc
2        0x5495ae7d3bf7d097:0xbcbc06152a3ccebc
3        0x5495ae7d3bf7d097:0xbcbc06152a3ccebc
4        0x5495ae7d3bf7d097:0xbcbc06152a3ccebc
...                                        ...
1942015  0x54905fc9357076eb:0xb98c4d55e9204118
1942016  0x54905fc9357076eb:0xb98c4d55e9204118
1942017  0x54905fc9357076eb:0xb98c4d55e9204118
1942018  0x54905fc9357076eb:0xb98c4d55e9204118
1942019  0x54905fc9357076eb:0xb98c4d55e9204118

[1942020 rows x 8 columns]

In [177]:
washington.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.030930e+20,Casper Steele,1626907411534,2,Drivers say security has bathroom key. Securit...,None,None,0x5495ae7d3bf7d097:0xbcbc06152a3ccebc
1,1.110141e+20,Judy Maes,1613028426989,5,It's a CTRAN transit center with schedules to ...,None,None,0x5495ae7d3bf7d097:0xbcbc06152a3ccebc
2,1.117244e+20,Daniel Hernandez,1536710665852,5,Neat little Transit Center with lots of schedu...,None,None,0x5495ae7d3bf7d097:0xbcbc06152a3ccebc
3,1.153311e+20,Lumi Nosa,1484359806540,5,Very helpful. Thanks,None,None,0x5495ae7d3bf7d097:0xbcbc06152a3ccebc
4,1.069064e+20,James Conright,1500643741079,1,They don't sell tacos.,None,None,0x5495ae7d3bf7d097:0xbcbc06152a3ccebc

In [178]:
washington_filtrado = washington.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [179]:
washington_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 363053 entries, 0 to 363052
Data columns (total 8 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   user_id  363053 non-null  float64
 1   name     363053 non-null  object
 2   time     363053 non-null  int64
 3   rating   363053 non-null  int64
 4   text     220714 non-null  object
 5   pics     14518 non-null   object
 6   resp     30146 non-null   object
 7   gmap_id  363053 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 22.2+ MB

In [180]:
# Convertir la columna 'time' a datetime
washington_filtrado['time'] = pd.to_datetime(washington_filtrado['time'], unit='ms')

In [181]:
washington_filtrado = washington_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [182]:
washington_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [183]:
washington_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    348825
Name: count, dtype: int64

In [184]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
washington_filtrado.to_csv(os.path.join(ruta_reviews, "48-washington.csv"),index= False)

49-West Virginia

In [185]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-West_Virginia')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            west_virginia = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(west_virginia)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id                name           time  rating  \
0        1.046492e+20         Pam Holcomb  1557935316444       4
1        1.009344e+20        Cheryl Norga  1532897953993       5
2        1.096628e+20         Jason Lough  1551725058851       3
3        1.094669e+20          Chris Cook  1574728085154       5
4        1.028647e+20         Dave Graley  1539855732886       4
...               ...                 ...            ...     ...
1080328  1.036087e+20  Cassandra Ferguson  1556339883438       5
1080329  1.110624e+20  Christine Lawrence  1609969451508       4
1080330  1.005872e+20      Brian Flanagan  1567975306006       4
1080331  1.024866e+20      Shannon Harvey  1580817558274       5
1080332  1.018518e+20     Greta Wilkinson  1601189039127       4

                                                      text  pics  resp  \
0        Nice personnel and atmosphere and have done bu...  None  None
1        Maggie is awesome..very sweet & helpful.\nLadi...  None  None
2         Little on the expensive side but friendly people  None  None
3                           Too bad this place is closing.  None  None
4                                                     None  None  None
...                                                    ...   ...   ...
1080328                                               None  None  None
1080329                                               None  None  None
1080330                                               None  None  None
1080331                                               None  None  None
1080332                                               None  None  None

                                       gmap_id
0        0x884955486c37d473:0x1b1f0907f74deee5
1        0x884955486c37d473:0x1b1f0907f74deee5
2        0x884955486c37d473:0x1b1f0907f74deee5
3        0x884955486c37d473:0x1b1f0907f74deee5
4        0x884955486c37d473:0x1b1f0907f74deee5
...                                        ...
1080328  0x8845dfe9876d06a7:0x29e23c6d6187cc02
1080329  0x8845dfe9876d06a7:0x29e23c6d6187cc02
1080330  0x8845dfe9876d06a7:0x29e23c6d6187cc02
1080331  0x8845dfe9876d06a7:0x29e23c6d6187cc02
1080332  0x8845dfe9876d06a7:0x29e23c6d6187cc02

[1080333 rows x 8 columns]

In [186]:
west_virginia.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.046492e+20,Pam Holcomb,1557935316444,4,Nice personnel and atmosphere and have done bu...,None,None,0x884955486c37d473:0x1b1f0907f74deee5
1,1.009344e+20,Cheryl Norga,1532897953993,5,Maggie is awesome..very sweet & helpful.\nLadi...,None,None,0x884955486c37d473:0x1b1f0907f74deee5
2,1.096628e+20,Jason Lough,1551725058851,3,Little on the expensive side but friendly people,None,None,0x884955486c37d473:0x1b1f0907f74deee5
3,1.094669e+20,Chris Cook,1574728085154,5,Too bad this place is closing.,None,None,0x884955486c37d473:0x1b1f0907f74deee5
4,1.028647e+20,Dave Graley,1539855732886,4,None,None,None,0x884955486c37d473:0x1b1f0907f74deee5

In [187]:
west_virginia_filtrado = west_virginia.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [188]:
west_virginia_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56478 entries, 0 to 56477
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   user_id  56478 non-null  float64
 1   name     56478 non-null  object
 2   time     56478 non-null  int64
 3   rating   56478 non-null  int64
 4   text     32048 non-null  object
 5   pics     1087 non-null   object
 6   resp     4771 non-null   object
 7   gmap_id  56478 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 3.4+ MB

In [189]:
# Convertir la columna 'time' a datetime
west_virginia_filtrado['time'] = pd.to_datetime(west_virginia_filtrado['time'], unit='ms')

In [190]:
west_virginia_filtrado = west_virginia_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [191]:
west_virginia_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [192]:
west_virginia_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    54755
Name: count, dtype: int64

In [193]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
west_virginia_filtrado.to_csv(os.path.join(ruta_reviews, "49-west_virginia.csv"),index= False)

50-Wisconsin

In [194]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-Wisconsin')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            wisconsin = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(wisconsin)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

              user_id               name           time  rating  \
0        1.054496e+20      Kadence Leigh  1592846644902       3
1        1.089909e+20     Jeremy Schafer  1534088176466       1
2        1.011444e+20      Kaden Lindner  1525430562021       1
3        1.034197e+20            J ellen  1594403566473       1
4        1.030543e+20  Stephanie Johnson  1575431324657       3
...               ...                ...            ...     ...
1686477  1.115248e+20      LeRoy Hibbard  1612644286410       4
1686478  1.127229e+20     Joyce Meredith  1603846471266       5
1686479  1.093270e+20     Ronna Blackley  1610851195055       5
1686480  1.056662e+20    Dave Matijevich  1605319176525       5
1686481  1.112598e+20           Mortisha  1600820330514       5

                                                      text  pics  resp  \
0        Fun although a lot of breaks witch sucks and t...  None  None
1        Management sucks they don't watch the  kids ha...  None  None
2        Horrible water so groups I saw a full diper on...  None  None
3                                                     None  None  None
4                                                     None  None  None
...                                                    ...   ...   ...
1686477  My wife went into there to get Mardi gras item...  None  None
1686478  Went there to buy a magnet, but couldn't find ...  None  None
1686479  I Always LOVE this Dollar Tree in Portage,  WI...  None  None
1686480  Busy store. Friendly staff. Have good prices o...  None  None
1686481  The young man at the register (Trey, I think h...  None  None

                                       gmap_id
0        0x87fd108d3f915a5f:0x2b7132092901f4df
1        0x87fd108d3f915a5f:0x2b7132092901f4df
2        0x87fd108d3f915a5f:0x2b7132092901f4df
3        0x87fd108d3f915a5f:0x2b7132092901f4df
4        0x87fd108d3f915a5f:0x2b7132092901f4df
...                                        ...
1686477  0x880726af5540b7d1:0xd6e8d5939b422ad6
1686478  0x880726af5540b7d1:0xd6e8d5939b422ad6
1686479  0x880726af5540b7d1:0xd6e8d5939b422ad6
1686480  0x880726af5540b7d1:0xd6e8d5939b422ad6
1686481  0x880726af5540b7d1:0xd6e8d5939b422ad6

[1686482 rows x 8 columns]

In [195]:
wisconsin.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.054496e+20,Kadence Leigh,1592846644902,3,Fun although a lot of breaks witch sucks and t...,None,None,0x87fd108d3f915a5f:0x2b7132092901f4df
1,1.089909e+20,Jeremy Schafer,1534088176466,1,Management sucks they don't watch the kids ha...,None,None,0x87fd108d3f915a5f:0x2b7132092901f4df
2,1.011444e+20,Kaden Lindner,1525430562021,1,Horrible water so groups I saw a full diper on...,None,None,0x87fd108d3f915a5f:0x2b7132092901f4df
3,1.034197e+20,J ellen,1594403566473,1,None,None,None,0x87fd108d3f915a5f:0x2b7132092901f4df
4,1.030543e+20,Stephanie Johnson,1575431324657,3,None,None,None,0x87fd108d3f915a5f:0x2b7132092901f4df

In [196]:
wisconsin_filtrado = wisconsin.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [197]:
wisconsin_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 248953 entries, 0 to 248952
Data columns (total 8 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   user_id  248953 non-null  float64
 1   name     248953 non-null  object
 2   time     248953 non-null  int64
 3   rating   248953 non-null  int64
 4   text     144630 non-null  object
 5   pics     5743 non-null    object
 6   resp     32871 non-null   object
 7   gmap_id  248953 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 15.2+ MB

In [198]:
# Convertir la columna 'time' a datetime
wisconsin_filtrado['time'] = pd.to_datetime(wisconsin_filtrado['time'], unit='ms')

In [199]:
wisconsin_filtrado = wisconsin_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [200]:
wisconsin_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [201]:
wisconsin_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    241599
Name: count, dtype: int64

In [202]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
wisconsin_filtrado.to_csv(os.path.join(ruta_reviews, "wisconsin.csv"),index= False)

51-Wyoming

In [203]:
import pandas as pd
import os
import glob

# Obtener la ruta del directorio actual de trabajo
current_dir = os.getcwd()

# Construir la ruta a la carpeta que contiene los archivos JSON
json_dir = os.path.join(current_dir, 'google', 'reviews', 'review-Wyoming')

# Verificar si el directorio existe
if not os.path.exists(json_dir):
    print(f"El directorio {json_dir} no existe.")
else:
    # Crear una lista para almacenar los DataFrames
    dataframes = []

    # Usar glob para encontrar todos los archivos JSON en la carpeta
    json_files = glob.glob(os.path.join(json_dir, '*.json'))

    # Verificar si se encontraron archivos JSON
    if not json_files:
        print(f"No se encontraron archivos JSON en {json_dir}.")
    else:
        # Leer cada archivo JSON y agregarlo a la lista de DataFrames
        for json_file in json_files:
            try:
                df = pd.read_json(json_file, lines=True)
                dataframes.append(df)
            except ValueError as e:
                print(f"Error al leer el archivo {json_file}: {e}")
            except Exception as e:
                print(f"Ocurrió un error inesperado al leer {json_file}: {e}")

        # Concatenar todos los DataFrames en uno solo (opcional)
        if dataframes:  # Verificar que la lista no esté vacía
            wyoming = pd.concat(dataframes, ignore_index=True)
            # Mostrar el DataFrame combinado
            print(wyoming)
        else:
            print("No se pudieron cargar DataFrames de los archivos JSON.")

             user_id              name           time  rating  \
0       1.114353e+20       Jenn Thomas  1602893531994       5
1       1.036137e+20    Michelle Barta  1575991509006       5
2       1.135567e+20    Bethany Baldes  1626981484302       5
3       1.022354e+20      nichole vogt  1583381337082       5
4       1.140217e+20     Kristi Friday  1571112557173       4
...              ...               ...            ...     ...
427803  1.078991e+20  Carlene Calabaza  1614741323428       5
427804  1.173878e+20             Gizmo  1561931911835       5
427805  1.078871e+20        Jan Soucek  1501029366785       5
427806  1.047652e+20    Kyle Leatherow  1565466860108       3
427807  1.079835e+20   Richard Bowling  1587302438249       3

                                                     text  pics  \
0       When knowledge is key and kindness matters, Ni...  None
1       The entire team is outstanding! They are profe...  None
2                                                    None  None
3                                                    None  None
4                                                    None  None
...                                                   ...   ...
427803                                               None  None
427804                                               None  None
427805                                               None  None
427806                                               None  None
427807                                               None  None

                                                     resp  \
0                                                    None
1       {'time': 1580484156696, 'text': 'We are lucky ...
2                                                    None
3                                                    None
4       {'time': 1571246498430, 'text': 'Thanks for th...
...                                                   ...
427803                                               None
427804                                               None
427805                                               None
427806                                               None
427807                                               None

                                      gmap_id
0       0x8758dd1ca83449d9:0xb6156dcfc5e04c9b
1       0x8758dd1ca83449d9:0xb6156dcfc5e04c9b
2       0x8758dd1ca83449d9:0xb6156dcfc5e04c9b
3       0x8758dd1ca83449d9:0xb6156dcfc5e04c9b
4       0x8758dd1ca83449d9:0xb6156dcfc5e04c9b
...                                       ...
427803  0x53349429523d615b:0x2a66a9272032e8b4
427804  0x53349429523d615b:0x2a66a9272032e8b4
427805  0x53349429523d615b:0x2a66a9272032e8b4
427806  0x53349429523d615b:0x2a66a9272032e8b4
427807  0x53349429523d615b:0x2a66a9272032e8b4

[427808 rows x 8 columns]

In [204]:
wyoming.head()

,user_id,name,time,rating,text,pics,resp,gmap_id
0,1.114353e+20,Jenn Thomas,1602893531994,5,"When knowledge is key and kindness matters, Ni...",None,None,0x8758dd1ca83449d9:0xb6156dcfc5e04c9b
1,1.036137e+20,Michelle Barta,1575991509006,5,The entire team is outstanding! They are profe...,None,"{'time': 1580484156696, 'text': 'We are lucky ...",0x8758dd1ca83449d9:0xb6156dcfc5e04c9b
2,1.135567e+20,Bethany Baldes,1626981484302,5,None,None,None,0x8758dd1ca83449d9:0xb6156dcfc5e04c9b
3,1.022354e+20,nichole vogt,1583381337082,5,None,None,None,0x8758dd1ca83449d9:0xb6156dcfc5e04c9b
4,1.140217e+20,Kristi Friday,1571112557173,4,None,None,"{'time': 1571246498430, 'text': 'Thanks for th...",0x8758dd1ca83449d9:0xb6156dcfc5e04c9b

In [205]:
wyoming_filtrado = wyoming.merge(restaurantes.to_frame(name='gmap_id'), on='gmap_id')

In [206]:
wyoming_filtrado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18018 entries, 0 to 18017
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   user_id  18018 non-null  float64
 1   name     18018 non-null  object
 2   time     18018 non-null  int64
 3   rating   18018 non-null  int64
 4   text     10541 non-null  object
 5   pics     337 non-null    object
 6   resp     1660 non-null   object
 7   gmap_id  18018 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 1.1+ MB

In [207]:
# Convertir la columna 'time' a datetime
wyoming_filtrado['time'] = pd.to_datetime(wyoming_filtrado['time'], unit='ms')

In [208]:
wyoming_filtrado = wyoming_filtrado[["user_id","name","time","rating","text","gmap_id"]]

In [209]:
wyoming_filtrado.drop_duplicates(subset=["time", "text", "user_id"], inplace=True)

In [210]:
wyoming_filtrado[["time","text","user_id"]].duplicated().value_counts()

False    17491
Name: count, dtype: int64

In [211]:
# Define la ruta del directorio
directorio = os.getcwd()

# Verifica si el directorio "Datos Limpios" existe y si no, lo crea
ruta_datos_limpios = os.path.join(directorio, "Datos Limpios")
if not os.path.exists(ruta_datos_limpios):
    os.makedirs(ruta_datos_limpios)

# Verifica si la carpeta "reviews" existe dentro de "Datos Limpios" y si no, la crea
ruta_reviews = os.path.join(ruta_datos_limpios, "reviews")
if not os.path.exists(ruta_reviews):
    os.makedirs(ruta_reviews)


# Guarda el DataFrame como un archivo CSV en la carpeta "reviews"
wyoming_filtrado.to_csv(os.path.join(ruta_reviews, "51-wyoming.csv"),index= False)

In [ ]:
# Detiene el temporizador
fin = time.time()

# Calcula el tiempo de ejecución en minutos
tiempo_ejecucion = (fin - inicio) / 60
print(f'Tiempo de ejecución: {tiempo_ejecucion:.2f} minutos')